import type { MultiCutReplayProductionBridgeContract } from "./types";

export const MULTI_CUT_REPLAY_PRODUCTION_BRIDGE_CONTRACT =
  Object.freeze({
    contractVersion: "1.0",
    command: Object.freeze({
      owner: "pg-query-result",
      productionSource: "PostgreSQLQueryResult.command",
      replayTarget: "MultiCutReplayPostgresqlFakeClientResult.command",
      projection: "direct",
      inference: "forbidden",
    }),
    zeroRow: Object.freeze({
      owner: "multi-cut-replay-postgresql-pure-adapter",
      driverExpectedResult: "many",
      bridgeClassification: "none",
      preservedCardinalities: Object.freeze([0, 1, "multiple"] as const),
    }),
    parameters: Object.freeze([
      Object.freeze({
        cast: "uuid",
        acceptedInput: "canonical-lowercase-uuid-string",
        normalization: "canonical-validation-only",
        parameterKind: "uuid",
        nullable: false,
        invalidInput: "fail-closed-before-query",
        overflow: "not-applicable",
        precision: "exact",
      }),
      Object.freeze({
        cast: "text",
        acceptedInput: "string",
        normalization: "none",
        parameterKind: "string",
        nullable: false,
        invalidInput: "fail-closed-before-query",
        overflow: "reject-if-driver-limit-exceeded",
        precision: "exact",
      }),
      Object.freeze({
        cast: "integer",
        acceptedInput: "safe-integer-within-postgresql-int4-range",
        normalization: "canonical-validation-only",
        parameterKind: "safe-integer",
        nullable: false,
        invalidInput: "fail-closed-before-query",
        overflow: "reject-outside-minus-2147483648-to-2147483647",
        precision: "exact",
      }),
      Object.freeze({
        cast: "bigint",
        acceptedInput: "canonical-decimal-string-within-postgresql-int8-range",
        normalization: "canonical-validation-only",
        parameterKind: "bigint",
        nullable: false,
        invalidInput: "fail-closed-before-query",
        overflow:
          "reject-outside-minus-9223372036854775808-to-9223372036854775807",
        precision: "exact",
      }),
      Object.freeze({
        cast: "timestamptz",
        acceptedInput: "canonical-utc-timestamp-string-ending-in-Z",
        normalization: "canonical-validation-only",
        parameterKind: "utc-timestamp",
        nullable: false,
        invalidInput: "fail-closed-before-query",
        overflow: "reject-non-finite-or-out-of-range",
        precision: "exact",
      }),
    ]),
    result: Object.freeze({
      fields: Object.freeze(["rows", "rowCount", "command"] as const),
      rows: "decoded-values-copy-isolated",
      rowCount: "direct",
      command: "direct",
      null: "preserve",
      undefined: "fail-closed",
      domainMapping: "forbidden",
    }),
    failures: Object.freeze(([
      ["invalid-request", "query-rejected", false, false, "not-retained", "not-required"],
      ["query-cancelled", "query-rejected", false, false, "safe-class-only", "not-required"],
      ["timeout", "query-rejected", true, false, "not-retained", "not-required"],
      ["connection-unavailable", "connection-unavailable", false, false, "safe-class-only", "required"],
      ["schema-mismatch", "query-rejected", false, false, "safe-class-only", "required"],
      ["constraint-conflict", "query-rejected", false, false, "safe-class-only", "required"],
      ["retryable-conflict", "serialization-conflict", true, false, "safe-class-only", "not-required"],
      ["read-only", "query-rejected", false, false, "safe-class-only", "not-required"],
      ["insufficient-privilege", "query-rejected", false, false, "safe-class-only", "not-required"],
      ["unknown-failure", "query-rejected", false, false, "not-retained", "required"],
      ["disposed", "transaction-rejected", false, false, "not-retained", "required"],
      ["commit-outcome-unknown", "commit-outcome-unknown", false, true, "not-retained", "required"],
      ["non-postgresql-thrown-value", "query-rejected", false, false, "not-retained", "required"],
    ] as const).map(([source, target, retryable, commitUnknown, sqlState, reconciliation]) =>
      Object.freeze({
        source,
        target,
        retryable,
        commitUnknown,
        originalCause: "not-exposed",
        sqlState,
        safeReason: "classified-safe-reason",
        reconciliation,
      }),
    )),
    connections: Object.freeze(([
      ["acquired", "allowed", "allowed", "same-terminal-outcome", "return-to-pool", "release"],
      ["transaction-open", "prohibited", "allowed", "prohibited-while-active", "transaction-must-finish-first", "not-reachable"],
      ["committed", "allowed", "allowed", "same-terminal-outcome", "return-to-pool", "release"],
      ["rolled-back", "allowed", "allowed", "same-terminal-outcome", "return-to-pool", "release"],
      ["commit-unknown", "idempotent-no-op", "required", "same-terminal-outcome", "destroy-connection", "no-op"],
      ["discarded", "idempotent-no-op", "idempotent-no-op", "same-terminal-outcome", "none", "no-op"],
      ["released", "idempotent-no-op", "idempotent-no-op", "same-terminal-outcome", "none", "no-op"],
    ] as const).map(([state, release, discard, repeatedCall, underlyingAction, runtimeReleaseResult]) =>
      Object.freeze({
        state,
        release,
        discard,
        repeatedCall,
        underlyingAction,
        runtimeReleaseResult,
      }),
    )),
    transactionOwner: "multi-cut-replay-postgresql-execution-runtime",
    mechanismProvider: "production-postgresql-driver",
    dependencyDirection: Object.freeze({
      bridgeDependsOn: Object.freeze([
        "multi-cut-replay-postgresql-driver-types",
        "production-postgresql-driver-types",
      ] as const),
      forbidden: Object.freeze([
        "production-driver-to-replay",
        "pure-adapter-to-production-driver",
        "execution-runtime-to-pg",
        "sql-definitions-to-driver",
        "circular-dependency",
      ] as const),
    }),
  } satisfies MultiCutReplayProductionBridgeContract);
