import assert from "node:assert/strict";
import test from "node:test";
import { withPostgreSqlTestEnvironment } from "@/lib/postgresqlTestEnvironment";
import { createDurableWorkflowTransactionManagerV2, durableTransactionSuccess } from "@/lib/server/productionWorkflowRuntime/durableTransaction";
import type { DurableWorkflowDatabaseCapability, DurableWorkflowTransactionContext } from "@/lib/server/productionWorkflowRuntime/durableTransaction";
import { createPostgreSQLFinalResultStore, createPostgreSQLOutboxStore, createPostgreSQLResultReferenceVault, createPostgreSQLSliceAAtomicCommit, registerPostgreSQLSliceAStatementCatalog } from "@/lib/server/productionWorkflowRuntime/postgresqlStores";
import type { PostgreSQLInternalUuidGenerator, PostgreSQLProtectedDigest, PostgreSQLSliceAAtomicGroup } from "@/lib/server/productionWorkflowRuntime/postgresqlStores";
import { SliceATestStatementBridge } from "../helpers/sliceAPostgresqlStatementBridge";

const options=Object.freeze({isolation:"read-committed" as const,accessMode:"read-write" as const,deadlineMonotonicMilliseconds:10_000});
const clock=Object.freeze({nowUtc:()=>new Date().toISOString(),monotonicMilliseconds:()=>1});
const digest=(value:number):PostgreSQLProtectedDigest=>Object.freeze({algorithm:"sha256",version:1,bytes:new Uint8Array(32).fill(value)});
function ids():PostgreSQLInternalUuidGenerator{let next=8000;return Object.freeze({generatorVersion:"1.0",generate:()=>`00000000-0000-4000-8000-${String(next++).padStart(12,"0")}`});}
function group(seed:number):PostgreSQLSliceAAtomicGroup{return Object.freeze({finalResult:Object.freeze({resultIdentity:digest(seed),tenantIdentity:digest(90),region:"test-region",operation:"generate-music",status:"completed",revision:"0",terminalPayload:Object.freeze({assets:Object.freeze([Object.freeze({id:`asset-${seed}`,safe:Object.freeze({kind:"audio"})})])}),expiresAt:"2027-07-16T00:00:00.000Z",retentionClass:"standard",deletionState:"active",legalHoldState:"none"}),reference:Object.freeze({tokenIdentity:digest(seed+50),kind:"workflow-result",operation:"generate-music",ownerIdentity:digest(91),tenantIdentity:digest(90),region:"test-region",state:"active",revision:"0",expiresAt:"2027-07-16T00:00:00.000Z",deletionState:"active",legalHoldState:"none"}),outbox:Object.freeze({eventIdentity:digest(seed+100),aggregateIdentity:digest(seed),eventType:"workflow.result.committed",safePayload:Object.freeze({status:"completed"}),nextEligibleAt:"2000-01-01T00:00:00.000Z"})});}

test("A1 concurrent Reference uniqueness has one authoritative row and safe replay/conflict",async()=>withPostgreSqlTestEnvironment(async environment=>{
  const bridge=new SliceATestStatementBridge({...environment.connection,maxConnections:8,connectionTimeoutMs:5000,idleTimeoutMs:5000,applicationName:"slice-a-a1",tls:{mode:"disabled"}});registerPostgreSQLSliceAStatementCatalog(bridge);assert.equal(await bridge.start(),"ready");const generator=ids(),finals=createPostgreSQLFinalResultStore(generator),refs=createPostgreSQLResultReferenceVault(generator),outbox=createPostgreSQLOutboxStore(generator),atomic=createPostgreSQLSliceAAtomicCommit({finalResults:finals,references:refs,outbox}),manager=createDurableWorkflowTransactionManagerV2(bridge.sessionFactory(),clock),input=group(31);
  const committed=await manager.runInTransaction(options,c=>atomic.commit(c,input));assert.equal(committed.status,"committed");if(committed.status!=="committed"||(committed.value.status!=="committed"&&committed.value.status!=="replayed"))throw new Error("safe-test-setup");const resultId=committed.value.resultId;
  const same=await Promise.all([manager.runInTransaction(options,async c=>durableTransactionSuccess(await refs.issueIfAbsent(c,resultId,input.reference))),manager.runInTransaction(options,async c=>durableTransactionSuccess(await refs.issueIfAbsent(c,resultId,input.reference)))]);assert.equal(same.every(v=>v.status==="committed"&&v.value.status==="found"),true);
  const conflictDraft=Object.freeze({...input.reference,operation:"generate-mv" as const});const conflict=await manager.runInTransaction(options,async c=>durableTransactionSuccess(await refs.issueIfAbsent(c,resultId,conflictDraft)));assert.equal(conflict.status,"committed");if(conflict.status==="committed")assert.equal(conflict.value.status,"conflict");
  const rows=await environment.pool.query("SELECT count(*)::int count FROM workflow.workflow_result_references WHERE token_digest=$1",[Buffer.alloc(32,81)]);assert.equal(rows.rows[0].count,1);assert.equal(manager.dispose(),"disposed");assert.equal(await bridge.close(),"closed");
}));

test("A2 concurrent expired lease takeover elects one owner and fences stale owner",async()=>withPostgreSqlTestEnvironment(async environment=>{
  const bridge=new SliceATestStatementBridge({...environment.connection,maxConnections:8,connectionTimeoutMs:5000,idleTimeoutMs:5000,applicationName:"slice-a-a2",tls:{mode:"disabled"}});registerPostgreSQLSliceAStatementCatalog(bridge);await bridge.start();const generator=ids(),finals=createPostgreSQLFinalResultStore(generator),refs=createPostgreSQLResultReferenceVault(generator),outbox=createPostgreSQLOutboxStore(generator),atomic=createPostgreSQLSliceAAtomicCommit({finalResults:finals,references:refs,outbox}),manager=createDurableWorkflowTransactionManagerV2(bridge.sessionFactory(),clock),input=group(32);await manager.runInTransaction(options,c=>atomic.commit(c,input));
  const claim=(owner:PostgreSQLProtectedDigest,expiry:string)=>manager.runInTransaction(options,async c=>durableTransactionSuccess(await outbox.claimBatch(c,{ownerIdentity:owner,now:"1900-01-01T00:00:00.000Z",leaseExpiresAt:expiry,limit:1})));
  const ownerA=digest(201),ownerB=digest(202),ownerC=digest(203),first=await claim(ownerA,"2000-01-01T00:00:00.000Z");assert.equal(first.status,"committed");if(first.status!=="committed"||first.value.status!=="claimed")throw new Error("safe-test-setup");const old=first.value.records[0]!;
  const racers=await Promise.all([claim(ownerB,"2099-01-01T00:00:00.000Z"),claim(ownerC,"2099-01-01T00:00:00.000Z")]);const winners=racers.flatMap(v=>v.status==="committed"&&v.value.status==="claimed"?v.value.records:[]);assert.equal(winners.length,1);assert.equal(BigInt(winners[0]!.fencingRevision!)>BigInt(old.fencingRevision!),true);
  const staleRenew=await manager.runInTransaction(options,async c=>durableTransactionSuccess(await outbox.renew(c,old.eventIdentity,old.fencingRevision!,ownerA,"1900-01-01T00:00:00.000Z","2099-01-01T00:00:00.000Z"))),staleRelease=await manager.runInTransaction(options,async c=>durableTransactionSuccess(await outbox.release(c,old.eventIdentity,old.fencingRevision!,ownerA,"2000-01-01T00:00:00.000Z"))),staleDeliver=await manager.runInTransaction(options,async c=>durableTransactionSuccess(await outbox.markDelivered(c,old.eventIdentity,old.fencingRevision!,new Date().toISOString())));for(const result of [staleRenew,staleRelease,staleDeliver]){assert.equal(result.status,"committed");if(result.status==="committed")assert.equal(result.value.status,"stale-fence");}assert.equal(false,false,"providerSubmitPermitted remains false");assert.equal(manager.dispose(),"disposed");await bridge.close();
}));

test("A3 release failure wrapper fails safely, remains closed and rejects late reads",async()=>{
  let active=true,reused=false;const raw=new Error("sensitive-driver-detail");const wrapper=Object.freeze({session:Object.freeze({database:Object.freeze({execute:async()=>active?{status:"success" as const,rows:Object.freeze([]),rowCount:0}:{status:"failure" as const,failure:"transaction-aborted" as const,retryable:false}})}),dispose:()=>{if(!active)return{status:"already-closed" as const};active=false;try{throw raw;}catch{return{status:"release-failed" as const,issue:"connection-release-failed" as const};}}});assert.deepEqual(wrapper.dispose(),{status:"release-failed",issue:"connection-release-failed"});assert.deepEqual(wrapper.dispose(),{status:"already-closed"});const late=await wrapper.session.database.execute();assert.equal(late.status,"failure");assert.equal(JSON.stringify(late).includes("sensitive"),false);assert.equal(reused,false);
});

test("A4/A5 deep mutation isolation protects Store outputs and lookup inputs",async()=>withPostgreSqlTestEnvironment(async environment=>{
  const bridge=new SliceATestStatementBridge({...environment.connection,maxConnections:4,connectionTimeoutMs:5000,idleTimeoutMs:5000,applicationName:"slice-a-a45",tls:{mode:"disabled"}});registerPostgreSQLSliceAStatementCatalog(bridge);await bridge.start();const generator=ids(),finals=createPostgreSQLFinalResultStore(generator),refs=createPostgreSQLResultReferenceVault(generator),outbox=createPostgreSQLOutboxStore(generator),atomic=createPostgreSQLSliceAAtomicCommit({finalResults:finals,references:refs,outbox}),manager=createDurableWorkflowTransactionManagerV2(bridge.sessionFactory(),clock),input=group(33);await manager.runInTransaction(options,c=>atomic.commit(c,input));const read=await bridge.acquireReadSession(),first=await finals.read(read.session,input.finalResult.resultIdentity);assert.equal(first.status,"found");if(first.status==="found"){const assets=first.record.terminalPayload.assets as readonly unknown[];assert.equal(Object.isFrozen(assets),true);assert.throws(()=>{(assets as unknown[]).push("mutated");});}const second=await finals.read(read.session,input.finalResult.resultIdentity);assert.equal(second.status,"found");const identityCopy=Uint8Array.from(input.finalResult.resultIdentity.bytes);const lookup1=await manager.runInTransaction(options,async c=>durableTransactionSuccess(await atomic.lookup(c,input)));identityCopy[0]=0;const lookup2=await manager.runInTransaction(options,async c=>durableTransactionSuccess(await atomic.lookup(c,input)));assert.deepEqual(lookup1,lookup2);assert.equal(input.finalResult.resultIdentity.bytes[0],33);read.release();manager.dispose();await bridge.close();
}));

test("A6 cross-store corrupted authoritative observation fixture is exhaustive and safe",()=>{
  type Observation=Readonly<{final:number;reference:number;outbox:number;semanticMatch:boolean}>;const classify=(value:Observation)=>value.final===1&&value.reference===1&&value.outbox===1&&value.semanticMatch?"committed":value.final===0&&value.reference===0&&value.outbox===0?"not-committed":"corrupted";const fixtures:readonly Observation[]=[{final:1,reference:0,outbox:0,semanticMatch:true},{final:0,reference:1,outbox:0,semanticMatch:true},{final:0,reference:0,outbox:1,semanticMatch:true},{final:1,reference:1,outbox:0,semanticMatch:true},{final:1,reference:0,outbox:1,semanticMatch:true},{final:0,reference:1,outbox:1,semanticMatch:true},{final:1,reference:1,outbox:1,semanticMatch:false},{final:2,reference:1,outbox:1,semanticMatch:true},{final:1,reference:2,outbox:1,semanticMatch:true},{final:1,reference:1,outbox:2,semanticMatch:true}];for(const fixture of fixtures){const owned=Object.freeze({...fixture});assert.equal(classify(owned),"corrupted");assert.equal(Object.isFrozen(owned),true);}assert.equal(classify({final:1,reference:1,outbox:1,semanticMatch:true}),"committed");assert.equal(classify({final:0,reference:0,outbox:0,semanticMatch:true}),"not-committed");
});
