import assert from "node:assert/strict";
import test from "node:test";
import { withPostgreSqlTestEnvironment } from "@/lib/postgresqlTestEnvironment";
import { createDurableWorkflowTransactionManagerV2, durableTransactionFailure, durableTransactionSuccess } from "@/lib/server/productionWorkflowRuntime/durableTransaction";
import type { DurableWorkflowDatabaseCapability, DurableWorkflowDatabaseExecutionResult, DurableWorkflowTransactionContext } from "@/lib/server/productionWorkflowRuntime/durableTransaction";
import { createPostgreSQLFinalResultStore, createPostgreSQLOutboxStore, createPostgreSQLResultReferenceVault, createPostgreSQLSliceAAtomicCommit, getPostgreSQLSliceAStoreDescriptor, listPostgreSQLSliceAStoreDescriptors, parseFinalResultRow, POSTGRESQL_SLICE_A_STATEMENT_CATALOG, registerPostgreSQLSliceAStatementCatalog } from "@/lib/server/productionWorkflowRuntime/postgresqlStores";
import type { PostgreSQLInternalUuidGenerator, PostgreSQLProtectedDigest, PostgreSQLSliceAAtomicGroup, PostgreSQLSliceAUnknownLookupResult } from "@/lib/server/productionWorkflowRuntime/postgresqlStores";
import { SliceATestStatementBridge } from "../helpers/sliceAPostgresqlStatementBridge";

const options=Object.freeze({isolation:"read-committed" as const,accessMode:"read-write" as const,deadlineMonotonicMilliseconds:10_000});
const clock=Object.freeze({nowUtc:()=>"2026-07-16T00:00:00.000Z",monotonicMilliseconds:()=>1});
const digest=(value:number):PostgreSQLProtectedDigest=>Object.freeze({algorithm:"sha256",version:1,bytes:new Uint8Array(32).fill(value)});
function ids():PostgreSQLInternalUuidGenerator{let next=1000;return Object.freeze({generatorVersion:"1.0",generate:()=>`00000000-0000-4000-8000-${String(next++).padStart(12,"0")}`});}
function group(seed:number):PostgreSQLSliceAAtomicGroup{return Object.freeze({finalResult:Object.freeze({resultIdentity:digest(seed),tenantIdentity:digest(90),region:"test-region",operation:"generate-music",status:"completed",revision:"0",terminalPayload:Object.freeze({assets:Object.freeze([`safe-${seed}`])}),expiresAt:"2027-07-16T00:00:00.000Z",retentionClass:"standard",deletionState:"active",legalHoldState:"none"}),reference:Object.freeze({tokenIdentity:digest(seed+40),kind:"workflow-result",operation:"generate-music",ownerIdentity:digest(91),tenantIdentity:digest(90),region:"test-region",state:"active",revision:"0",expiresAt:"2027-07-16T00:00:00.000Z",deletionState:"active",legalHoldState:"none"}),outbox:Object.freeze({eventIdentity:digest(seed+80),aggregateIdentity:digest(seed),eventType:"workflow.result.committed",safePayload:Object.freeze({status:"completed"}),nextEligibleAt:"2026-07-16T00:00:00.000Z"})});}
function fakeContext(database:DurableWorkflowDatabaseCapability):DurableWorkflowTransactionContext{return Object.freeze({contextVersion:"2.0",scope:"opaque-production-durable-transaction-scope",startedAt:"2026-07-16T00:00:00.000Z",deadlineMonotonicMilliseconds:10_000,externalIoAllowed:false,database,state:()=>"active"}) as DurableWorkflowTransactionContext;}

test("statement catalog, registry and read-session verification matrix",async()=>withPostgreSqlTestEnvironment(async environment=>{
  const bridge=new SliceATestStatementBridge({...environment.connection,maxConnections:8,connectionTimeoutMs:5000,idleTimeoutMs:5000,applicationName:"slice-a-verification",tls:{mode:"disabled"}});
  assert.equal(registerPostgreSQLSliceAStatementCatalog(bridge),"registered");assert.equal(registerPostgreSQLSliceAStatementCatalog(bridge),"registered");assert.equal(await bridge.start(),"ready");
  const expected=new Map<string,[number,string,string]>([["slice-a.final.insert",[12,"many","write"]],["slice-a.final.read",[1,"single","read"]],["slice-a.final.cas",[4,"single","write"]],["slice-a.reference.insert",[13,"many","write"]],["slice-a.reference.read",[1,"single","read"]],["slice-a.reference.cas",[4,"single","write"]],["slice-a.outbox.insert",[7,"many","write"]],["slice-a.outbox.read",[1,"single","read"]],["slice-a.outbox.claim",[4,"many","write"]],["slice-a.outbox.renew",[5,"many","write"]],["slice-a.outbox.release",[5,"many","write"]],["slice-a.outbox.reconcile",[3,"many","write"]],["slice-a.outbox.deliver",[3,"many","write"]],["slice-a.atomic.lookup",[3,"single","read"]]]);
  assert.equal(Object.isFrozen(POSTGRESQL_SLICE_A_STATEMENT_CATALOG),true);assert.equal(Object.isFrozen(POSTGRESQL_SLICE_A_STATEMENT_CATALOG.statements),true);
  for(const statement of POSTGRESQL_SLICE_A_STATEMENT_CATALOG.statements){assert.equal(Object.isFrozen(statement),true);assert.deepEqual([statement.parameterCount,statement.cardinality,statement.accessMode],expected.get(statement.statementId));}
  const read=await bridge.acquireReadSession();assert.equal(read.state(),"active");const unknown=await read.session.database.execute(Object.freeze({commandVersion:"1.0",statementId:"slice-a.unknown",parameters:Object.freeze([]),expectedResult:"single"}));assert.equal(unknown.status,"failure");assert.equal(read.release(),"released");assert.equal(read.state(),"closed");assert.equal(read.release(),"already-released");const late=await read.session.database.execute(Object.freeze({commandVersion:"1.0",statementId:"slice-a.final.read",parameters:Object.freeze([digest(1).bytes]),expectedResult:"single"}));assert.deepEqual(late,{status:"failure",failure:"transaction-aborted",retryable:false});
  const first=listPostgreSQLSliceAStoreDescriptors(),second=listPostgreSQLSliceAStoreDescriptors();assert.notEqual(first,second);assert.notEqual(first[0],second[0]);assert.equal(first[0]!.runtimeComposable,false);assert.equal(getPostgreSQLSliceAStoreDescriptor("unknown"),undefined);
  assert.equal(await bridge.close(),"closed");
}));

test("real PostgreSQL lifecycle, rejection, visibility and concurrency matrix",async()=>withPostgreSqlTestEnvironment(async environment=>{
  const bridge=new SliceATestStatementBridge({...environment.connection,maxConnections:16,connectionTimeoutMs:5000,idleTimeoutMs:5000,applicationName:"slice-a-matrix",tls:{mode:"disabled"}});registerPostgreSQLSliceAStatementCatalog(bridge);assert.equal(await bridge.start(),"ready");
  const generator=ids(),finals=createPostgreSQLFinalResultStore(generator),refs=createPostgreSQLResultReferenceVault(generator),outbox=createPostgreSQLOutboxStore(generator),atomic=createPostgreSQLSliceAAtomicCommit({finalResults:finals,references:refs,outbox}),manager=createDurableWorkflowTransactionManagerV2(bridge.sessionFactory(),clock);
  for(const seed of [10,11,12,13,14,15]){const result=await manager.runInTransaction(options,c=>atomic.commit(c,group(seed)));assert.equal(result.status,"committed");}
  await assert.rejects(environment.pool.query("INSERT INTO workflow.workflow_final_results SELECT * FROM workflow.workflow_final_results LIMIT 1"));
  await assert.rejects(environment.pool.query("UPDATE workflow.workflow_final_results SET result_status='non-terminal' WHERE result_digest=$1",[Buffer.alloc(32,10)]));
  await assert.rejects(environment.pool.query("UPDATE workflow.workflow_result_references SET reference_state='deleted',deletion_state='active' WHERE token_digest=$1",[Buffer.alloc(32,50)]));
  const transition=await manager.runInTransaction(options,async c=>{const revoked=await refs.revoke(c,digest(50),"0");if(revoked.status!=="found")return durableTransactionFailure("transaction-aborted");const expired=await refs.expire(c,digest(50),revoked.record.revision);if(expired.status!=="found")return durableTransactionFailure("transaction-aborted");const deleted=await refs.delete(c,digest(50),expired.record.revision);return deleted.status==="found"?durableTransactionSuccess(deleted.record):durableTransactionFailure("transaction-aborted");});assert.equal(transition.status,"committed");if(transition.status==="committed")assert.deepEqual([transition.value.state,transition.value.deletionState],["deleted","deleted"]);
  const staleCas=await manager.runInTransaction(options,async c=>durableTransactionSuccess(await finals.compareAndSet(c,digest(10),"99",{deletionState:"deletion-pending",legalHoldState:"none"})));assert.equal(staleCas.status,"committed");if(staleCas.status==="committed")assert.equal(staleCas.value.status,"conflict");
  const concurrentCas=await Promise.all([manager.runInTransaction(options,async c=>durableTransactionSuccess(await finals.compareAndSet(c,digest(11),"0",{deletionState:"deletion-pending",legalHoldState:"none"}))),manager.runInTransaction(options,async c=>durableTransactionSuccess(await finals.compareAndSet(c,digest(11),"0",{deletionState:"active",legalHoldState:"held"})))]);assert.deepEqual(concurrentCas.map(v=>v.status==="committed"?v.value.status:v.status).sort(),["conflict","updated"]);
  const read=await bridge.acquireReadSession();const visible=await finals.read(read.session,digest(12));assert.equal(visible.status,"found");read.release();
  const ownerA=digest(200),ownerB=digest(201);const claim=async(owner:PostgreSQLProtectedDigest,now:string,expiry:string,limit=20)=>manager.runInTransaction(options,async c=>durableTransactionSuccess(await outbox.claimBatch(c,{ownerIdentity:owner,now,leaseExpiresAt:expiry,limit})));
  const parallel=await Promise.all([claim(ownerA,"2026-07-16T00:00:00.000Z","2026-07-16T00:10:00.000Z",3),claim(ownerB,"2026-07-16T00:00:00.000Z","2026-07-16T00:10:00.000Z",3)]);const claimedIds=parallel.flatMap(v=>v.status==="committed"&&v.value.status==="claimed"?v.value.records.map(r=>r.internalId):[]);assert.equal(new Set(claimedIds).size,claimedIds.length);
  const record=parallel.flatMap(v=>v.status==="committed"&&v.value.status==="claimed"?v.value.records:[])[0]!;const stale=await manager.runInTransaction(options,async c=>durableTransactionSuccess(await outbox.renew(c,record.eventIdentity,"999",ownerA,"2026-07-16T00:01:00.000Z","2026-07-16T00:20:00.000Z")));assert.equal(stale.status,"committed");if(stale.status==="committed")assert.equal(stale.value.status,"stale-fence");
  const owner=record.claimOwnerIdentity!;const released=await manager.runInTransaction(options,async c=>durableTransactionSuccess(await outbox.release(c,record.eventIdentity,record.fencingRevision!,owner,"2026-07-16T00:00:00.000Z")));assert.equal(released.status,"committed");if(released.status==="committed")assert.equal(released.value.status,"delivered");const reclaimed=await claim(ownerB,"2026-07-16T00:02:00.000Z","2026-07-16T00:20:00.000Z",1);assert.equal(reclaimed.status,"committed");if(reclaimed.status==="committed")assert.equal(reclaimed.value.status,"claimed");
  const reconcileTarget=parallel.flatMap(v=>v.status==="committed"&&v.value.status==="claimed"?v.value.records:[]).find(r=>r.internalId!==record.internalId)!;const reconciled=await manager.runInTransaction(options,async c=>durableTransactionSuccess(await outbox.markReconciliationRequired(c,reconcileTarget.eventIdentity,reconcileTarget.revision,"delivery-unknown")));assert.equal(reconciled.status,"committed");if(reconciled.status==="committed")assert.equal(reconciled.value.status,"delivered");
  const expiredTarget=parallel.flatMap(v=>v.status==="committed"&&v.value.status==="claimed"?v.value.records:[]).find(r=>r.internalId!==record.internalId&&r.internalId!==reconcileTarget.internalId);if(expiredTarget){await environment.pool.query("UPDATE workflow.workflow_outbox_events SET lease_expires_at='2026-07-16T00:00:00Z' WHERE event_id=$1",[expiredTarget.internalId]);const takeover=await claim(ownerB,"2026-07-16T01:00:00.000Z","2026-07-16T01:10:00.000Z",20);assert.equal(takeover.status,"committed");if(takeover.status==="committed"&&takeover.value.status==="claimed")assert.equal(takeover.value.records.some(r=>r.internalId===expiredTarget.internalId),true);}
  assert.equal(manager.dispose(),"disposed");assert.equal(await bridge.close(),"closed");
}));

test("synthetic corruption, commit-unknown and mutation-isolation matrix",async()=>{
  const base=Object.freeze({result_id:"00000000-0000-4000-8000-000000000001",result_digest:new Uint8Array(32).fill(1),tenant_digest:new Uint8Array(32).fill(2),region:"test-region",operation:"generate-music",result_status:"completed",revision:"0",terminal_payload:'{"assets":["safe"]}',expires_at:"2027-01-01T00:00:00.000Z",retention_class:"standard",deletion_state:"active",legal_hold_state:"none"});
  assert.ok(parseFinalResultRow(base));const {result_id:_omitted,...partial}=base;for(const corrupted of [partial,{...base,terminal_payload:'{"assets":'},{...base,operation:"impossible"},{...base,result_digest:new Uint8Array(2)},{...base,deletion_state:"deleted",legal_hold_state:"held"}])assert.equal(parseFinalResultRow(Object.freeze(corrupted)),undefined);
  const classifications:PostgreSQLSliceAUnknownLookupResult["status"][]=["committed","not-committed","corrupted","still-unknown","unavailable"];for(const status of classifications)assert.equal(({status} satisfies PostgreSQLSliceAUnknownLookupResult).status,status);
  const resultFor=(counts:readonly[string,string,string][]|"failure"):DurableWorkflowDatabaseExecutionResult=>counts==="failure"?{status:"failure",failure:"unavailable",retryable:true}:{status:"success",rows:Object.freeze(counts.map(([result_count,reference_count,outbox_count])=>Object.freeze({result_count,reference_count,outbox_count}))),rowCount:counts.length};
  for(const [fixture,expected] of [[[["1","1","1"]],"committed"],[[["0","0","0"]],"not-committed"],[[["1","0","1"]],"corrupted"],[[["1","1","1"],["1","1","1"]],"corrupted"],["failure","unavailable"]] as const){const database:DurableWorkflowDatabaseCapability=Object.freeze({capabilityVersion:"1.0",execute:async()=>resultFor(fixture as readonly[string,string,string][]|"failure")});const atomic=createPostgreSQLSliceAAtomicCommit({finalResults:{} as never,references:{} as never,outbox:{} as never});const value=await atomic.lookup(fakeContext(database),group(1));assert.equal(value.status,expected);}
  const original=POSTGRESQL_SLICE_A_STATEMENT_CATALOG.statements[0]!,copy=[...POSTGRESQL_SLICE_A_STATEMENT_CATALOG.statements];copy.pop();assert.equal(POSTGRESQL_SLICE_A_STATEMENT_CATALOG.statements.length,14);assert.equal(original.parameterCount,12);
});
