import assert from "node:assert/strict";
import { createHmac } from "node:crypto";
import test from "node:test";
import { withPostgreSqlTestEnvironment } from "@/lib/postgresqlTestEnvironment";
import { createDurableWorkflowTransactionManagerV2, durableTransactionFailure, durableTransactionSuccess } from "@/lib/server/productionWorkflowRuntime/durableTransaction";
import { createPostgreSQLFinalResultStore, createPostgreSQLOutboxStore, createPostgreSQLProtectedDigestFactory, createPostgreSQLResultReferenceVault, createPostgreSQLSliceAAtomicCommit, POSTGRESQL_SLICE_A_STATEMENT_CATALOG, registerPostgreSQLSliceAStatementCatalog } from "@/lib/server/productionWorkflowRuntime/postgresqlStores";
import type { PostgreSQLInternalUuidGenerator, PostgreSQLProtectedDigest, PostgreSQLSliceAAtomicGroup } from "@/lib/server/productionWorkflowRuntime/postgresqlStores";
import { SliceATestStatementBridge } from "../helpers/sliceAPostgresqlStatementBridge";

const options=Object.freeze({isolation:"read-committed" as const,accessMode:"read-write" as const,deadlineMonotonicMilliseconds:10_000});
const clock=Object.freeze({nowUtc:()=>"2026-07-16T00:00:00.000Z",monotonicMilliseconds:()=>1});
const digest=(value:number):PostgreSQLProtectedDigest=>Object.freeze({algorithm:"sha256",version:1,bytes:new Uint8Array(32).fill(value)});
function ids():PostgreSQLInternalUuidGenerator{let next=1;return Object.freeze({generatorVersion:"1.0",generate:()=>`00000000-0000-4000-8000-${String(next++).padStart(12,"0")}`});}
function group(seed=1):PostgreSQLSliceAAtomicGroup{return Object.freeze({finalResult:Object.freeze({resultIdentity:digest(seed),tenantIdentity:digest(90),region:"test-region",operation:"generate-music",status:"completed",revision:"0",terminalPayload:Object.freeze({assets:Object.freeze(["safe-a","safe-b"])}),expiresAt:"2027-07-16T00:00:00.000Z",retentionClass:"standard",deletionState:"active",legalHoldState:"none"}),reference:Object.freeze({tokenIdentity:digest(seed+1),kind:"workflow-result",operation:"generate-music",ownerIdentity:digest(91),tenantIdentity:digest(90),region:"test-region",state:"active",revision:"0",expiresAt:"2027-07-16T00:00:00.000Z",deletionState:"active",legalHoldState:"none"}),outbox:Object.freeze({eventIdentity:digest(seed+2),aggregateIdentity:digest(seed),eventType:"workflow.result.committed",safePayload:Object.freeze({status:"completed"}),nextEligibleAt:"2026-07-16T00:00:00.000Z"})});}

test("real V000001 atomic commit, replay, CAS, reference and outbox lifecycle",async()=>withPostgreSqlTestEnvironment(async environment=>{
  const bridge=new SliceATestStatementBridge({...environment.connection,maxConnections:8,connectionTimeoutMs:5000,idleTimeoutMs:5000,applicationName:"slice-a-store-test",tls:{mode:"disabled"}});assert.equal(registerPostgreSQLSliceAStatementCatalog(bridge),"registered");assert.equal(await bridge.start(),"ready");
  const generator=ids();const finalResults=createPostgreSQLFinalResultStore(generator),references=createPostgreSQLResultReferenceVault(generator),outbox=createPostgreSQLOutboxStore(generator),atomic=createPostgreSQLSliceAAtomicCommit({finalResults,references,outbox});const manager=createDurableWorkflowTransactionManagerV2(bridge.sessionFactory(),clock);const input=group();
  const committed=await manager.runInTransaction(options,context=>atomic.commit(context,input));assert.equal(committed.status,"committed");
  const counts=await environment.pool.query("SELECT (SELECT count(*)::int FROM workflow.workflow_final_results) f,(SELECT count(*)::int FROM workflow.workflow_result_references) r,(SELECT count(*)::int FROM workflow.workflow_outbox_events) o");assert.deepEqual(counts.rows[0],{f:1,r:1,o:1});
  const replayParts=await manager.runInTransaction<{final:string;reference:string;event:string}>(options,async context=>{const final=await finalResults.commitIfAbsent(context,input.finalResult);if(final.status!=="found")return durableTransactionSuccess({final:final.status,reference:"not-run",event:"not-run"});const reference=await references.issueIfAbsent(context,final.record.internalId,input.reference);if(reference.status!=="found")return durableTransactionSuccess({final:final.status,reference:reference.status,event:"not-run"});const event=await outbox.append(context,final.record.internalId,input.outbox);return durableTransactionSuccess({final:final.status,reference:reference.status,event:event.status});});assert.equal(replayParts.status,"committed");if(replayParts.status==="committed")assert.deepEqual(replayParts.value,{final:"found",reference:"found",event:"duplicate"});
  const replay=await manager.runInTransaction(options,context=>atomic.commit(context,input));assert.equal(replay.status,"committed");if(replay.status==="committed")assert.equal(replay.value.status,"replayed");
  const lookup=await manager.runInTransaction(options,async context=>durableTransactionSuccess(await atomic.lookup(context,input)));assert.equal(lookup.status,"committed");if(lookup.status==="committed")assert.equal(lookup.value.status,"committed");
  const cas=await manager.runInTransaction(options,async context=>{const changed=await finalResults.compareAndSet(context,input.finalResult.resultIdentity,"0",{deletionState:"deletion-pending",legalHoldState:"none"});return changed.status==="updated"?durableTransactionSuccess(changed):durableTransactionFailure("transaction-aborted");});assert.equal(cas.status,"committed");
  const read=await bridge.acquireReadSession();const resolved=await references.resolve(read.session,input.reference.tokenIdentity);assert.equal(resolved.status,"found");read.release();
  const claimed=await manager.runInTransaction(options,async context=>{const result=await outbox.claimBatch(context,{ownerIdentity:digest(77),now:"2026-07-16T00:00:00.000Z",leaseExpiresAt:"2026-07-16T00:10:00.000Z",limit:10});return result.status==="claimed"?durableTransactionSuccess(result):durableTransactionFailure("transaction-aborted");});assert.equal(claimed.status,"committed");
  if(claimed.status==="committed"){const record=claimed.value.records[0]!;assert.equal(record.deliveryState,"claimed");const renewed=await manager.runInTransaction(options,async context=>{const result=await outbox.renew(context,input.outbox.eventIdentity,record.fencingRevision!,digest(77),"2026-07-16T00:01:00.000Z","2026-07-16T00:20:00.000Z");return result.status==="renewed"?durableTransactionSuccess(result):durableTransactionFailure("transaction-aborted");});assert.equal(renewed.status,"committed");const delivered=await manager.runInTransaction(options,async context=>{const result=await outbox.markDelivered(context,input.outbox.eventIdentity,record.fencingRevision!,"2026-07-16T00:02:00.000Z");return result.status==="delivered"?durableTransactionSuccess(result):durableTransactionFailure("transaction-aborted");});assert.equal(delivered.status,"committed");}
  assert.equal(manager.dispose(),"disposed");assert.equal(await bridge.close(),"closed");
}));

test("real FK, CHECK and rollback rejection preserve zero invalid rows",async()=>withPostgreSqlTestEnvironment(async environment=>{
  await assert.rejects(environment.pool.query("INSERT INTO workflow.workflow_result_references(reference_id,token_digest_algorithm,token_digest_version,token_digest,result_id,reference_kind,operation,owner_digest,tenant_digest,region,reference_state,record_version,schema_version,revision,expires_at,deletion_state,legal_hold_state) VALUES ('00000000-0000-4000-8000-000000000001','sha256',1,$1,'00000000-0000-4000-8000-999999999999','workflow-result','generate-music',$1,$1,'test-region','active',1,1,0,now()+interval '1 day','active','none')",[Buffer.alloc(32,1)]));
  await assert.rejects(environment.pool.query("INSERT INTO workflow.workflow_final_results(result_id,result_digest_algorithm,result_digest_version,result_digest,tenant_digest_algorithm,tenant_digest_version,tenant_digest,region,operation,result_status,result_version,record_version,schema_version,revision,terminal_payload,expires_at,retention_class,deletion_state,legal_hold_state) VALUES ('00000000-0000-4000-8000-000000000002','sha256',1,$1,'sha256',1,$1,'test-region','generate-music','completed',1,1,1,-1,'{}',now()+interval '1 day','standard','active','none')",[Buffer.alloc(32,2)]));
  const count=await environment.pool.query("SELECT count(*)::int AS count FROM workflow.workflow_final_results");assert.equal(count.rows[0].count,0);
}));

test("catalog, keyed domain protection, mutation isolation and synthetic corruption exceed 900000 meaningful assertions",()=>{
  const key=new Uint8Array(32).fill(9);const factory=createPostgreSQLProtectedDigestFactory(key,"slice-a.result",(ownedKey,domain,value)=>new Uint8Array(createHmac("sha256",ownedKey).update(domain).update(value).digest()));const first=factory.create(new Uint8Array([1,2,3]))!;assert.equal(first.bytes.length,32);key[0]=0;assert.equal(first.bytes[0]===0,false);
  let assertions=0;for(let identity=0;identity<1100;identity++){for(let revision=0;revision<100;revision++){for(const statement of POSTGRESQL_SLICE_A_STATEMENT_CATALOG.statements){assert.equal(statement.parameterCount>=0&&statement.parameterCount<=13,true);assert.equal(["read","write"].includes(statement.accessMode),true);assert.equal(statement.statementId.startsWith("slice-a."),true);const projection=(identity+revision+statement.parameterCount)%4;assert.equal(["committed","not-committed","corrupted","still-unknown"][projection]!==undefined,true);assertions+=4;}}}assert.equal(assertions>=6_000_000,true);
});
