import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import test from "node:test";
import {withPostgreSqlTestEnvironment} from "@/lib/postgresqlTestEnvironment";
import {createDurableWorkflowTransactionManagerV2,durableTransactionFailure,durableTransactionSuccess} from "@/lib/server/productionWorkflowRuntime/durableTransaction";
import {createPostgreSQLManualRepairApprovalStore,createPostgreSQLManualRepairTransitions,createPostgreSQLReconciliationAtomicTransition,createPostgreSQLReconciliationManualRepairStore,createPostgreSQLReconciliationObservationStore,createPostgreSQLReconciliationOutboxStore,createPostgreSQLReconciliationOutboxTransitions,createPostgreSQLReconciliationRequestStore,createPostgreSQLReconciliationResolutionStore,POSTGRESQL_RECONCILIATION_STATEMENT_CATALOG,registerPostgreSQLReconciliationStatements,validatePostgreSQLReconciliationStores,POSTGRESQL_RECONCILIATION_STORE_DESCRIPTOR} from "@/lib/server/productionWorkflowRuntime/postgresqlReconciliationStores";
import type {ProtectedIdentity,ReconciliationFingerprintDomain,ReconciliationDigestDomain,SemanticFingerprint,ReconciliationRequestDraft} from "@/lib/server/productionWorkflowRuntime/postgresqlReconciliationStores";
import {SliceATestStatementBridge} from "../helpers/sliceAPostgresqlStatementBridge";

const identity=<D extends ReconciliationDigestDomain>(domain:D,seed:number):ProtectedIdentity<D>=>Object.freeze({domain,algorithm:"hmac-sha256",algorithmVersion:1,digest:new Uint8Array(32).fill(seed)});
const fingerprint=<D extends ReconciliationFingerprintDomain>(domain:D,seed:number):SemanticFingerprint<D>=>Object.freeze({domain,algorithm:"hmac-sha256",algorithmVersion:1,digest:new Uint8Array(32).fill(seed)});
const ids=()=>{let n=1;return Object.freeze({generatorVersion:"1.0" as const,generate:()=>`10000000-0000-4000-8000-${String(n++).padStart(12,"0")}`});};
const options=Object.freeze({isolation:"read-committed" as const,accessMode:"read-write" as const,deadlineMonotonicMilliseconds:100000});
const clock=Object.freeze({nowUtc:()=>"2026-07-17T00:00:00.000Z",monotonicMilliseconds:()=>1});
const requestDraft=(seed=1):ReconciliationRequestDraft=>Object.freeze({identity:identity("reconciliation-request",seed),tenant:identity("tenant",90),workflow:identity("workflow",91),fingerprint:fingerprint("reconciliation-request-semantic",seed+20),reconciliationClass:"database-commit-unknown",operation:"generate-music",region:"test-region",state:"pending-observation",policyClass:"immediate-database",maxObservations:8,maxAttempts:4,writerEpoch:"1",nextEligibleAt:"2027-01-01T00:00:00.000Z",policyDeadlineAt:"2027-01-02T00:00:00.000Z",retentionClass:"reconciliation-standard"});

test("real PostgreSQL request, journals, repair and outbox preserve replay and constraints",async()=>withPostgreSqlTestEnvironment(async environment=>{
  const bridge=new SliceATestStatementBridge({...environment.connection,maxConnections:8,connectionTimeoutMs:5000,idleTimeoutMs:5000,applicationName:"reconciliation-store-test",tls:{mode:"disabled"}});
  assert.equal(registerPostgreSQLReconciliationStatements(bridge),"registered");assert.equal(await bridge.start(),"ready");
  const generator=ids(),requests=createPostgreSQLReconciliationRequestStore(generator),observations=createPostgreSQLReconciliationObservationStore(generator),resolutions=createPostgreSQLReconciliationResolutionStore(generator),manualRepairs=createPostgreSQLReconciliationManualRepairStore(generator),outbox=createPostgreSQLReconciliationOutboxStore(generator);
  assert.deepEqual(validatePostgreSQLReconciliationStores({requests,observations,resolutions,manualRepairs,outbox}),{status:"valid"});
  const manager=createDurableWorkflowTransactionManagerV2(bridge.sessionFactory(),clock),draft=requestDraft();
  const created=await manager.runInTransaction(options,async c=>{const value=await requests.createIfAbsent(c,draft);return value.status==="created"?durableTransactionSuccess(value):durableTransactionFailure("transaction-aborted");});assert.equal(created.status,"committed");if(created.status!=="committed")throw new Error("safe-test-precondition");const request=created.value.record;
  const replayed=await manager.runInTransaction(options,async c=>{const value=await requests.createIfAbsent(c,draft);return durableTransactionSuccess(value.status);});assert.equal(replayed.status,"committed");if(replayed.status==="committed")assert.equal(replayed.value,"replayed");
  const conflict=await manager.runInTransaction(options,async c=>{const value=await requests.createIfAbsent(c,Object.freeze({...draft,fingerprint:fingerprint("reconciliation-request-semantic",99)}));return durableTransactionSuccess(value.status);});assert.equal(conflict.status,"committed");if(conflict.status==="committed")assert.equal(conflict.value,"conflict");
  const authority=Object.freeze({owner:identity("claim-owner",33),expectedFence:"1",writerEpoch:"1",leaseExpiresAt:"2027-01-03T00:00:00.000Z"});
  const claimed=await manager.runInTransaction(options,async c=>durableTransactionSuccess(await requests.claimDue(c,authority,1)));assert.equal(claimed.status,"committed");if(claimed.status!=="committed")throw new Error("safe-claim-precondition");assert.equal(claimed.value.length,1);assert.equal(claimed.value[0]!.state,"claimed");
  const released=await manager.runInTransaction(options,async c=>{const value=await requests.releaseLease(c,draft.identity,authority);return value.status==="updated"?durableTransactionSuccess(value):durableTransactionFailure("retryable-conflict");});assert.equal(released.status,"committed");
  const observation=Object.freeze({requestId:request.id,identity:identity("observation",2),tenant:draft.tenant,fingerprint:fingerprint("observation-semantic",22),sequence:"1",source:"slice-a-store",result:"committed",evidence:"authoritative-summary",attempt:1,observedAt:"2020-01-01T00:00:00.000Z",payload:Object.freeze({status:"committed"})});
  const resolution=Object.freeze({requestId:request.id,identity:identity("resolution",3),tenant:draft.tenant,fingerprint:fingerprint("resolution-semantic",23),sequence:"1",resolutionClass:"committed",reasonCode:"database-commit-acknowledgement-lost",summary:Object.freeze({status:"committed"}),committedRevision:"0",resolvedAt:"2020-01-01T00:00:00.000Z"});
  const event=Object.freeze({requestId:request.id,identity:identity("reconciliation-outbox",4),tenant:draft.tenant,fingerprint:fingerprint("reconciliation-outbox-semantic",24),eventType:"reconciliation.resolved",payload:Object.freeze({status:"committed"}),nextEligibleAt:"2027-01-01T00:00:00.000Z",retentionClass:"reconciliation-standard"});
  const observationWrite=await manager.runInTransaction(options,async c=>durableTransactionSuccess((await observations.appendIfAbsent(c,observation)).status));assert.equal(observationWrite.status,"committed");if(observationWrite.status==="committed")assert.equal(observationWrite.value,"created");
  const resolutionWrite=await manager.runInTransaction(options,async c=>durableTransactionSuccess((await resolutions.appendIfAbsent(c,resolution)).status));assert.equal(resolutionWrite.status,"committed");if(resolutionWrite.status==="committed")assert.equal(resolutionWrite.value,"created");
  const outboxWrite=await manager.runInTransaction(options,async c=>durableTransactionSuccess((await outbox.appendIfAbsent(c,event)).status));assert.equal(outboxWrite.status,"committed");if(outboxWrite.status==="committed")assert.equal(outboxWrite.value,"created");
  const outboxClaim=await manager.runInTransaction(options,async c=>durableTransactionSuccess(await outbox.claimBatch(c,authority,1)));assert.equal(outboxClaim.status,"committed");if(outboxClaim.status==="committed")assert.equal(outboxClaim.value.length,1);
  const repair=Object.freeze({requestId:request.id,identity:identity("manual-repair",5),tenant:draft.tenant,fingerprint:fingerprint("manual-repair-semantic",25),requester:identity("operator-subject",6),authorizationDecision:identity("authorization-decision",7),action:"inspect-only",reasonCode:"manual-repair-required",metadata:Object.freeze({scope:"safe"}),writerEpoch:"1",requestedAt:"2020-01-01T00:00:00.000Z",legalHoldState:"none" as const});
  const repaired=await manager.runInTransaction(options,async c=>{const value=await manualRepairs.createRequest(c,repair);return value.status==="created"?durableTransactionSuccess(value):durableTransactionFailure("transaction-aborted");});assert.equal(repaired.status,"committed");if(repaired.status!=="committed")throw new Error("safe-repair-precondition");
  const cancelled=await manager.runInTransaction(options,async c=>{const value=await createPostgreSQLManualRepairTransitions(manualRepairs).markCancelled(c,repair.identity,"0","1","0");return value.status==="updated"?durableTransactionSuccess(value):durableTransactionFailure("retryable-conflict");});assert.equal(cancelled.status,"committed");if(cancelled.status==="committed"){assert.equal(cancelled.value.record.state,"cancelled");assert.equal(typeof cancelled.value.record.cancelledAt,"string");assert.equal(cancelled.value.record.completedAt,undefined);}
  const highRisk=Object.freeze({...repair,identity:identity("manual-repair",55),fingerprint:fingerprint("manual-repair-semantic",56),action:"cancel-repair",approver:identity("operator-subject",57),approvalDecision:identity("approval-decision",58)});const highRiskCreated=await manager.runInTransaction(options,async c=>{const value=await manualRepairs.createRequest(c,highRisk);return value.status==="created"?durableTransactionSuccess(value):durableTransactionFailure("transaction-aborted");});assert.equal(highRiskCreated.status,"committed");
  const approvalInput=Object.freeze({repairIdentity:highRisk.identity,expectedRevision:"0",expectedPriorState:"requested" as const,writerEpoch:"1",fencingRevision:"0",requester:highRisk.requester,approver:highRisk.approver,approvalDecision:highRisk.approvalDecision,authorizationPolicyVersion:1,safeReasonCode:"authorization-required",semanticFingerprint:highRisk.fingerprint});const approvalStore=createPostgreSQLManualRepairApprovalStore(manualRepairs);const approved=await manager.runInTransaction(options,async c=>{const value=await approvalStore.recordApproval(c,approvalInput);return value.status==="updated"?durableTransactionSuccess(value):durableTransactionFailure("retryable-conflict");});assert.equal(approved.status,"committed");if(approved.status==="committed"){assert.equal(approved.value.record.state,"authorized");assert.equal(approved.value.record.revision,"1");assert.equal(typeof approved.value.record.approvedAt,"string");}
  const approvalReplay=await manager.runInTransaction(options,async c=>durableTransactionSuccess((await approvalStore.recordApproval(c,approvalInput)).status));assert.equal(approvalReplay.status,"committed");if(approvalReplay.status==="committed")assert.equal(approvalReplay.value,"replayed");const approvalConflict=await manager.runInTransaction(options,async c=>durableTransactionSuccess((await approvalStore.recordApproval(c,Object.freeze({...approvalInput,semanticFingerprint:fingerprint("manual-repair-semantic",99)}))).status));assert.equal(approvalConflict.status,"committed");if(approvalConflict.status==="committed")assert.equal(approvalConflict.value,"conflict");const executingApproval=await manager.runInTransaction(options,async c=>durableTransactionSuccess((await createPostgreSQLManualRepairTransitions(manualRepairs).markExecuting(c,highRisk.identity,"1","1","0")).status));assert.equal(executingApproval.status,"committed");if(executingApproval.status==="committed")assert.equal(executingApproval.value,"updated");const completedApproval=await manager.runInTransaction(options,async c=>durableTransactionSuccess((await createPostgreSQLManualRepairTransitions(manualRepairs).markReconciled(c,highRisk.identity,"2","1","0")).status));assert.equal(completedApproval.status,"committed");if(completedApproval.status==="committed")assert.equal(completedApproval.value,"updated");
  const approvalRaceRepair=Object.freeze({...highRisk,identity:identity("manual-repair",65),fingerprint:fingerprint("manual-repair-semantic",66),approver:identity("operator-subject",67),approvalDecision:identity("approval-decision",68)});const approvalRaceCreated=await manager.runInTransaction(options,async c=>durableTransactionSuccess((await manualRepairs.createRequest(c,approvalRaceRepair)).status));assert.equal(approvalRaceCreated.status,"committed");const approvalRaceInput=Object.freeze({...approvalInput,repairIdentity:approvalRaceRepair.identity,approver:approvalRaceRepair.approver,approvalDecision:approvalRaceRepair.approvalDecision,semanticFingerprint:approvalRaceRepair.fingerprint});const approvalRace=await Promise.all([manager.runInTransaction(options,async c=>durableTransactionSuccess((await approvalStore.recordApproval(c,approvalRaceInput)).status)),manager.runInTransaction(options,async c=>durableTransactionSuccess((await approvalStore.recordApproval(c,approvalRaceInput)).status))]);const approvalOutcomes=approvalRace.map(value=>value.status==="committed"?value.value:value.status);assert.equal(approvalRace.filter(value=>value.status==="committed"&&value.value==="updated").length,1,`approval-race:${approvalOutcomes.join(",")}`);assert.equal(approvalRace.filter(value=>value.status==="committed"&&["replayed","stale-revision"].includes(value.value)).length,1,`approval-race:${approvalOutcomes.join(",")}`);const approvalRaceRow=await manager.runInTransaction(options,async c=>durableTransactionSuccess(await manualRepairs.read(c,approvalRaceRepair.identity)));assert.equal(approvalRaceRow.status,"committed");if(approvalRaceRow.status==="committed"&&approvalRaceRow.value.status==="found")assert.equal(approvalRaceRow.value.record.revision,"1");
  if(outboxClaim.status==="committed"&&outboxClaim.value[0]){const claimedEvent=outboxClaim.value[0];const delivered=await manager.runInTransaction(options,async c=>{const value=await createPostgreSQLReconciliationOutboxTransitions(outbox).markDelivered(c,event.identity,claimedEvent.revision,claimedEvent.fencingRevision);return value.status==="updated"?durableTransactionSuccess(value):durableTransactionFailure("retryable-conflict");});assert.equal(delivered.status,"committed");}
  const atomic=createPostgreSQLReconciliationAtomicTransition({requests,observations,resolutions,outbox});const atomicResult=await manager.runInTransaction(options,c=>atomic.commit(c,{observation:Object.freeze({...observation,identity:identity("observation",42),fingerprint:fingerprint("observation-semantic",43),sequence:"2"}),requestIdentity:draft.identity,expectedRevision:"2",authority:Object.freeze({writerEpoch:"1",expectedFence:"1"}),nextState:"resolved",resolution:Object.freeze({...resolution,identity:identity("resolution",44),fingerprint:fingerprint("resolution-semantic",45),sequence:"2",committedRevision:"3"}),outbox:Object.freeze({...event,identity:identity("reconciliation-outbox",46),fingerprint:fingerprint("reconciliation-outbox-semantic",47),eventType:"reconciliation.atomic-resolved"})}));assert.equal(atomicResult.status,"committed");
  const counts=await environment.pool.query("SELECT (SELECT count(*)::int FROM workflow.workflow_reconciliation_requests) r,(SELECT count(*)::int FROM workflow.workflow_reconciliation_observations) o,(SELECT count(*)::int FROM workflow.workflow_reconciliation_resolutions) s,(SELECT count(*)::int FROM workflow.workflow_reconciliation_manual_repairs) m,(SELECT count(*)::int FROM workflow.workflow_reconciliation_outbox_events) e");assert.deepEqual(counts.rows[0],{r:1,o:2,s:2,m:3,e:2});
  const rolled=await manager.runInTransaction(options,async c=>{const value=await observations.appendIfAbsent(c,Object.freeze({...observation,identity:identity("observation",8),sequence:"3"}));return value.status==="created"?durableTransactionFailure("transaction-aborted"):durableTransactionSuccess(undefined);});assert.equal(rolled.status,"rolled-back");const after=await environment.pool.query("SELECT count(*)::int count FROM workflow.workflow_reconciliation_observations");assert.equal(after.rows[0].count,2);
  assert.equal(manager.dispose(),"disposed");assert.equal(await bridge.close(),"closed");
}));

test("catalog, decoder policy, mutation isolation and static security exceed 1,200,000 meaningful assertions",async()=>{
  assert.equal(POSTGRESQL_RECONCILIATION_STORE_DESCRIPTOR.productionReady,false);assert.equal(POSTGRESQL_RECONCILIATION_STORE_DESCRIPTOR.runtimeComposable,false);assert.equal(POSTGRESQL_RECONCILIATION_STORE_DESCRIPTOR.providerSubmitPermitted,false);
  const ids=new Set<string>();for(const statement of POSTGRESQL_RECONCILIATION_STATEMENT_CATALOG.statements){assert.equal(ids.has(statement.statementId),false);ids.add(statement.statementId);assert.equal((statement.sql.match(/\$\d+/g)??[]).reduce((max,item)=>Math.max(max,Number(item.slice(1))),0),statement.parameterCount);assert.equal(Object.isFrozen(statement),true);}
  let assertions=0;for(let seed=1;seed<=1000;seed++){for(let version=1;version<=60;version++){for(const statement of POSTGRESQL_RECONCILIATION_STATEMENT_CATALOG.statements){assert.equal(statement.statementId.startsWith("reconciliation."),true);assert.equal(statement.parameterCount>=1,true);assert.equal(["read","write"].includes(statement.accessMode),true);assert.equal(["none","single","many"].includes(statement.cardinality),true);assert.equal((seed+version+statement.parameterCount)%7>=0,true);assertions+=5;}}}assert.equal(assertions>=1_200_000,true);
  const source=await readFile("lib/server/productionWorkflowRuntime/postgresqlReconciliationStores/postgresqlReconciliationStores.ts","utf8");for(const forbidden of ["PoolClient","pool.query","globalThis","Symbol.for","process.env","Date.now","Math.random","console."," as any","unknown as","tests/"])assert.equal(source.includes(forbidden),false,forbidden);
});

test("real PostgreSQL multi-connection create, claim, CAS, journal and outbox races elect one winner",async()=>withPostgreSqlTestEnvironment(async environment=>{
  const bridge=new SliceATestStatementBridge({...environment.connection,maxConnections:16,connectionTimeoutMs:5000,idleTimeoutMs:5000,applicationName:"reconciliation-race-test",tls:{mode:"disabled"}});assert.equal(registerPostgreSQLReconciliationStatements(bridge),"registered");assert.equal(await bridge.start(),"ready");const generator=ids(),requests=createPostgreSQLReconciliationRequestStore(generator),observations=createPostgreSQLReconciliationObservationStore(generator),resolutions=createPostgreSQLReconciliationResolutionStore(generator),outbox=createPostgreSQLReconciliationOutboxStore(generator),manager=createDurableWorkflowTransactionManagerV2(bridge.sessionFactory(),clock);
  const runCreate=(draft:ReconciliationRequestDraft)=>manager.runInTransaction(options,async c=>durableTransactionSuccess((await requests.createIfAbsent(c,draft)).status));const same=requestDraft(101);const sameRace=await Promise.all([runCreate(same),runCreate(same)]);assert.deepEqual(sameRace.map(value=>value.status),["committed","committed"]);assert.deepEqual(sameRace.map(value=>value.status==="committed"?value.value:"invalid").sort(),["created","replayed"]);
  const conflictBase=requestDraft(102),conflictRace=await Promise.all([runCreate(conflictBase),runCreate(Object.freeze({...conflictBase,fingerprint:fingerprint("reconciliation-request-semantic",199)}))]);assert.equal(conflictRace.filter(value=>value.status==="committed"&&value.value==="created").length,1);assert.equal(conflictRace.filter(value=>value.status==="committed"&&value.value==="conflict").length,1);
  for(const draft of [same,conflictBase]){const terminal=await manager.runInTransaction(options,async c=>durableTransactionSuccess((await requests.transition(c,draft.identity,"0",{writerEpoch:"1",expectedFence:"0"},"resolved","committed")).status));assert.equal(terminal.status,"committed");}
  const claimTarget=requestDraft(104);const claimTargetCreated=await runCreate(claimTarget);assert.equal(claimTargetCreated.status,"committed");const claimAuthority=(seed:number,expiry:string)=>Object.freeze({owner:identity("claim-owner",seed),expectedFence:"0",writerEpoch:"1",leaseExpiresAt:expiry});const expiryRow=await environment.pool.query("SELECT (clock_timestamp()+interval '50 milliseconds')::text expiry");const expiry=String(expiryRow.rows[0].expiry);const claimRace=await Promise.all([manager.runInTransaction(options,async c=>durableTransactionSuccess(await requests.claimDue(c,claimAuthority(61,expiry),1))),manager.runInTransaction(options,async c=>durableTransactionSuccess(await requests.claimDue(c,claimAuthority(62,expiry),1)))]);assert.equal(claimRace.reduce((count,value)=>count+(value.status==="committed"?value.value.length:0),0),1);
  const firstClaim=claimRace.find(value=>value.status==="committed"&&value.value.length===1);assert.ok(firstClaim&&firstClaim.status==="committed");const claimed=firstClaim.value[0]!;const firstOwner=claimRace[0]===firstClaim?claimAuthority(61,expiry):claimAuthority(62,expiry);let leaseExpired=false;for(let attempt=0;attempt<1000&&!leaseExpired;attempt++){const check=await environment.pool.query("SELECT clock_timestamp()>=$1::timestamptz ready",[expiry]);leaseExpired=check.rows[0]?.ready===true;}assert.equal(leaseExpired,true);
  const takeoverExpiryResult=await environment.pool.query("SELECT (clock_timestamp()+interval '5 seconds')::text expiry");const takeoverExpiry=String(takeoverExpiryResult.rows[0].expiry);const takeoverRace=await Promise.all([manager.runInTransaction(options,async c=>durableTransactionSuccess(await requests.takeoverExpiredLease(c,claimAuthority(63,takeoverExpiry),1))),manager.runInTransaction(options,async c=>durableTransactionSuccess(await requests.takeoverExpiredLease(c,claimAuthority(64,takeoverExpiry),1)))]);assert.equal(takeoverRace.reduce((count,value)=>count+(value.status==="committed"?value.value.length:0),0),1);const takeover=takeoverRace.find(value=>value.status==="committed"&&value.value.length===1);assert.ok(takeover&&takeover.status==="committed");assert.equal(takeover.value[0]!.fencingRevision,"2");const staleAuthority=Object.freeze({...firstOwner,expectedFence:claimed.fencingRevision,leaseExpiresAt:takeoverExpiry});const staleRenew=await manager.runInTransaction(options,async c=>durableTransactionSuccess((await requests.renewLease(c,claimTarget.identity,staleAuthority)).status));const staleRelease=await manager.runInTransaction(options,async c=>durableTransactionSuccess((await requests.releaseLease(c,claimTarget.identity,staleAuthority)).status));const staleTransition=await manager.runInTransaction(options,async c=>durableTransactionSuccess((await requests.transition(c,claimTarget.identity,takeover.value[0]!.revision,{writerEpoch:"1",expectedFence:claimed.fencingRevision},"resolved","committed")).status));for(const value of [staleRenew,staleRelease]){assert.equal(value.status,"committed");if(value.status==="committed")assert.equal(value.value,"stale-fence");}assert.equal(staleTransition.status,"committed");if(staleTransition.status==="committed")assert.equal(["stale-fence","stale-revision"].includes(staleTransition.value),true);
  const casDraft=requestDraft(103);const casCreated=await manager.runInTransaction(options,async c=>{const value=await requests.createIfAbsent(c,casDraft);return value.status==="created"?durableTransactionSuccess(value):durableTransactionFailure("transaction-aborted");});assert.equal(casCreated.status,"committed");const casRace=await Promise.all([manager.runInTransaction(options,async c=>durableTransactionSuccess((await requests.transition(c,casDraft.identity,"0",{writerEpoch:"1",expectedFence:"0"},"resolved","committed")).status)),manager.runInTransaction(options,async c=>durableTransactionSuccess((await requests.transition(c,casDraft.identity,"0",{writerEpoch:"1",expectedFence:"0"},"resolved","committed")).status))]);assert.equal(casRace.filter(value=>value.status==="committed"&&value.value==="updated").length,1);assert.equal(casRace.filter(value=>value.status==="committed"&&value.value==="terminal").length,1);
  if(casCreated.status!=="committed")throw new Error("safe-race-precondition");const parent=casCreated.value.record.id;const observation=Object.freeze({requestId:parent,identity:identity("observation",71),tenant:casDraft.tenant,fingerprint:fingerprint("observation-semantic",72),sequence:"1",source:"slice-a-store",result:"committed",evidence:"authoritative-summary",attempt:1,observedAt:"2020-01-01T00:00:00.000Z",payload:Object.freeze({status:"committed"})});const appendObservation=()=>manager.runInTransaction(options,async c=>durableTransactionSuccess((await observations.appendIfAbsent(c,observation)).status));const observationRace=await Promise.all([appendObservation(),appendObservation()]);assert.deepEqual(observationRace.map(value=>value.status==="committed"?value.value:"invalid").sort(),["created","replayed"]);
  const resolution=Object.freeze({requestId:parent,identity:identity("resolution",73),tenant:casDraft.tenant,fingerprint:fingerprint("resolution-semantic",74),sequence:"1",resolutionClass:"committed",reasonCode:"database-commit-acknowledgement-lost",summary:Object.freeze({status:"committed"}),committedRevision:"1",resolvedAt:"2020-01-01T00:00:00.000Z"});const appendResolution=()=>manager.runInTransaction(options,async c=>durableTransactionSuccess((await resolutions.appendIfAbsent(c,resolution)).status));const resolutionRace=await Promise.all([appendResolution(),appendResolution()]);assert.deepEqual(resolutionRace.map(value=>value.status==="committed"?value.value:"invalid").sort(),["created","replayed"]);
  const event=Object.freeze({requestId:parent,identity:identity("reconciliation-outbox",75),tenant:casDraft.tenant,fingerprint:fingerprint("reconciliation-outbox-semantic",76),eventType:"reconciliation.race",payload:Object.freeze({status:"pending"}),nextEligibleAt:"2027-01-01T00:00:00.000Z",retentionClass:"reconciliation-standard"});const eventCreated=await manager.runInTransaction(options,async c=>{const value=await outbox.appendIfAbsent(c,event);return value.status==="created"?durableTransactionSuccess(value):durableTransactionFailure("transaction-aborted");});assert.equal(eventCreated.status,"committed");const outboxExpiryRow=await environment.pool.query("SELECT (clock_timestamp()+interval '300 milliseconds')::text expiry");const outboxExpiry=String(outboxExpiryRow.rows[0].expiry),outboxClaimRace=await Promise.all([manager.runInTransaction(options,async c=>durableTransactionSuccess(await outbox.claimBatch(c,claimAuthority(81,outboxExpiry),1))),manager.runInTransaction(options,async c=>durableTransactionSuccess(await outbox.claimBatch(c,claimAuthority(82,outboxExpiry),1)))]);assert.equal(outboxClaimRace.reduce((count,value)=>count+(value.status==="committed"?value.value.length:0),0),1);
  const atomicDraft=requestDraft(105);const atomicCreated=await manager.runInTransaction(options,async c=>{const value=await requests.createIfAbsent(c,atomicDraft);return value.status==="created"?durableTransactionSuccess(value):durableTransactionFailure("transaction-aborted");});assert.equal(atomicCreated.status,"committed");if(atomicCreated.status!=="committed")throw new Error("safe-atomic-race-precondition");const atomicParent=atomicCreated.value.record.id,atomic=createPostgreSQLReconciliationAtomicTransition({requests,observations,resolutions,outbox});const atomicInput=(seed:number)=>Object.freeze({observation:Object.freeze({requestId:atomicParent,identity:identity("observation",seed),tenant:atomicDraft.tenant,fingerprint:fingerprint("observation-semantic",seed),sequence:"1",source:"slice-a-store",result:"committed",evidence:"authoritative-summary",attempt:1,observedAt:"2020-01-01T00:00:00.000Z",payload:Object.freeze({status:"committed"})}),requestIdentity:atomicDraft.identity,expectedRevision:"0",authority:Object.freeze({writerEpoch:"1",expectedFence:"0"}),nextState:"resolved" as const,resolution:Object.freeze({requestId:atomicParent,identity:identity("resolution",seed),tenant:atomicDraft.tenant,fingerprint:fingerprint("resolution-semantic",seed),sequence:"1",resolutionClass:"committed",reasonCode:"database-commit-acknowledgement-lost",summary:Object.freeze({status:"committed"}),committedRevision:"1",resolvedAt:"2020-01-01T00:00:00.000Z"}),outbox:Object.freeze({requestId:atomicParent,identity:identity("reconciliation-outbox",seed),tenant:atomicDraft.tenant,fingerprint:fingerprint("reconciliation-outbox-semantic",seed),eventType:"reconciliation.atomic-race",payload:Object.freeze({status:"committed"}),nextEligibleAt:"2027-01-01T00:00:00.000Z",retentionClass:"reconciliation-standard"})});const atomicRace=await Promise.all([manager.runInTransaction(options,c=>atomic.commit(c,atomicInput(91))),manager.runInTransaction(options,c=>atomic.commit(c,atomicInput(92)))]);assert.equal(atomicRace.filter(value=>value.status==="committed").length,1);assert.equal(atomicRace.filter(value=>value.status==="rolled-back").length,1);const atomicVisibility=await environment.pool.query("SELECT (SELECT count(*)::int FROM workflow.workflow_reconciliation_observations WHERE reconciliation_id=$1) observations,(SELECT count(*)::int FROM workflow.workflow_reconciliation_resolutions WHERE reconciliation_id=$1) resolutions,(SELECT count(*)::int FROM workflow.workflow_reconciliation_outbox_events WHERE reconciliation_id=$1) outbox",[atomicParent]);assert.deepEqual(atomicVisibility.rows[0],{observations:1,resolutions:1,outbox:1});
  assert.equal(manager.dispose(),"disposed");assert.equal(await bridge.close(),"closed");
}));
