import assert from "node:assert/strict";
import test from "node:test";
import { withPostgreSqlTestEnvironment } from "@/lib/postgresqlTestEnvironment";
import { createDurableWorkflowTransactionManagerV2, durableTransactionSuccess } from "@/lib/server/productionWorkflowRuntime/durableTransaction";
import { createPostgreSQLReconciliationAtomicExecutorV2, createPostgreSQLReconciliationObservationStore, createPostgreSQLReconciliationOutboxStore, createPostgreSQLReconciliationRequestStore, createPostgreSQLReconciliationRequestStoreV2, createPostgreSQLReconciliationResolutionStore, createPostgreSQLReconciliationResolutionStoreV2, POSTGRESQL_RECONCILIATION_ATOMIC_EXECUTOR_V2_DESCRIPTOR, registerPostgreSQLReconciliationStatements, validatePostgreSQLReconciliationAtomicExecutorV2 } from "@/lib/server/productionWorkflowRuntime/postgresqlReconciliationStores";
import type { ProtectedIdentity, ReconciliationAtomicInputV2, ReconciliationDigestDomain, ReconciliationFingerprintDomain, ReconciliationRequestDraft, SemanticFingerprint } from "@/lib/server/productionWorkflowRuntime/postgresqlReconciliationStores";
import { SliceATestStatementBridge } from "../helpers/sliceAPostgresqlStatementBridge";

const identity = <D extends ReconciliationDigestDomain>(domain: D, seed: number): ProtectedIdentity<D> => Object.freeze({ domain, algorithm: "hmac-sha256", algorithmVersion: 1, digest: new Uint8Array(32).fill(seed) });
const fingerprint = <D extends ReconciliationFingerprintDomain>(domain: D, seed: number): SemanticFingerprint<D> => Object.freeze({ domain, algorithm: "hmac-sha256", algorithmVersion: 1, digest: new Uint8Array(32).fill(seed) });
const ids = () => { let value = 1; return Object.freeze({ generatorVersion: "1.0" as const, generate: () => `30000000-0000-4000-8000-${String(value++).padStart(12, "0")}` }); };
const options = Object.freeze({ isolation: "read-committed" as const, accessMode: "read-write" as const, deadlineMonotonicMilliseconds: 100000 });
const clock = Object.freeze({ nowUtc: () => "2026-07-17T00:00:00.000Z", monotonicMilliseconds: () => 1 });
const requestDraft = (seed: number): ReconciliationRequestDraft => Object.freeze({ identity: identity("reconciliation-request", seed), tenant: identity("tenant", 2), workflow: identity("workflow", 3), fingerprint: fingerprint("reconciliation-request-semantic", seed), reconciliationClass: "database-commit-unknown", operation: "generate-music", region: "test-region", state: "pending-observation", policyClass: "immediate-database", maxObservations: 8, maxAttempts: 4, writerEpoch: "1", nextEligibleAt: "2027-01-01T00:00:00.000Z", policyDeadlineAt: "2027-01-02T00:00:00.000Z", retentionClass: "reconciliation-standard" });

test("Atomic Executor V2 preserves authority conflict classes after full rollback", async () => withPostgreSqlTestEnvironment(async environment => {
  const bridge = new SliceATestStatementBridge({ ...environment.connection, maxConnections: 8, connectionTimeoutMs: 5000, idleTimeoutMs: 5000, applicationName: "reconciliation-atomic-v2", tls: { mode: "disabled" } });
  assert.equal(registerPostgreSQLReconciliationStatements(bridge), "registered"); assert.equal(await bridge.start(), "ready");
  const generator = ids(); const requests = createPostgreSQLReconciliationRequestStoreV2(createPostgreSQLReconciliationRequestStore(generator)); const observations = createPostgreSQLReconciliationObservationStore(generator); const resolutions = createPostgreSQLReconciliationResolutionStoreV2(createPostgreSQLReconciliationResolutionStore(generator),generator); const outbox = createPostgreSQLReconciliationOutboxStore(generator); const manager = createDurableWorkflowTransactionManagerV2(bridge.sessionFactory(), clock);
  try {
    const executor = createPostgreSQLReconciliationAtomicExecutorV2(manager, options, { requests, observations, resolutions, outbox });
    assert.equal(executor.executorVersion, "2.1"); assert.deepEqual(executor.descriptor, POSTGRESQL_RECONCILIATION_ATOMIC_EXECUTOR_V2_DESCRIPTOR); assert.deepEqual(validatePostgreSQLReconciliationAtomicExecutorV2(executor), { status: "valid" }); assert.equal(executor.descriptor.productionReady, false); assert.equal(executor.descriptor.runtimeComposable, false);
    for (const fixture of [{ seed: 11, authority: { writerEpoch: "1", expectedFence: "1", owner: identity("claim-owner", 91) }, expected: "stale-fence" as const }, { seed: 21, authority: { writerEpoch: "2", expectedFence: "0", owner: identity("claim-owner", 92) }, expected: "writer-epoch-mismatch" as const }]) {
      const draft = requestDraft(fixture.seed); const created = await manager.runInTransaction(options, async context => durableTransactionSuccess(await requests.createIfAbsent(context, draft))); assert.equal(created.status, "committed"); if (created.status !== "committed" || created.value.status !== "created") throw new Error("safe-atomic-v2-precondition"); const parent = created.value.record.id;
      const input: ReconciliationAtomicInputV2 = { observation: Object.freeze({ requestId: parent, identity: identity("observation", fixture.seed), tenant: draft.tenant, fingerprint: fingerprint("observation-semantic", fixture.seed), sequence: "1", source: "slice-a-store", result: "committed", evidence: "authoritative-summary", attempt: 1, observedAt: "2020-01-01T00:00:00.000Z", payload: Object.freeze({ status: "committed" }) }), requestIdentity: draft.identity, expectedRevision: "0", expectedPriorStates: ["pending-observation"], authority: Object.freeze(fixture.authority), nextState: "resolved", resolution: Object.freeze({ requestId: parent, identity: identity("resolution", fixture.seed), tenant: draft.tenant, fingerprint: fingerprint("resolution-semantic", fixture.seed), sequence: "1", resolutionClass: "committed", reasonCode: "database-commit-acknowledgement-lost", summary: Object.freeze({ status: "committed" }), committedRevision: "1", resolvedAt: "2020-01-01T00:00:00.000Z" }), outbox: Object.freeze({ requestId: parent, identity: identity("reconciliation-outbox", fixture.seed), tenant: draft.tenant, fingerprint: fingerprint("reconciliation-outbox-semantic", fixture.seed), eventType: "reconciliation.atomic-v2", payload: Object.freeze({ status: "committed" }), nextEligibleAt: "2027-01-01T00:00:00.000Z", retentionClass: "reconciliation-standard" }) };
      const result = await executor.execute(input); assert.deepEqual(result, { status: "conflict", conflictClass: fixture.expected });
      const visibility = await environment.pool.query("SELECT r.revision::text revision,r.state,(SELECT count(*)::int FROM workflow.workflow_reconciliation_observations o WHERE o.reconciliation_id=r.reconciliation_id) observations,(SELECT count(*)::int FROM workflow.workflow_reconciliation_resolutions s WHERE s.reconciliation_id=r.reconciliation_id) resolutions,(SELECT count(*)::int FROM workflow.workflow_reconciliation_outbox_events e WHERE e.reconciliation_id=r.reconciliation_id) outbox FROM workflow.workflow_reconciliation_requests r WHERE r.reconciliation_id=$1", [parent]); assert.deepEqual(visibility.rows[0], { revision: "0", state: "pending-observation", observations: 0, resolutions: 0, outbox: 0 });
    }
  } finally { assert.equal(manager.dispose(), "disposed"); assert.equal(await bridge.close(), "closed"); }
}));
