import assert from "node:assert/strict";
import test from "node:test";
import { withPostgreSqlTestEnvironment } from "@/lib/postgresqlTestEnvironment";
import { createDurableWorkflowTransactionManagerV2, durableTransactionSuccess } from "@/lib/server/productionWorkflowRuntime/durableTransaction";
import { createPostgreSQLReconciliationOutboxStore, createPostgreSQLReconciliationOutboxStoreV2, createPostgreSQLReconciliationRequestStore, createPostgreSQLReconciliationRequestStoreV2, createPostgreSQLReconciliationResolutionStore, createPostgreSQLReconciliationResolutionStoreV2, getPostgreSQLReconciliationCapabilityDescriptor, listPostgreSQLReconciliationCapabilityDescriptors, registerPostgreSQLReconciliationStatements, validatePostgreSQLReconciliationOutboxStoreV2, validatePostgreSQLReconciliationResolutionStoreV2 } from "@/lib/server/productionWorkflowRuntime/postgresqlReconciliationStores";
import type { ProtectedIdentity, ReconciliationDigestDomain, ReconciliationFingerprintDomain, ReconciliationRequestDraft, SemanticFingerprint } from "@/lib/server/productionWorkflowRuntime/postgresqlReconciliationStores";
import { SliceATestStatementBridge } from "../helpers/sliceAPostgresqlStatementBridge";

const identity=<D extends ReconciliationDigestDomain>(domain:D,seed:number):ProtectedIdentity<D>=>Object.freeze({domain,algorithm:"hmac-sha256",algorithmVersion:1,digest:new Uint8Array(32).fill(seed)});
const fingerprint=<D extends ReconciliationFingerprintDomain>(domain:D,seed:number):SemanticFingerprint<D>=>Object.freeze({domain,algorithm:"hmac-sha256",algorithmVersion:1,digest:new Uint8Array(32).fill(seed)});
const ids=()=>{let value=500;return Object.freeze({generatorVersion:"1.0" as const,generate:()=>`50000000-0000-4000-8000-${String(value++).padStart(12,"0")}`});};
const options=Object.freeze({isolation:"read-committed" as const,accessMode:"read-write" as const,deadlineMonotonicMilliseconds:100000});
const clock=Object.freeze({nowUtc:()=>"2026-07-17T00:00:00.000Z",monotonicMilliseconds:()=>1});
const requestDraft=(seed:number):ReconciliationRequestDraft=>Object.freeze({identity:identity("reconciliation-request",seed),tenant:identity("tenant",2),workflow:identity("workflow",3),fingerprint:fingerprint("reconciliation-request-semantic",seed),reconciliationClass:"database-commit-unknown",operation:"generate-music",region:"test-region",state:"pending-observation",policyClass:"immediate-database",maxObservations:8,maxAttempts:4,writerEpoch:"1",nextEligibleAt:"2027-01-01T00:00:00.000Z",policyDeadlineAt:"2027-01-02T00:00:00.000Z",retentionClass:"reconciliation-standard"});

test("V2 Resolution parent guard and Outbox owner guard reject late and stale writes",async()=>withPostgreSqlTestEnvironment(async environment=>{
  const bridge=new SliceATestStatementBridge({...environment.connection,maxConnections:8,connectionTimeoutMs:5000,idleTimeoutMs:5000,applicationName:"reconciliation-capability-v2",tls:{mode:"disabled"}});assert.equal(registerPostgreSQLReconciliationStatements(bridge),"registered");assert.equal(await bridge.start(),"ready");
  const generator=ids(),requestV1=createPostgreSQLReconciliationRequestStore(generator),requests=createPostgreSQLReconciliationRequestStoreV2(requestV1),resolutions=createPostgreSQLReconciliationResolutionStoreV2(createPostgreSQLReconciliationResolutionStore(generator),generator),outboxV1=createPostgreSQLReconciliationOutboxStore(generator),outbox=createPostgreSQLReconciliationOutboxStoreV2(),manager=createDurableWorkflowTransactionManagerV2(bridge.sessionFactory(),clock);
  try{
    assert.deepEqual(validatePostgreSQLReconciliationResolutionStoreV2(resolutions),{status:"valid"});assert.deepEqual(validatePostgreSQLReconciliationOutboxStoreV2(outbox),{status:"valid"});
    const draft=requestDraft(111),created=await manager.runInTransaction(options,async c=>durableTransactionSuccess(await requestV1.createIfAbsent(c,draft)));assert.equal(created.status,"committed");if(created.status!=="committed"||created.value.status!=="created")throw new Error("safe-v2-setup");
    const owner=identity("claim-owner",31),expiry=String((await environment.pool.query("SELECT (transaction_timestamp()+interval '1 hour')::text expiry")).rows[0].expiry),claimed=await manager.runInTransaction(options,async c=>durableTransactionSuccess(await requestV1.claimDue(c,{owner,expectedFence:"0",writerEpoch:"1",leaseExpiresAt:expiry},1)));assert.equal(claimed.status,"committed");if(claimed.status!=="committed"||claimed.value.length!==1)throw new Error("safe-v2-claim");const parent=claimed.value[0]!;
    const resolutionDraft=Object.freeze({requestId:parent.id,identity:identity("resolution",41),tenant:draft.tenant,fingerprint:fingerprint("resolution-semantic",41),sequence:"1",resolutionClass:"committed",reasonCode:"database-commit-acknowledgement-lost",summary:Object.freeze({status:"committed"}),committedRevision:String(Number(parent.revision)+1),resolvedAt:"2020-01-01T00:00:00.000Z"});
    const resolutionInput=Object.freeze({draft:resolutionDraft,requestIdentity:draft.identity,expectedRequestRevision:parent.revision,expectedPriorStates:["claimed"] as const,authority:Object.freeze({writerEpoch:"1",expectedFence:parent.fencingRevision,owner})});
    const appended=await manager.runInTransaction(options,async c=>durableTransactionSuccess(await resolutions.appendStandaloneV2(c,resolutionInput)));assert.equal(appended.status,"committed");if(appended.status==="committed")assert.deepEqual(appended.value,{status:"created"});
    const replayed=await manager.runInTransaction(options,async c=>durableTransactionSuccess(await resolutions.appendStandaloneV2(c,resolutionInput)));assert.equal(replayed.status,"committed");if(replayed.status==="committed")assert.deepEqual(replayed.value,{status:"replayed"});
    const terminal=await manager.runInTransaction(options,async c=>durableTransactionSuccess(await requests.transitionV2(c,{identity:draft.identity,expectedRevision:parent.revision,expectedPriorStates:["claimed"],authority:{writerEpoch:"1",expectedFence:parent.fencingRevision,owner},nextState:"resolved",resolutionClass:"committed"})));assert.equal(terminal.status,"committed");
    const lateInput=Object.freeze({...resolutionInput,draft:Object.freeze({...resolutionDraft,identity:identity("resolution",42),fingerprint:fingerprint("resolution-semantic",42),sequence:"2"})});const late=await manager.runInTransaction(options,async c=>durableTransactionSuccess(await resolutions.appendStandaloneV2(c,lateInput)));assert.equal(late.status,"committed");if(late.status==="committed")assert.deepEqual(late.value,{status:"conflict",conflictClass:"terminal-preserved"});
    const event=Object.freeze({requestId:parent.id,identity:identity("reconciliation-outbox",51),tenant:draft.tenant,fingerprint:fingerprint("reconciliation-outbox-semantic",51),eventType:"reconciliation.v2",payload:Object.freeze({status:"pending"}),nextEligibleAt:"2027-01-01T00:00:00.000Z",retentionClass:"reconciliation-standard"});const eventCreated=await manager.runInTransaction(options,async c=>durableTransactionSuccess(await outboxV1.appendIfAbsent(c,event)));assert.equal(eventCreated.status,"committed");const eventOwner=identity("claim-owner",52),eventClaim=await manager.runInTransaction(options,async c=>durableTransactionSuccess(await outboxV1.claimBatch(c,{owner:eventOwner,expectedFence:"0",writerEpoch:"1",leaseExpiresAt:expiry},1)));assert.equal(eventClaim.status,"committed");if(eventClaim.status!=="committed"||eventClaim.value.length!==1)throw new Error("safe-v2-event-claim");const claimedEvent=eventClaim.value[0]!,guard=Object.freeze({identity:event.identity,expectedFingerprint:event.fingerprint,expectedRevision:claimedEvent.revision,expectedSourceState:"claimed" as const,expectedOwner:eventOwner,expectedFence:claimedEvent.fencingRevision});
    const stale=await manager.runInTransaction(options,async c=>durableTransactionSuccess(await outbox.transitionV2(c,{...guard,expectedOwner:identity("claim-owner",53),targetState:"delivered"})));assert.equal(stale.status,"committed");if(stale.status==="committed")assert.deepEqual(stale.value,{status:"conflict",conflictClass:"stale-fence",providerSubmitPermitted:false});
    const delivered=await manager.runInTransaction(options,async c=>durableTransactionSuccess(await outbox.transitionV2(c,{...guard,targetState:"delivered"})));assert.equal(delivered.status,"committed");if(delivered.status==="committed")assert.deepEqual(delivered.value,{status:"updated",outcome:"delivered",providerSubmitPermitted:false});
    const overwrite=await manager.runInTransaction(options,async c=>durableTransactionSuccess(await outbox.transitionV2(c,{...guard,targetState:"reconciliation-required",safeFailureClass:"delivery-unknown"})));assert.equal(overwrite.status,"committed");if(overwrite.status==="committed")assert.deepEqual(overwrite.value,{status:"conflict",conflictClass:"terminal-preserved",providerSubmitPermitted:false});
    assert.equal((await environment.pool.query("SELECT count(*)::int count FROM workflow.workflow_reconciliation_resolutions WHERE reconciliation_id=$1",[parent.id])).rows[0].count,1);
  }finally{assert.equal(manager.dispose(),"disposed");assert.equal(await bridge.close(),"closed");}
}));

test("V1 and V2 capability descriptors are isolated immutable projections",()=>{const descriptors=listPostgreSQLReconciliationCapabilityDescriptors();assert.equal(descriptors.length,4);for(const descriptor of descriptors)assert.equal(Object.isFrozen(descriptor),true);assert.equal(getPostgreSQLReconciliationCapabilityDescriptor("reconciliation-resolution-v1")?.parentPreconditionGuard,false);assert.equal(getPostgreSQLReconciliationCapabilityDescriptor("reconciliation-resolution-v2")?.parentPreconditionGuard,true);assert.equal(getPostgreSQLReconciliationCapabilityDescriptor("reconciliation-outbox-transition-v1")?.ownerGuard,false);assert.equal(getPostgreSQLReconciliationCapabilityDescriptor("reconciliation-outbox-transition-v2")?.ownerGuard,true);assert.equal(getPostgreSQLReconciliationCapabilityDescriptor("unknown"),undefined);});
