import assert from "node:assert/strict";
import test from "node:test";
import { withPostgreSqlTestEnvironment } from "@/lib/postgresqlTestEnvironment";
import { createDurableWorkflowTransactionManagerV2, durableTransactionSuccess } from "@/lib/server/productionWorkflowRuntime/durableTransaction";
import { createPostgreSQLReconciliationOutboxStore, createPostgreSQLReconciliationOutboxStoreV2, createPostgreSQLReconciliationRequestStore, registerPostgreSQLReconciliationStatements } from "@/lib/server/productionWorkflowRuntime/postgresqlReconciliationStores";
import type { ProtectedIdentity, ReconciliationDigestDomain, ReconciliationFingerprintDomain, ReconciliationOutboxDraft, ReconciliationOutboxRecord, ReconciliationRequestDraft, SemanticFingerprint } from "@/lib/server/productionWorkflowRuntime/postgresqlReconciliationStores";
import { SliceATestStatementBridge } from "../helpers/sliceAPostgresqlStatementBridge";

const identity=<D extends ReconciliationDigestDomain>(domain:D,seed:number):ProtectedIdentity<D>=>Object.freeze({domain,algorithm:"hmac-sha256",algorithmVersion:1,digest:new Uint8Array(32).fill(seed)});
const fingerprint=<D extends ReconciliationFingerprintDomain>(domain:D,seed:number):SemanticFingerprint<D>=>Object.freeze({domain,algorithm:"hmac-sha256",algorithmVersion:1,digest:new Uint8Array(32).fill(seed)});
const ids=()=>{let value=700;return Object.freeze({generatorVersion:"1.0" as const,generate:()=>`70000000-0000-4000-8000-${String(value++).padStart(12,"0")}`});};
const options=Object.freeze({isolation:"read-committed" as const,accessMode:"read-write" as const,deadlineMonotonicMilliseconds:100000});
const clock=Object.freeze({nowUtc:()=>"2026-07-17T00:00:00.000Z",monotonicMilliseconds:()=>1});
const sameIdentity=(left:ProtectedIdentity<"reconciliation-outbox">,right:ProtectedIdentity<"reconciliation-outbox">)=>left.domain===right.domain&&left.algorithm===right.algorithm&&left.algorithmVersion===right.algorithmVersion&&left.digest.length===right.digest.length&&left.digest.every((value,index)=>value===right.digest[index]);

for(const operation of ["renew","release","reconciliation-required"] as const)test(`Fixture Group 1 verifies ${operation} success in an isolated database`,async()=>withPostgreSqlTestEnvironment(async environment=>{
  const bridge=new SliceATestStatementBridge({...environment.connection,maxConnections:8,connectionTimeoutMs:5000,idleTimeoutMs:5000,applicationName:`reconciliation-outbox-v2-${operation}`,tls:{mode:"disabled"}});assert.equal(registerPostgreSQLReconciliationStatements(bridge),"registered");assert.equal(await bridge.start(),"ready");
  const seed=operation==="renew"?41:operation==="release"?51:61,generator=ids(),requests=createPostgreSQLReconciliationRequestStore(generator),v1=createPostgreSQLReconciliationOutboxStore(generator),v2=createPostgreSQLReconciliationOutboxStoreV2(),manager=createDurableWorkflowTransactionManagerV2(bridge.sessionFactory(),clock),tenant=identity("tenant",seed),workflow=identity("workflow",seed+1),owner=identity("claim-owner",seed+2);
  const run=<T>(action:(context:Parameters<typeof v2.transitionV2>[0])=>Promise<T>)=>manager.runInTransaction(options,async context=>durableTransactionSuccess(await action(context)));
  try{
    const request:ReconciliationRequestDraft=Object.freeze({identity:identity("reconciliation-request",seed+3),tenant,workflow,fingerprint:fingerprint("reconciliation-request-semantic",seed+3),reconciliationClass:"database-commit-unknown",operation:"generate-music",region:"test-region",state:"pending-observation",policyClass:"immediate-database",maxObservations:8,maxAttempts:4,writerEpoch:"1",nextEligibleAt:"2027-01-01T00:00:00.000Z",policyDeadlineAt:"2027-01-02T00:00:00.000Z",retentionClass:"reconciliation-standard"});const parent=await run(c=>requests.createIfAbsent(c,request));if(parent.status!=="committed"||parent.value.status!=="created")throw new Error("safe-group1-success-parent");
    const draft:ReconciliationOutboxDraft=Object.freeze({requestId:parent.value.record.id,identity:identity("reconciliation-outbox",seed+4),tenant,fingerprint:fingerprint("reconciliation-outbox-semantic",seed+4),eventType:"reconciliation.lifecycle-v2",payload:Object.freeze({marker:seed,status:"pending"}),nextEligibleAt:"2027-01-01T00:00:00.000Z",retentionClass:"reconciliation-standard"});const created=await run(c=>v1.appendIfAbsent(c,draft));assert.equal(created.status,"committed");
    const leaseExpiresAt=String((await environment.pool.query("SELECT (transaction_timestamp()+interval '1 hour')::text value")).rows[0].value),later=String((await environment.pool.query("SELECT (transaction_timestamp()+interval '2 hours')::text value")).rows[0].value);const claim=await run(c=>v1.claimBatch(c,{owner,expectedFence:"0",writerEpoch:"1",leaseExpiresAt},1));assert.equal(claim.status,"committed","safe-success-claim-status");if(claim.status!=="committed")throw new Error("safe-success-claim-unavailable");assert.equal(claim.value.length,1,"safe-success-claim-count");const claimed=claim.value[0];if(!claimed)throw new Error("safe-success-claim-missing");assert.equal(sameIdentity(claimed.identity,draft.identity),true,"safe-success-fixture-isolation");
    const guard=Object.freeze({identity:draft.identity,expectedFingerprint:draft.fingerprint,expectedRevision:claimed.revision,expectedSourceState:"claimed" as const,expectedOwner:claimed.claimOwner!,expectedFence:claimed.fencingRevision});
    if(operation==="renew"){const result=await run(c=>v2.renewLeaseV2(c,{...guard,leaseExpiresAt:later}));assert.equal(result.status,"committed");if(result.status==="committed")assert.deepEqual(result.value,{status:"updated",outcome:"renewed",providerSubmitPermitted:false});const row=(await environment.pool.query("SELECT revision::text,fencing_revision::text,lease_expires_at IS NOT NULL lease FROM workflow.workflow_reconciliation_outbox_events WHERE event_id=$1",[claimed.id])).rows[0];assert.equal(row.revision,String(Number(claimed.revision)+1));assert.equal(row.fencing_revision,claimed.fencingRevision);assert.equal(row.lease,true);}
    if(operation==="release"){const result=await run(c=>v2.releaseLeaseV2(c,guard));assert.equal(result.status,"committed");if(result.status==="committed")assert.deepEqual(result.value,{status:"updated",outcome:"released",providerSubmitPermitted:false});const row=(await environment.pool.query("SELECT delivery_state,claim_owner_digest IS NULL owner_clear,lease_expires_at IS NULL lease_clear FROM workflow.workflow_reconciliation_outbox_events WHERE event_id=$1",[claimed.id])).rows[0];assert.deepEqual({state:row.delivery_state,owner:row.owner_clear,lease:row.lease_clear},{state:"pending",owner:true,lease:true});}
    if(operation==="reconciliation-required"){const result=await run(c=>v2.transitionV2(c,{...guard,targetState:"reconciliation-required",safeFailureClass:"delivery-unknown"}));assert.equal(result.status,"committed");if(result.status==="committed")assert.deepEqual(result.value,{status:"updated",outcome:"reconciliation-required",providerSubmitPermitted:false});const row=(await environment.pool.query("SELECT delivery_state,delivered_at IS NULL no_delivery,lease_expires_at IS NULL no_lease FROM workflow.workflow_reconciliation_outbox_events WHERE event_id=$1",[claimed.id])).rows[0];assert.deepEqual({state:row.delivery_state,noDelivery:row.no_delivery,noLease:row.no_lease},{state:"reconciliation-required",noDelivery:true,noLease:true});const terminal=await run(c=>v2.transitionV2(c,{...guard,targetState:"delivered"}));assert.equal(terminal.status,"committed");if(terminal.status==="committed")assert.deepEqual(terminal.value,{status:"conflict",conflictClass:"terminal-preserved",providerSubmitPermitted:false});}
  }finally{assert.equal(manager.dispose(),"disposed");assert.equal(await bridge.close(),"closed");}
}));

test("Fixture Group 1 directly verifies Outbox V2 lifecycle and safe classification",async()=>withPostgreSqlTestEnvironment(async environment=>{
  const bridge=new SliceATestStatementBridge({...environment.connection,maxConnections:8,connectionTimeoutMs:5000,idleTimeoutMs:5000,applicationName:"reconciliation-outbox-v2-lifecycle",tls:{mode:"disabled"}});assert.equal(registerPostgreSQLReconciliationStatements(bridge),"registered");assert.equal(await bridge.start(),"ready");
  const generator=ids(),requests=createPostgreSQLReconciliationRequestStore(generator),v1=createPostgreSQLReconciliationOutboxStore(generator),v2=createPostgreSQLReconciliationOutboxStoreV2(),manager=createDurableWorkflowTransactionManagerV2(bridge.sessionFactory(),clock),tenant=identity("tenant",2),workflow=identity("workflow",3),owner=identity("claim-owner",10),wrongOwner=identity("claim-owner",11);type C=Parameters<typeof v2.transitionV2>[0];
  const run=<T>(operation:(context:Parameters<typeof v2.transitionV2>[0])=>Promise<T>)=>manager.runInTransaction(options,async context=>durableTransactionSuccess(await operation(context)));
  try{
    const request:ReconciliationRequestDraft=Object.freeze({identity:identity("reconciliation-request",1),tenant,workflow,fingerprint:fingerprint("reconciliation-request-semantic",1),reconciliationClass:"database-commit-unknown",operation:"generate-music",region:"test-region",state:"pending-observation",policyClass:"immediate-database",maxObservations:8,maxAttempts:4,writerEpoch:"1",nextEligibleAt:"2027-01-01T00:00:00.000Z",policyDeadlineAt:"2027-01-02T00:00:00.000Z",retentionClass:"reconciliation-standard"});const parent=await run(c=>requests.createIfAbsent(c,request));if(parent.status!=="committed"||parent.value.status!=="created")throw new Error("safe-group1-parent");const parentId=parent.value.record.id;
    const future=String((await environment.pool.query("SELECT (transaction_timestamp()+interval '1 hour')::text value")).rows[0].value),later=String((await environment.pool.query("SELECT (transaction_timestamp()+interval '2 hours')::text value")).rows[0].value);
    const drafts=new Map<number,ReconciliationOutboxDraft>();
    const makeDraft=(seed:number)=>{const draft=Object.freeze({requestId:parentId,identity:identity("reconciliation-outbox",seed),tenant,fingerprint:fingerprint("reconciliation-outbox-semantic",seed),eventType:"reconciliation.lifecycle-v2",payload:Object.freeze({marker:seed,status:"pending"}),nextEligibleAt:"2027-01-01T00:00:00.000Z",retentionClass:"reconciliation-standard"});drafts.set(seed,draft);return draft;};
    const claimed=async(seed:number,lease=future,claimOwner=owner)=>{const draft=makeDraft(seed);const created=await run(c=>v1.appendIfAbsent(c,draft));assert.equal(created.status,"committed");const claim=await run(c=>v1.claimBatch(c,{owner:claimOwner,expectedFence:"0",writerEpoch:"1",leaseExpiresAt:lease},1));if(claim.status!=="committed"||claim.value.length!==1)throw new Error("safe-group1-claim");return Object.freeze({draft,record:claim.value[0]!});};
    const guard=(fixture:{draft:ReconciliationOutboxDraft;record:ReconciliationOutboxRecord})=>Object.freeze({identity:fixture.draft.identity,expectedFingerprint:fixture.draft.fingerprint,expectedRevision:fixture.record.revision,expectedSourceState:"claimed" as const,expectedOwner:fixture.record.claimOwner!,expectedFence:fixture.record.fencingRevision});

    const stale=await claimed(24),base=guard(stale);for(const [label,call] of [["owner-renew",(c:C)=>v2.renewLeaseV2(c,{...base,expectedOwner:wrongOwner,leaseExpiresAt:later})],["owner-release",(c:C)=>v2.releaseLeaseV2(c,{...base,expectedOwner:wrongOwner})],["owner-delivered",(c:C)=>v2.transitionV2(c,{...base,expectedOwner:wrongOwner,targetState:"delivered"})],["owner-required",(c:C)=>v2.transitionV2(c,{...base,expectedOwner:wrongOwner,targetState:"reconciliation-required",safeFailureClass:"delivery-unknown"})],["fence-renew",(c:C)=>v2.renewLeaseV2(c,{...base,expectedFence:"0",leaseExpiresAt:later})],["fence-release",(c:C)=>v2.releaseLeaseV2(c,{...base,expectedFence:"0"})],["fence-delivered",(c:C)=>v2.transitionV2(c,{...base,expectedFence:"0",targetState:"delivered"})],["fence-required",(c:C)=>v2.transitionV2(c,{...base,expectedFence:"0",targetState:"reconciliation-required",safeFailureClass:"delivery-unknown"})]] as const){const result=await run(call);assert.equal(result.status,"committed",label);if(result.status==="committed")assert.deepEqual(result.value,{status:"conflict",conflictClass:"stale-fence",providerSubmitPermitted:false},label);}
    for(const call of [(c:C)=>v2.renewLeaseV2(c,{...base,expectedRevision:"999",leaseExpiresAt:later}),(c:C)=>v2.releaseLeaseV2(c,{...base,expectedRevision:"999"}),(c:C)=>v2.transitionV2(c,{...base,expectedRevision:"999",targetState:"delivered"}),(c:C)=>v2.transitionV2(c,{...base,expectedRevision:"999",targetState:"reconciliation-required",safeFailureClass:"delivery-unknown"})]){const result=await run(call);assert.equal(result.status,"committed");if(result.status==="committed")assert.deepEqual(result.value,{status:"conflict",conflictClass:"stale-revision",providerSubmitPermitted:false});}
    const unchanged=(await environment.pool.query("SELECT revision::text,safe_payload FROM workflow.workflow_reconciliation_outbox_events WHERE event_id=$1",[stale.record.id])).rows[0];assert.equal(unchanged.revision,stale.record.revision);

    const pending=makeDraft(25);await run(c=>v1.appendIfAbsent(c,pending));const pendingBefore=(await environment.pool.query("SELECT revision::text,safe_payload FROM workflow.workflow_reconciliation_outbox_events WHERE identity_digest=$1",[pending.identity.digest])).rows[0],pendingResult=await run(c=>v2.transitionV2(c,{identity:pending.identity,expectedFingerprint:pending.fingerprint,expectedRevision:"0",expectedSourceState:"claimed",expectedOwner:owner,expectedFence:"0",targetState:"delivered"}));assert.equal(pendingResult.status,"committed");if(pendingResult.status==="committed")assert.deepEqual(pendingResult.value,{status:"conflict",conflictClass:"stale-fence",providerSubmitPermitted:false});const pendingAfter=(await environment.pool.query("SELECT revision::text,safe_payload FROM workflow.workflow_reconciliation_outbox_events WHERE identity_digest=$1",[pending.identity.digest])).rows[0];assert.equal(pendingAfter.revision,pendingBefore.revision,"pending-ownership-priority-revision-unchanged");assert.equal(JSON.stringify(pendingAfter.safe_payload)===JSON.stringify(pendingBefore.safe_payload),true,"pending-ownership-priority-payload-unchanged");
  }finally{assert.equal(manager.dispose(),"disposed");assert.equal(await bridge.close(),"closed");}
}));

test("Fixture Group 1 verifies expired takeover in an isolated database",async()=>withPostgreSqlTestEnvironment(async environment=>{
  const bridge=new SliceATestStatementBridge({...environment.connection,maxConnections:8,connectionTimeoutMs:5000,idleTimeoutMs:5000,applicationName:"reconciliation-outbox-v2-takeover",tls:{mode:"disabled"}});assert.equal(registerPostgreSQLReconciliationStatements(bridge),"registered");assert.equal(await bridge.start(),"ready");
  const generator=ids(),requests=createPostgreSQLReconciliationRequestStore(generator),v1=createPostgreSQLReconciliationOutboxStore(generator),v2=createPostgreSQLReconciliationOutboxStoreV2(),manager=createDurableWorkflowTransactionManagerV2(bridge.sessionFactory(),clock),tenant=identity("tenant",32),workflow=identity("workflow",33),owner=identity("claim-owner",34),newOwner=identity("claim-owner",35);
  const run=<T>(operation:(context:Parameters<typeof v2.transitionV2>[0])=>Promise<T>)=>manager.runInTransaction(options,async context=>durableTransactionSuccess(await operation(context)));
  try{
    const request:ReconciliationRequestDraft=Object.freeze({identity:identity("reconciliation-request",31),tenant,workflow,fingerprint:fingerprint("reconciliation-request-semantic",31),reconciliationClass:"database-commit-unknown",operation:"generate-music",region:"test-region",state:"pending-observation",policyClass:"immediate-database",maxObservations:8,maxAttempts:4,writerEpoch:"1",nextEligibleAt:"2027-01-01T00:00:00.000Z",policyDeadlineAt:"2027-01-02T00:00:00.000Z",retentionClass:"reconciliation-standard"});
    const parent=await run(c=>requests.createIfAbsent(c,request));if(parent.status!=="committed"||parent.value.status!=="created")throw new Error("safe-group1-takeover-parent");
    const draft:ReconciliationOutboxDraft=Object.freeze({requestId:parent.value.record.id,identity:identity("reconciliation-outbox",36),tenant,fingerprint:fingerprint("reconciliation-outbox-semantic",36),eventType:"reconciliation.lifecycle-v2",payload:Object.freeze({marker:36,status:"pending"}),nextEligibleAt:"2027-01-01T00:00:00.000Z",retentionClass:"reconciliation-standard"});
    const created=await run(c=>v1.appendIfAbsent(c,draft));assert.equal(created.status,"committed");
    const leaseExpiresAt=String((await environment.pool.query("SELECT (transaction_timestamp()+interval '100 milliseconds')::text value")).rows[0].value),renewedLeaseExpiresAt=String((await environment.pool.query("SELECT (transaction_timestamp()+interval '1 hour')::text value")).rows[0].value);
    const claim=await run(c=>v1.claimBatch(c,{owner,expectedFence:"0",writerEpoch:"1",leaseExpiresAt},1));assert.equal(claim.status,"committed","safe-takeover-claim-status");if(claim.status!=="committed")throw new Error("safe-takeover-claim-unavailable");assert.equal(claim.value.length,1,"safe-takeover-claim-count");const claimed=claim.value[0];if(!claimed)throw new Error("safe-takeover-claim-missing");
    const identityMatches=claimed.identity.domain===draft.identity.domain&&claimed.identity.algorithm===draft.identity.algorithm&&claimed.identity.algorithmVersion===draft.identity.algorithmVersion&&claimed.identity.digest.length===draft.identity.digest.length&&claimed.identity.digest.every((value,index)=>value===draft.identity.digest[index]);assert.equal(identityMatches,true,"safe-takeover-fixture-isolation");
    let databaseExpired=false;for(let attempt=0;attempt<1000&&!databaseExpired;attempt++){databaseExpired=(await environment.pool.query("SELECT transaction_timestamp()>=$1::timestamptz expired",[leaseExpiresAt])).rows[0].expired===true;}assert.equal(databaseExpired,true,"database-authoritative-expiry");
    const taken=await run(c=>v2.takeoverExpiredLeaseV2(c,{identity:draft.identity,expectedRevision:claimed.revision,expectedSourceState:"claimed",expectedFence:claimed.fencingRevision,newOwner,leaseExpiresAt:renewedLeaseExpiresAt}));assert.equal(taken.status,"committed");if(taken.status==="committed")assert.deepEqual(taken.value,{status:"updated",outcome:"taken-over",providerSubmitPermitted:false});
    const takenRow=(await environment.pool.query("SELECT revision::text,fencing_revision::text,claim_owner_digest=$2 owner_changed FROM workflow.workflow_reconciliation_outbox_events WHERE event_id=$1",[claimed.id,newOwner.digest])).rows[0];assert.equal(takenRow.revision,String(Number(claimed.revision)+1));assert.equal(takenRow.fencing_revision,String(Number(claimed.fencingRevision)+1));assert.equal(takenRow.owner_changed,true);
  }finally{assert.equal(manager.dispose(),"disposed");assert.equal(await bridge.close(),"closed");}
}));
