import type { WorkflowUiEffect, WorkflowUiEvent, WorkflowUiState, WorkflowUiTransitionResult } from "./types";
import { copyWorkflowUi, createInitialPollState, createWorkflowUiError, validateWorkflowUiServiceResult } from "./workflowUiUtils";

export const createInitialWorkflowUiState = (): WorkflowUiState => ({ uiStateVersion: "1.0", kind: "idle", serverStatus: "none", activity: "idle", activeCommand: "none" });
const terminal = (state: WorkflowUiState) => ["completed", "degraded", "partial", "failed", "cancelled"].includes(state.kind);
const conflict = (state: WorkflowUiState): WorkflowUiTransitionResult => ({ status: "conflict", state: copyWorkflowUi(state), error: createWorkflowUiError("client-state-conflict") });
const transitioned = (state: WorkflowUiState, effects: readonly WorkflowUiEffect[] = []): WorkflowUiTransitionResult => ({ status: "transitioned", state: copyWorkflowUi(state), effects: copyWorkflowUi(effects) });

export function reduceWorkflowUiState(input: WorkflowUiState, event: WorkflowUiEvent): WorkflowUiTransitionResult {
  const state = copyWorkflowUi(input);
  if (event.type === "RESET_REQUESTED") return transitioned(createInitialWorkflowUiState());
  if (event.type === "RESULT_RECOVERY_STARTED") return transitioned({ uiStateVersion: "2.0", kind: "recovering-result", operation: event.operation, serverStatus: "none", activity: "recovering", activeCommand: "query-result", generation: event.generation, resultReference: copyWorkflowUi(event.reference), resultReferenceExpiresAt: event.expiresAt }, [{ type: "cancel-poll" }]);
  if (event.type === "RESULT_RECOVERY_FAILED") return state.kind === "recovering-result" && state.generation === event.generation ? transitioned(createInitialWorkflowUiState(), [{ type: "cancel-poll" }]) : conflict(state);
  if (event.type === "CANCEL_PREEMPTION_FAILED") { const previous = copyWorkflowUi(event.previous); previous.generation = event.generation; previous.activity = "paused"; previous.activeCommand = "none"; previous.poll = { ...previous.poll, status: "paused" }; return transitioned(previous, [{ type: "cancel-poll" }, { type: "save-session" }]); }
  if ("generation" in state && "generation" in event && ["COMMAND_SUCCEEDED", "COMMAND_FAILED", "REQUEST_ABORTED"].includes(event.type) && event.generation !== state.generation) return { status: "ignored-stale", state };
  if (terminal(state)) return conflict(state);
  if (event.type === "START_REQUESTED") return state.kind === "idle" ? transitioned({ uiStateVersion: "1.0", kind: "starting", operation: event.operation, serverStatus: "none", activity: "requesting", activeCommand: "start", startIdentity: "allocated", generation: event.generation }) : conflict(state);
  if (event.type === "COMMAND_SUCCEEDED") {
    const checked = validateWorkflowUiServiceResult(event.result);
    const operation = "operation" in state ? state.operation : "generate-mv";
    if (checked.status !== "valid") return state.kind === "recovering-result" ? transitioned(createInitialWorkflowUiState()) : transitioned({ uiStateVersion: "1.0", kind: "failed", operation, serverStatus: "failed", activity: "idle", activeCommand: "none", generation: event.generation, error: createWorkflowUiError("response-invalid") }, [{ type: "cancel-poll" }]);
    if (checked.value.status === "error") return state.kind === "recovering-result" ? transitioned(createInitialWorkflowUiState()) : transitioned({ uiStateVersion: "1.0", kind: "failed", operation, serverStatus: "failed", activity: "idle", activeCommand: "none", generation: event.generation, error: createWorkflowUiError(checked.value.body.code, checked.value.body.retryable) }, [{ type: "cancel-poll" }]);
    const result = checked.value.body;
    if (state.kind === "recovering-result" && (result.status === "pending-upload" || result.status === "pending-generation")) return conflict(state);
    if (result.status === "pending-upload") return transitioned({ uiStateVersion: "1.0", kind: "pending-upload", operation: result.operation, serverStatus: result.status, activity: "waiting", activeCommand: "none", generation: event.generation, reference: copyWorkflowUi(result.reference), poll: state.kind === "pending-upload" || state.kind === "pending-generation" ? copyWorkflowUi(state.poll) : createInitialPollState(), retryAdvice: copyWorkflowUi(result.retryAdvice), progress: copyWorkflowUi(result.progress) }, [{ type: "save-session" }]);
    if (result.status === "pending-generation") return transitioned({ uiStateVersion: "1.0", kind: "pending-generation", operation: result.operation, serverStatus: result.status, activity: "waiting", activeCommand: "none", generation: event.generation, reference: copyWorkflowUi(result.reference), poll: state.kind === "pending-upload" || state.kind === "pending-generation" ? copyWorkflowUi(state.poll) : createInitialPollState(), retryAdvice: copyWorkflowUi(result.retryAdvice), progress: copyWorkflowUi(result.progress) }, [{ type: "save-session" }]);
    const expiresAt = state.kind === "recovering-result" ? state.resultReferenceExpiresAt : undefined;
    if (result.status === "failed") return transitioned({ uiStateVersion: "1.0", kind: "failed", operation: result.operation, serverStatus: "failed", activity: "idle", activeCommand: "none", generation: event.generation, error: createWorkflowUiError(result.error.code, result.error.retryable), resultReference: copyWorkflowUi(result.resultReference), resultReferenceExpiresAt: expiresAt }, [{ type: "cancel-poll" }]);
    return transitioned({ uiStateVersion: "1.0", kind: result.status, operation: result.operation, serverStatus: result.status, activity: "idle", activeCommand: "none", generation: event.generation, resultReference: copyWorkflowUi(result.resultReference), resultReferenceExpiresAt: expiresAt, result: copyWorkflowUi(result) } as WorkflowUiState, [{ type: "cancel-poll" }]);
  }
  if (event.type === "COMMAND_FAILED") { if (!("operation" in state)) return conflict(state); if (state.kind === "recovering-result") return transitioned(createInitialWorkflowUiState()); if (state.kind === "pending-upload" || state.kind === "pending-generation") { state.activity = "paused"; state.activeCommand = "none"; state.generation = event.generation; state.poll = { ...state.poll, status: "paused" }; return transitioned(state, [{ type: "cancel-poll" }]); } return transitioned({ uiStateVersion: "1.0", kind: "failed", operation: state.operation, serverStatus: "failed", activity: "idle", activeCommand: "none", generation: event.generation, error: copyWorkflowUi(event.error) }, [{ type: "cancel-poll" }]); }
  if (event.type === "CANCEL_REQUESTED") return state.kind === "pending-upload" || state.kind === "pending-generation" ? transitioned({ uiStateVersion: "1.0", kind: "cancelling", operation: state.operation, serverStatus: state.serverStatus, activity: "requesting", activeCommand: "cancel", generation: event.generation, reference: copyWorkflowUi(state.reference) }, [{ type: "cancel-poll" }]) : conflict(state);
  if (event.type === "POLL_STARTED") { if (!(state.kind === "pending-upload" || state.kind === "pending-generation") || state.activeCommand !== "none") return conflict(state); state.activity = "requesting"; state.activeCommand = state.kind === "pending-upload" ? "poll-upload" : "poll-generation"; state.poll = copyWorkflowUi(event.poll); state.generation = event.generation; return transitioned(state); }
  if (event.type === "POLL_SCHEDULED") { if (!(state.kind === "pending-upload" || state.kind === "pending-generation")) return conflict(state); state.activity = "waiting"; state.activeCommand = "none"; state.poll = copyWorkflowUi(event.poll); state.generation = event.generation; return transitioned(state); }
  if (event.type === "POLL_PAUSED" || event.type === "POLL_BUDGET_EXHAUSTED") { if (!(state.kind === "pending-upload" || state.kind === "pending-generation")) return conflict(state); state.activity = "paused"; state.activeCommand = "none"; state.poll = copyWorkflowUi(event.poll); return transitioned(state, [{ type: "cancel-poll" }]); }
  if (event.type === "NETWORK_OFFLINE" || event.type === "VISIBILITY_HIDDEN") { if (!(state.kind === "pending-upload" || state.kind === "pending-generation")) return conflict(state); state.activity = "paused"; state.activeCommand = "none"; return transitioned(state, [{ type: "cancel-poll" }]); }
  if (event.type === "NETWORK_ONLINE" || event.type === "VISIBILITY_VISIBLE" || event.type === "RECOVERY_REQUESTED") { if (!(state.kind === "pending-upload" || state.kind === "pending-generation")) return conflict(state); state.activity = "recovering"; state.activeCommand = "query-result"; state.generation = event.generation; return transitioned(state, [{ type: "query-result" }]); }
  if (event.type === "REQUEST_ABORTED") { if (state.kind === "starting") return transitioned(createInitialWorkflowUiState()); if (state.kind === "recovering-result") return transitioned(createInitialWorkflowUiState()); if (state.kind === "pending-upload" || state.kind === "pending-generation") { state.activity = "paused"; state.activeCommand = "none"; return transitioned(state, [{ type: "cancel-poll" }]); } }
  return conflict(state);
}
