import type {WorkflowApiErrorDTO,WorkflowApiResultDTO,WorkflowApiServiceResult,WorkflowReferenceDTO,WorkflowRetryAdviceDTO} from "@/lib/workflowApi/types";import {validateErrorDto,validateReference,validateResultDto,validUtcMillis} from "@/lib/workflowApi/workflowApiUtils";import type {WorkflowUiDescriptor,WorkflowUiEvent,WorkflowUiPollPolicy,WorkflowUiPollState,WorkflowUiPublicError,WorkflowUiSession,WorkflowUiState} from "./types";
const forbidden=new Set(["__proto__","prototype","constructor"]),errorCodes=new Set(["request-invalid","request-version-unsupported","operation-unsupported","unauthenticated","unauthorized","reference-unavailable","reference-expired","idempotency-conflict","workflow-conflict","workflow-failed","workflow-cancelled","rate-limited","temporarily-unavailable","timeout","reconciliation-required","internal-error"]),operations=new Set(["generate-vocal","generate-music","generate-mv"]);const keysExact=(v:Record<string,unknown>,keys:readonly string[])=>{const allowed=keys.map(k=>k.endsWith("?")?k.slice(0,-1):k);return Object.keys(v).every(k=>allowed.includes(k)&&!forbidden.has(k))&&keys.filter(k=>!k.endsWith("?")).every(k=>k in v)};
export const isWorkflowUiPlainObject=(v:unknown):v is Record<string,unknown>=>{if(!v||typeof v!=="object"||Array.isArray(v))return false;const p=Object.getPrototypeOf(v);return p===Object.prototype||p===null};export const copyWorkflowUi=<T>(v:T):T=>v===undefined?v:JSON.parse(JSON.stringify(v));export const freezeWorkflowUi=<T>(v:T):Readonly<T>=>Object.freeze(copyWorkflowUi(v));
export function hasWorkflowUiUnsafeStructure(v:unknown,depth=0,seen=new Set<object>()):boolean{if(depth>16)return true;if(!v||typeof v!=="object")return false;if(seen.has(v as object))return true;seen.add(v as object);if(Array.isArray(v))return v.length>500||v.some(x=>hasWorkflowUiUnsafeStructure(x,depth+1,seen));if(!isWorkflowUiPlainObject(v))return true;return Object.keys(v).some(k=>forbidden.has(k))||Object.values(v).some(x=>hasWorkflowUiUnsafeStructure(x,depth+1,seen))}
const validAsset=(a:unknown)=>isWorkflowUiPlainObject(a)&&keysExact(a,["assetVersion","assetId","kind","role","mimeType"])&&a.assetVersion==="1.0"&&typeof a.assetId==="string"&&a.assetId.length>0&&a.assetId.length<=128&&typeof a.kind==="string"&&a.kind.length>0&&typeof a.role==="string"&&a.role.length>0&&typeof a.mimeType==="string"&&/^[a-z0-9.+-]+\/[a-z0-9.+-]+$/i.test(a.mimeType);const validProgress=(p:unknown)=>p===undefined||isWorkflowUiPlainObject(p)&&keysExact(p,["progressVersion","stage","percent?"])&&p.progressVersion==="1.0"&&["upload","generation","ingestion"].includes(p.stage as string)&&(p.percent===undefined||typeof p.percent==="number"&&Number.isFinite(p.percent)&&p.percent>=0&&p.percent<=100);
export function validWorkflowUiRetryAdvice(v:unknown):v is WorkflowRetryAdviceDTO{return isWorkflowUiPlainObject(v)&&keysExact(v,["retryVersion","retryable","retryAfterClass?"])&&v.retryVersion==="1.0"&&typeof v.retryable==="boolean"&&(v.retryAfterClass===undefined||["short","medium","long"].includes(v.retryAfterClass as string))}
function strictResult(body:WorkflowApiResultDTO){if(body.status==="pending-upload"||body.status==="pending-generation")return validWorkflowUiRetryAdvice(body.retryAdvice??{retryVersion:"1.0",retryable:false})&&validProgress(body.progress);if(body.status==="failed")return validateErrorDto(body.error).status==="valid"&&errorCodes.has(body.error.code)&&validateReference(body.resultReference,"workflow-result").status==="valid";if(body.status==="cancelled")return validateReference(body.resultReference,"workflow-result").status==="valid";return body.assets.every(validAsset)&&new Set(body.assets.map(a=>a.assetId)).size===body.assets.length&&validateReference(body.resultReference,"workflow-result").status==="valid"}
export function validateWorkflowUiServiceResult(raw:unknown):{status:"valid";value:WorkflowApiServiceResult}|{status:"invalid"}{try{if(!isWorkflowUiPlainObject(raw)||hasWorkflowUiUnsafeStructure(raw)||!keysExact(raw,["status","http","body"])||!(raw.status==="success"||raw.status==="error")||!isWorkflowUiPlainObject(raw.http)||!keysExact(raw.http,["statusCode","headers"])||!Number.isInteger(raw.http.statusCode)||!Array.isArray(raw.http.headers))return{status:"invalid"};if(raw.status==="success"){const v=validateResultDto(raw.body);if(v.status!=="valid"||!strictResult(v.value))return{status:"invalid"};const expected=v.value.status==="pending-upload"||v.value.status==="pending-generation"?202:200;if(raw.http.statusCode!==expected)return{status:"invalid"};return{status:"valid",value:copyWorkflowUi(raw as WorkflowApiServiceResult)}}const v=validateErrorDto(raw.body);return v.status==="valid"&&errorCodes.has((raw.body as WorkflowApiErrorDTO).code)?{status:"valid",value:copyWorkflowUi(raw as WorkflowApiServiceResult)}:{status:"invalid"}}catch{return{status:"invalid"}}}
const messageByCode:Record<string,`workflow.${string}`>={"request-invalid":"workflow.requestInvalid","request-version-unsupported":"workflow.requestVersionUnsupported","operation-unsupported":"workflow.operationUnsupported",unauthenticated:"workflow.unauthenticated",unauthorized:"workflow.unauthorized","reference-unavailable":"workflow.referenceUnavailable","reference-expired":"workflow.referenceExpired","idempotency-conflict":"workflow.idempotencyConflict","workflow-conflict":"workflow.workflowConflict","workflow-failed":"workflow.failed","workflow-cancelled":"workflow.cancelled","rate-limited":"workflow.rateLimited","temporarily-unavailable":"workflow.serviceUnavailable",timeout:"workflow.timeout","reconciliation-required":"workflow.reconciliation","internal-error":"workflow.internalError","network-unavailable":"workflow.networkUnavailable","request-timeout":"workflow.timeout","response-invalid":"workflow.responseInvalid","service-unavailable":"workflow.serviceUnavailable","request-aborted":"workflow.requestAborted","client-state-conflict":"workflow.stateConflict","command-conflict":"workflow.commandConflict"};export function createWorkflowUiError(code:string,retryable=false):WorkflowUiPublicError{return{errorVersion:"1.0",code:(messageByCode[code]?code:"internal-error") as WorkflowUiPublicError["code"],messageKey:messageByCode[code]??"workflow.internalError",retryable}}
export function validWorkflowUiPollPolicy(v:unknown):v is WorkflowUiPollPolicy{if(!isWorkflowUiPlainObject(v)||!keysExact(v,["policyVersion","delaysMs","maxAttempts","maxElapsedMs","maxConsecutiveNetworkFailures"])||v.policyVersion!=="1.0"||!isWorkflowUiPlainObject(v.delaysMs)||!keysExact(v.delaysMs,["short","medium","long"]))return false;const d=v.delaysMs as Record<string,unknown>,nums=[d.short,d.medium,d.long,v.maxAttempts,v.maxElapsedMs,v.maxConsecutiveNetworkFailures];return nums.every(x=>Number.isSafeInteger(x)&&(x as number)>0)&&(d.short as number)<=(d.medium as number)&&(d.medium as number)<=(d.long as number)}
export function validWorkflowUiPollState(v:unknown):v is WorkflowUiPollState{return isWorkflowUiPlainObject(v)&&keysExact(v,["pollVersion","budget","lastRetryClass?","status"])&&v.pollVersion==="1.0"&&isWorkflowUiPlainObject(v.budget)&&keysExact(v.budget,["attempts","elapsedMs","consecutiveNetworkFailures"])&&[v.budget.attempts,v.budget.elapsedMs,v.budget.consecutiveNetworkFailures].every(x=>Number.isSafeInteger(x)&&(x as number)>=0)&&(v.lastRetryClass===undefined||["short","medium","long"].includes(v.lastRetryClass as string))&&["ready","scheduled","paused","stopped"].includes(v.status as string)}
export function validWorkflowUiSession(v:unknown):v is WorkflowUiSession{if(!isWorkflowUiPlainObject(v)||hasWorkflowUiUnsafeStructure(v)||!keysExact(v,["sessionVersion","operation","reference","lastServerStatus","resultReference?","pollAttempts","createdAt","expiresAt"]))return false;return v.sessionVersion==="1.0"&&operations.has(v.operation as string)&&validateReference(v.reference).status==="valid"&&(v.resultReference===undefined||validateReference(v.resultReference,"workflow-result").status==="valid")&&["pending-upload","pending-generation","completed","degraded","partial","failed","cancelled"].includes(v.lastServerStatus as string)&&Number.isSafeInteger(v.pollAttempts)&&(v.pollAttempts as number)>=0&&validUtcMillis(v.createdAt)&&validUtcMillis(v.expiresAt)&&(v.expiresAt as string)>(v.createdAt as string)}
export function validWorkflowUiState(v:unknown):v is WorkflowUiState{if(!isWorkflowUiPlainObject(v)||hasWorkflowUiUnsafeStructure(v)||v.uiStateVersion!=="1.0"||typeof v.kind!=="string")return false;const common=typeof v.activity==="string"&&typeof v.activeCommand==="string"&&typeof v.serverStatus==="string";if(!common)return false;if(v.kind==="idle")return keysExact(v,["uiStateVersion","kind","serverStatus","activity","activeCommand"])&&v.serverStatus==="none"&&v.activity==="idle"&&v.activeCommand==="none";if(!operations.has(v.operation as string)||!Number.isSafeInteger(v.generation)||(v.generation as number)<1)return false;if(v.kind==="starting")return keysExact(v,["uiStateVersion","kind","operation","serverStatus","activity","activeCommand","generation","startIdentity"])&&v.activity==="requesting"&&v.activeCommand==="start"&&v.serverStatus==="none";if(v.kind==="pending-upload"||v.kind==="pending-generation")return keysExact(v,["uiStateVersion","kind","operation","serverStatus","activity","activeCommand","generation","reference","poll","retryAdvice?","progress?"])&&v.serverStatus===v.kind&&validateReference(v.reference,v.kind==="pending-upload"?"upload-pending":"generation-job").status==="valid"&&validWorkflowUiPollState(v.poll)&&(v.retryAdvice===undefined||validWorkflowUiRetryAdvice(v.retryAdvice))&&validProgress(v.progress);if(v.kind==="cancelling")return keysExact(v,["uiStateVersion","kind","operation","serverStatus","activity","activeCommand","generation","reference"])&&v.activity==="requesting"&&v.activeCommand==="cancel"&&validateReference(v.reference).status==="valid";if(v.kind==="failed")return keysExact(v,["uiStateVersion","kind","operation","serverStatus","activity","activeCommand","generation","error","resultReference?"])&&v.serverStatus==="failed"&&v.activity==="idle"&&v.activeCommand==="none"&&validWorkflowUiError(v.error);if(["completed","degraded","partial","cancelled"].includes(v.kind))return keysExact(v,["uiStateVersion","kind","operation","serverStatus","activity","activeCommand","generation","resultReference","result"])&&v.serverStatus===v.kind&&v.activity==="idle"&&v.activeCommand==="none"&&validateWorkflowUiServiceResult({status:"success",http:{statusCode:200,headers:[]},body:v.result}).status==="valid";return false}
export function validWorkflowUiError(v:unknown):v is WorkflowUiPublicError{return isWorkflowUiPlainObject(v)&&keysExact(v,["errorVersion","code","messageKey","retryable"])&&v.errorVersion==="1.0"&&typeof v.code==="string"&&typeof v.messageKey==="string"&&v.messageKey.startsWith("workflow.")&&typeof v.retryable==="boolean"}
export function validWorkflowUiEvent(v:unknown):v is WorkflowUiEvent{return isWorkflowUiPlainObject(v)&&typeof v.type==="string"&&["START_REQUESTED","COMMAND_SUCCEEDED","COMMAND_FAILED","POLL_SCHEDULED","POLL_STARTED","POLL_PAUSED","POLL_BUDGET_EXHAUSTED","NETWORK_OFFLINE","NETWORK_ONLINE","VISIBILITY_HIDDEN","VISIBILITY_VISIBLE","CANCEL_REQUESTED","REQUEST_ABORTED","RECOVERY_REQUESTED","RESET_REQUESTED"].includes(v.type)}
export function validWorkflowUiDescriptor(v:unknown):v is WorkflowUiDescriptor{return isWorkflowUiPlainObject(v)&&keysExact(v,["id","contractVersion","supportedOperations","capabilities","availability"])&&typeof v.id==="string"&&v.contractVersion==="1.0"&&Array.isArray(v.supportedOperations)&&v.supportedOperations.every(x=>operations.has(x))&&Array.isArray(v.capabilities)&&v.capabilities.every(x=>typeof x==="string")&&v.availability==="available"}
export const createInitialPollState=():WorkflowUiPollState=>({pollVersion:"1.0",budget:{attempts:0,elapsedMs:0,consecutiveNetworkFailures:0},status:"ready"});export function referenceFromResult(result:WorkflowApiResultDTO):WorkflowReferenceDTO|undefined{return result.status==="pending-upload"||result.status==="pending-generation"?copyWorkflowUi(result.reference):"resultReference"in result?copyWorkflowUi(result.resultReference):undefined}

export type WorkflowUiTerminalComparison = { status: "same" } | { status: "conflict" } | { status: "invalid" };
export function compareWorkflowUiTerminalResults(left: unknown, right: unknown): WorkflowUiTerminalComparison {
  const terminal = (value: unknown): WorkflowApiResultDTO | undefined => {
    const checked = validateWorkflowUiServiceResult({ status: "success", http: { statusCode: 200, headers: [] }, body: value });
    if (checked.status !== "valid" || checked.value.status !== "success") return undefined;
    const body = checked.value.body;
    return body.status === "pending-upload" || body.status === "pending-generation" ? undefined : body;
  };
  try {
    const a = terminal(left), b = terminal(right); if (!a || !b) return { status: "invalid" };
    const reference = (value: WorkflowApiResultDTO) => "resultReference" in value ? value.resultReference : undefined;
    const assets = (value: WorkflowApiResultDTO) => "assets" in value ? value.assets.map(asset => [asset.assetId, asset.kind, asset.role, asset.mimeType]) : [];
    const warning = (value: WorkflowApiResultDTO) => value.status === "degraded" || value.status === "partial" ? value.status : "none";
    const error = (value: WorkflowApiResultDTO) => value.status === "failed" ? [value.error.code, value.error.retryable] : [];
    const signature = (value: WorkflowApiResultDTO) => JSON.stringify([value.status, value.operation, assets(value), warning(value), error(value), reference(value)?.kind, reference(value)?.reference]);
    return { status: signature(a) === signature(b) ? "same" : "conflict" };
  } catch { return { status: "invalid" }; }
}
