import type { DurableWorkflowDatabaseRow } from "../durableTransaction";
import { bytesField, execute, immutableJsonObject, stringField, validDigest, validUuid } from "./postgresqlStoreUtils";
import type { PostgreSQLInternalUuidGenerator, PostgreSQLOutboxRecord, PostgreSQLOutboxStoreV2 } from "./types";

function parse(row:DurableWorkflowDatabaseRow):PostgreSQLOutboxRecord|undefined{
  const internalId=stringField(row,"event_id"),event=bytesField(row,"event_digest"),aggregate=bytesField(row,"aggregate_digest"),resultId=stringField(row,"result_id"),eventType=stringField(row,"event_type"),payloadText=stringField(row,"safe_payload"),deliveryState=stringField(row,"delivery_state"),attemptValue=row.attempt,nextEligibleAt=stringField(row,"next_eligible_at"),revision=stringField(row,"revision");
  if(!internalId||!event||!aggregate||!resultId||!eventType||!payloadText||!deliveryState||!(typeof attemptValue==="number"||typeof attemptValue==="string")||!nextEligibleAt||!revision||!validUuid(internalId)||!validUuid(resultId))return undefined;
  let payload:Record<string,string|number|boolean|null>;try{payload=JSON.parse(payloadText);}catch{return undefined;}
  const owner=bytesField(row,"claim_owner_digest"),fence=stringField(row,"fencing_revision"),lease=stringField(row,"lease_expires_at"),delivered=stringField(row,"delivered_at"),failure=stringField(row,"safe_failure_class");
  return Object.freeze({internalId,eventIdentity:Object.freeze({algorithm:"sha256",version:1,bytes:event}),aggregateIdentity:Object.freeze({algorithm:"sha256",version:1,bytes:aggregate}),resultId,eventType,safePayload:immutableJsonObject(payload),deliveryState:deliveryState as PostgreSQLOutboxRecord["deliveryState"],attempt:Number(attemptValue),nextEligibleAt,revision,...(owner?{claimOwnerIdentity:Object.freeze({algorithm:"sha256" as const,version:1 as const,bytes:owner})}:{}),...(fence?{fencingRevision:fence}:{}),...(lease?{leaseExpiresAt:lease}:{}),...(delivered?{deliveredAt:delivered}:{}),...(failure?{safeFailureClass:failure}:{})});
}

export function createPostgreSQLOutboxStore(generator:PostgreSQLInternalUuidGenerator):PostgreSQLOutboxStoreV2{return Object.freeze({storeVersion:"2.0",async append(context,resultId,draft){
  const id=generator.generate();if(!validUuid(id)||!validUuid(resultId)||!validDigest(draft.eventIdentity)||!validDigest(draft.aggregateIdentity))return{status:"conflict"};
  const result=await execute(context.database,"slice-a.outbox.insert",[id,draft.eventIdentity.bytes,draft.aggregateIdentity.bytes,resultId,draft.eventType,JSON.stringify(draft.safePayload),draft.nextEligibleAt],"many");
  if(result.status==="success"&&result.rows.length===1)return{status:"appended",record:Object.freeze({...draft,internalId:id,resultId,deliveryState:"pending",attempt:0,revision:"0"})};
  if(result.status==="success"&&result.rows.length===0){const found=await execute(context.database,"slice-a.outbox.read",[draft.eventIdentity.bytes],"single");const record=found.status==="success"&&found.rows[0]?parse(found.rows[0]):undefined;return record?{status:"duplicate",record}:{status:"conflict"};}
  return{status:"unavailable"};
},async claimBatch(context,request){if(request.limit<1||request.limit>100||!validDigest(request.ownerIdentity))return{status:"conflict"};const result=await execute(context.database,"slice-a.outbox.claim",[request.limit,request.now,request.ownerIdentity.bytes,request.leaseExpiresAt],"many");if(result.status!=="success")return{status:"unavailable"};const records=result.rows.map(parse);if(records.some((value)=>!value))return{status:"conflict"};return records.length?{status:"claimed",records:records.filter((value):value is PostgreSQLOutboxRecord=>value!==undefined)}:{status:"empty"};},async renew(context,event,expectedFence,owner,now,nextExpiry){const result=await execute(context.database,"slice-a.outbox.renew",[event.bytes,expectedFence,owner.bytes,now,nextExpiry],"many");if(result.status!=="success")return{status:"unavailable"};if(result.rows.length!==1)return{status:"stale-fence"};const record=parse(result.rows[0]!);return record?{status:"renewed",record}:{status:"unavailable"};},async release(context,event,expectedFence,owner,nextEligibleAt){const result=await execute(context.database,"slice-a.outbox.release",[event.bytes,expectedFence,owner.bytes,"1970-01-01T00:00:00.000Z",nextEligibleAt],"many");return result.status==="success"&&result.rows.length===1?{status:"delivered"}:result.status==="failure"?{status:"unavailable"}:{status:"stale-fence"};},async markReconciliationRequired(context,event,expectedRevision,failureClass){const result=await execute(context.database,"slice-a.outbox.reconcile",[event.bytes,expectedRevision,failureClass],"many");return result.status==="success"&&result.rows.length===1?{status:"delivered"}:result.status==="failure"?{status:"unavailable"}:{status:"stale-fence"};},async markDelivered(context,event,expectedFence,deliveredAt){const result=await execute(context.database,"slice-a.outbox.deliver",[event.bytes,expectedFence,deliveredAt],"many");if(result.status!=="success")return{status:"unavailable"};if(result.rows.length===1)return{status:"delivered"};const found=await execute(context.database,"slice-a.outbox.read",[event.bytes],"single");if(found.status==="not-found")return{status:"stale-fence"};const row=found.status==="success"?found.rows[0]:undefined;return row&&stringField(row,"delivery_state")==="delivered"?{status:"duplicate"}:{status:"stale-fence"};}});}
