import type { WorkflowApiErrorCode,WorkflowApiServiceResult } from "@/lib/workflowApi/types";
import { copy,isPlainObject,validateErrorDto,validateResultDto } from "@/lib/workflowApi/workflowApiUtils";
const messages:Record<WorkflowApiErrorCode,string>={"request-invalid":"The request could not be processed.","request-version-unsupported":"The request version is not supported.","operation-unsupported":"The operation is not supported.",unauthenticated:"Authentication is required.",unauthorized:"The operation is not permitted.","reference-unavailable":"The workflow reference is unavailable.","reference-expired":"The workflow reference is unavailable.","idempotency-conflict":"The request conflicts with an earlier request.","workflow-conflict":"The workflow state could not be updated.","workflow-failed":"The workflow could not be completed.","workflow-cancelled":"The workflow was cancelled.","rate-limited":"Too many requests were made.","temporarily-unavailable":"The workflow service is temporarily unavailable.",timeout:"The workflow outcome is not yet available.","reconciliation-required":"The workflow outcome requires reconciliation.","internal-error":"The workflow request could not be completed."};
const expectedStatus:Record<WorkflowApiErrorCode,readonly number[]>={"request-invalid":[400,413,415],"request-version-unsupported":[400],"operation-unsupported":[422],unauthenticated:[401],unauthorized:[403],"reference-unavailable":[404],"reference-expired":[410],"idempotency-conflict":[409],"workflow-conflict":[409],"workflow-failed":[500],"workflow-cancelled":[200],"rate-limited":[429],"temporarily-unavailable":[503],timeout:[504],"reconciliation-required":[202],"internal-error":[500]};
const baseHeaders={"Cache-Control":"no-store, max-age=0","Pragma":"no-cache","X-Content-Type-Options":"nosniff","Referrer-Policy":"no-referrer","Content-Type":"application/json; charset=utf-8"};
const errorCodes=new Set(Object.keys(messages));
export function createReferenceWorkflowApiRouteError(statusCode:number,code:WorkflowApiErrorCode,retryable=false,retryAfterClass?:"short"|"medium"|"long"):WorkflowApiServiceResult{return{status:"error",http:{statusCode,headers:[]},body:{errorVersion:"1.0",code,message:messages[code],retryable,...(retryAfterClass?{retryAfterClass}:{})}}}
const validServiceResult=(raw:unknown):raw is WorkflowApiServiceResult=>{if(!isPlainObject(raw)||!(raw.status==="success"||raw.status==="error")||!isPlainObject(raw.http)||!Number.isInteger(raw.http.statusCode)||!Array.isArray(raw.http.headers))return false;if(raw.status==="success"){const body=validateResultDto(raw.body);if(body.status!=="valid")return false;const pending=body.value.status==="pending-upload"||body.value.status==="pending-generation";if((raw.http.statusCode as number)!==(pending?202:200))return false;if(body.value.status==="failed"&&(!isPlainObject(body.value.error)||validateErrorDto(body.value.error).status!=="valid"))return false;return true}const body=validateErrorDto(raw.body);if(body.status!=="valid"||!errorCodes.has(body.value.code)||body.value.message!==messages[body.value.code])return false;return expectedStatus[body.value.code].includes(raw.http.statusCode as number)};
const internalError=()=>createReferenceWorkflowApiRouteError(500,"internal-error");
export function toReferenceWorkflowApiResponse(raw:unknown):Response{try{const result=validServiceResult(raw)?raw:internalError(),payload=JSON.stringify(copy(result.body));return new Response(payload,{status:result.http.statusCode,headers:new Headers(baseHeaders)})}catch{const fallback=internalError();return new Response(JSON.stringify(fallback.body),{status:500,headers:new Headers(baseHeaders)})}}
export const projectReferenceWorkflowRouteLog=(input:{routeId:string;command:string;operation?:string;result:WorkflowApiServiceResult;requestSizeClass:"small"|"medium"|"large"|"too-large"})=>Object.freeze({routeId:input.routeId,command:input.command,...(input.operation?{operation:input.operation}:{}),httpClass:`${Math.floor(input.result.http.statusCode/100)}xx`,requestSizeClass:input.requestSizeClass,retryable:input.result.status==="error"?input.result.body.retryable:false,safeErrorCode:input.result.status==="error"?input.result.body.code:undefined});