// Server-only boundary: raw keys and request content are reduced to SHA-256 identities and are never exposed.
import { createHash } from "node:crypto";
import type { WorkflowApiCommand,WorkflowApiPrincipal,WorkflowApiServiceResult } from "@/lib/workflowApi/types";
import { copy } from "@/lib/workflowApi/workflowApiUtils";
const canonical=(v:unknown):string=>{if(v===null)return"null";if(Array.isArray(v))return`[${v.map(canonical).join(",")}]`;if(typeof v==="object")return`{${Object.keys(v as object).sort().map(k=>`${JSON.stringify(k)}:${canonical((v as Record<string,unknown>)[k])}`).join(",")}}`;return JSON.stringify(v)};
const digest=(v:unknown)=>createHash("sha256").update(canonical(v)).digest("hex");
export type WorkflowApiIdempotencyNamespace=`api-${WorkflowApiCommand}`;
export type ReferenceWorkflowApiIdempotencyStore={read(namespace:WorkflowApiIdempotencyNamespace,key:string,fingerprint:string):{status:"found";result:WorkflowApiServiceResult}|{status:"missing"|"conflict"};commit(namespace:WorkflowApiIdempotencyNamespace,key:string,fingerprint:string,result:WorkflowApiServiceResult):"stored"|"existing"|"conflict";clear():void};
export const createSafeWorkflowApiRequestFingerprint=(command:WorkflowApiCommand,request:unknown,principal:WorkflowApiPrincipal,scope?:{operation?:string;attempt?:number})=>{const semantic=request&&typeof request==="object"?Object.fromEntries(Object.entries(request as Record<string,unknown>).filter(([key])=>key!=="idempotencyKey")):request;return digest({fingerprintVersion:"1.0",command,apiVersion:"1.0",operation:scope?.operation??(semantic&&typeof semantic==="object"&&"operation"in semantic?(semantic as any).operation:undefined),attemptClass:scope?.attempt===undefined?undefined:scope.attempt===1?"initial":"retry",semanticRequest:digest(semantic),principalIdentity:digest({actorType:principal.actorType,subjectRef:principal.subjectRef,tenantRef:principal.tenantRef,region:principal.region})})};
export const shouldPersistWorkflowApiResult=(result:WorkflowApiServiceResult)=>result.status==="success"||!["unauthenticated","temporarily-unavailable","timeout","internal-error"].includes(result.body.code);
export function createReferenceWorkflowApiIdempotencyStore():ReferenceWorkflowApiIdempotencyStore{const values=new Map<string,{fingerprint:string;result:WorkflowApiServiceResult}>();const identity=(namespace:string,key:string)=>digest(["workflow-api-idempotency-v1",namespace,key]);return{read(namespace,key,fingerprint){const old=values.get(identity(namespace,key));return!old?{status:"missing"}:old.fingerprint!==fingerprint?{status:"conflict"}:{status:"found",result:copy(old.result)}},commit(namespace,key,fingerprint,result){const k=identity(namespace,key),old=values.get(k);if(old)return old.fingerprint===fingerprint?"existing":"conflict";values.set(k,{fingerprint,result:copy(result)});return"stored"},clear(){values.clear()}}}
