// Server-only boundary. Client tokens, protected record identities, and internal references are deliberately distinct.
import { createHash } from "node:crypto";
import type { ReferenceWorkflowResultQueryInput } from "@/lib/workflowEntry/types";
import type { WorkflowApiResultDTO,WorkflowReferenceDTO,WorkflowResultReferenceDTO } from "@/lib/workflowApi/types";
import { copy,validOpaque } from "@/lib/workflowApi/workflowApiUtils";
import type { WorkflowReferenceOwnership } from "./referenceWorkflowApiAuthProjector";
type InternalReference=ReferenceWorkflowResultQueryInput["reference"];
type VaultRecord={identity:string;kind:WorkflowReferenceDTO["kind"];internal?:InternalReference;ownership:WorkflowReferenceOwnership;state:"active"|"revoked";terminal?:WorkflowApiResultDTO};
const digest=(value:unknown)=>createHash("sha256").update(JSON.stringify(value)).digest("hex");
const tokenFor=(kind:string,identity:string)=>`wr_${digest(["workflow-api-reference-v1",kind,identity]).slice(0,64)}`;
export type ReferenceWorkflowApiReferenceVault={registerInternal(kind:"upload-pending"|"generation-job",internal:InternalReference,ownership:WorkflowReferenceOwnership):WorkflowReferenceDTO;commitTerminal(identity:string,ownership:WorkflowReferenceOwnership,build:(reference:WorkflowResultReferenceDTO)=>WorkflowApiResultDTO):{status:"stored"|"existing";reference:WorkflowResultReferenceDTO;result:WorkflowApiResultDTO}|{status:"conflict"};resolve(reference:WorkflowReferenceDTO):{status:"found";identity:string;kind:WorkflowReferenceDTO["kind"];internal?:InternalReference;ownership:WorkflowReferenceOwnership;state:"active"|"revoked";terminal?:WorkflowApiResultDTO}|{status:"unavailable"};revoke(reference:WorkflowReferenceDTO):"revoked"|"unavailable";clear():void};
export function createReferenceWorkflowApiReferenceVault():ReferenceWorkflowApiReferenceVault{const records=new Map<string,VaultRecord>(),identityIndex=new Map<string,string>();const protectedToken=(token:string)=>digest(["workflow-api-token-v1",token]);const put=(kind:WorkflowReferenceDTO["kind"],rawIdentity:string,ownership:WorkflowReferenceOwnership,internal?:InternalReference)=>{const identity=digest([rawIdentity,ownership.tenantRef,ownership.region,ownership.subjectRef??"",ownership.operation]),index=digest([kind,identity]),existingToken=identityIndex.get(index);if(existingToken){const old=records.get(existingToken)!;return{referenceVersion:"1.0",kind:old.kind,reference:tokenFor(old.kind,old.identity)} as WorkflowReferenceDTO}const token=tokenFor(kind,identity),key=protectedToken(token);records.set(key,{identity,kind,...(internal?{internal:copy(internal)}:{}),ownership:copy(ownership),state:"active"});identityIndex.set(index,key);return{referenceVersion:"1.0",kind,reference:token} as WorkflowReferenceDTO};return{registerInternal(kind,internal,ownership){return put(kind,digest(["internal-reference",kind,internal]),ownership,internal)},commitTerminal(rawIdentity,ownership,build){const identity=digest([digest(["terminal-result",rawIdentity]),ownership.tenantRef,ownership.region,ownership.subjectRef??"",ownership.operation]),index=digest(["workflow-result",identity]),knownKey=identityIndex.get(index);if(knownKey){const old=records.get(knownKey);if(!old?.terminal)return{status:"conflict"};const reference:WorkflowResultReferenceDTO={referenceVersion:"1.0",kind:"workflow-result",reference:tokenFor("workflow-result",identity)};build(reference);return{status:"existing",reference,result:copy(old.terminal)}}const reference:WorkflowResultReferenceDTO={referenceVersion:"1.0",kind:"workflow-result",reference:tokenFor("workflow-result",identity)},result=build(reference),key=protectedToken(reference.reference);records.set(key,{identity,kind:"workflow-result",ownership:copy(ownership),state:"active",terminal:copy(result)});identityIndex.set(index,key);return{status:"stored",reference,result:copy(result)}},resolve(reference){if(!validOpaque(reference.reference))return{status:"unavailable"};const old=records.get(protectedToken(reference.reference));if(!old||old.kind!==reference.kind)return{status:"unavailable"};return{status:"found",identity:old.identity,kind:old.kind,...(old.internal?{internal:copy(old.internal)}:{}),ownership:copy(old.ownership),state:old.state,...(old.terminal?{terminal:copy(old.terminal)}:{})}},revoke(reference){const key=protectedToken(reference.reference),old=records.get(key);if(!old||old.kind!==reference.kind)return"unavailable";old.state="revoked";records.set(key,old);return"revoked"},clear(){records.clear();identityIndex.clear()}}}
