// Server-only boundary. This service invokes existing workflows/entry points once and does not implement their state machine.
import { runReferenceVocalWorkflow } from "@/lib/workflows/referenceVocalWorkflow";
import { runReferenceMusicWorkflow } from "@/lib/workflows/referenceMusicWorkflow";
import { runReferenceMVWorkflow } from "@/lib/workflows/referenceMVWorkflow";
import { REFERENCE_VOCAL_CAPABILITY } from "@/lib/providers/referenceVocalAdapter";
import { REFERENCE_MUSIC_CAPABILITY } from "@/lib/providers/referenceMusicAdapter";
import { REFERENCE_MV_CAPABILITY } from "@/lib/providers/referenceMVAdapter";
import type { ReferenceWorkflowInput } from "@/lib/workflows/referenceWorkflowTypes";
import type { ReferenceWorkflowScenario } from "@/lib/workflows/types";
import type { ReferenceWorkflowEntryContext } from "@/lib/workflowEntry/types";
import type { WorkflowApiCommand,WorkflowApiOperation,WorkflowApiRequest,WorkflowApiServiceInput,WorkflowApiServiceResult,WorkflowReferenceDTO } from "@/lib/workflowApi/types";
import { classifyRequestSize,copy,validateContext,validatePrincipal,validateRequest } from "@/lib/workflowApi/workflowApiUtils";
import type { ReferenceWorkflowApiRuntimeProvider } from "./referenceWorkflowApiRuntimeProvider";
import type { ReferenceWorkflowApiAuthProjector,WorkflowReferenceOwnership } from "./referenceWorkflowApiAuthProjector";
import type { ReferenceWorkflowApiDtoMapper,ReferenceWorkflowApiMappableResult } from "./referenceWorkflowApiDtoMapper";
import type { ReferenceWorkflowApiReferenceVault } from "./referenceWorkflowApiReferenceVault";
import { SAFE_WORKFLOW_API_HEADERS } from "./referenceWorkflowApiErrorMapper";
import type { ReferenceWorkflowApiErrorMapper } from "./referenceWorkflowApiErrorMapper";
import { createSafeWorkflowApiRequestFingerprint,shouldPersistWorkflowApiResult,type ReferenceWorkflowApiIdempotencyStore } from "./referenceWorkflowApiIdempotencyStore";
export type ReferenceWorkflowApiServiceDependencies={runtimeProvider:ReferenceWorkflowApiRuntimeProvider;authProjector:ReferenceWorkflowApiAuthProjector;idempotencyStore:ReferenceWorkflowApiIdempotencyStore;dtoMapper:ReferenceWorkflowApiDtoMapper;referenceVault:ReferenceWorkflowApiReferenceVault;errorMapper:ReferenceWorkflowApiErrorMapper;scenarios?:Partial<Record<WorkflowApiOperation,ReferenceWorkflowScenario>>};
export type ReferenceWorkflowApiService={start(input:WorkflowApiServiceInput<Extract<WorkflowApiRequest,{operation:WorkflowApiOperation}>>):Promise<WorkflowApiServiceResult>;pollUpload(input:WorkflowApiServiceInput<Extract<WorkflowApiRequest,{command:"poll-upload"}>>):Promise<WorkflowApiServiceResult>;pollGeneration(input:WorkflowApiServiceInput<Extract<WorkflowApiRequest,{command:"poll-generation"}>>):Promise<WorkflowApiServiceResult>;queryResult(input:WorkflowApiServiceInput<Extract<WorkflowApiRequest,{command:"result"}>>):Promise<WorkflowApiServiceResult>;cancel(input:WorkflowApiServiceInput<Extract<WorkflowApiRequest,{command:"cancel"}>>):Promise<WorkflowApiServiceResult>};
export function createReferenceWorkflowApiService(d:ReferenceWorkflowApiServiceDependencies):ReferenceWorkflowApiService{
 const preflight=(raw:WorkflowApiServiceInput<any>)=>{const request=validateRequest(raw?.request),principal=validatePrincipal(raw?.principal),context=validateContext(raw?.context);if(request.status!=="valid")return d.errorMapper.error(request.code);if(principal.status!=="valid")return d.errorMapper.error("unauthenticated");if(context.status!=="valid")return d.errorMapper.error("request-invalid");const command=("operation"in request.value?"start":request.value.command)as WorkflowApiCommand,size=classifyRequestSize(request.value,command,"operation"in request.value?request.value.operation:undefined);if(size==="too-large")return d.errorMapper.error("request-invalid",{statusCode:413});return{request:request.value,principal:principal.value,context:context.value,command} as const};
 const entryContext=(context:any,fingerprint:string,cancel=false):ReferenceWorkflowEntryContext=>({contextVersion:"1.0",baselineTime:context.baselineTime,requestRef:context.requestRef,operationRef:context.correlationRef,attempt:context.attempt,idempotencyKeyRef:`api-derived-${fingerprint}` as any,cancellationRequested:cancel} as any);
 const idem=async(command:WorkflowApiCommand,key:string,fingerprint:string,execute:()=>Promise<WorkflowApiServiceResult>)=>{const namespace=`api-${command}` as const,old=d.idempotencyStore.read(namespace,key,fingerprint);if(old.status==="found")return old.result;if(old.status==="conflict")return d.errorMapper.error("idempotency-conflict");const result=await execute();if(shouldPersistWorkflowApiResult(result))d.idempotencyStore.commit(namespace,key,fingerprint,result);return copy(result)};
 const authorizeReference=(principal:any,command:WorkflowApiCommand,reference:WorkflowReferenceDTO,baselineTime:string)=>{const resolved=d.referenceVault.resolve(reference);if(resolved.status!=="found")return{error:d.errorMapper.error("reference-unavailable")} as const;const projected=d.authProjector.project({principal,command,operation:resolved.ownership.operation,ownership:resolved.ownership});if(projected.status!=="authorized")return{error:d.errorMapper.error(projected.status==="unauthorized"?"unauthorized":projected.status==="unauthenticated"?"unauthenticated":"reference-unavailable")} as const;if(resolved.state!=="active")return{error:d.errorMapper.error("reference-unavailable")} as const;if(resolved.ownership.expiresAt&&baselineTime>=resolved.ownership.expiresAt)return{error:d.errorMapper.error("reference-expired")} as const;return{resolved,authorization:projected.authorization} as const};
 const map=(result:ReferenceWorkflowApiMappableResult,operation:WorkflowApiOperation,ownership:WorkflowReferenceOwnership,resultIdentity:string,isNew=false)=>{const mapped=d.dtoMapper.mapResult(result,operation,ownership,resultIdentity,isNew);return mapped.status==="mapped"?mapped.result:d.errorMapper.error("internal-error")};
 return{
  async start(raw){const p=preflight(raw);if("status"in p)return p;const request=p.request as any,operation=request.operation as WorkflowApiOperation,auth=d.authProjector.project({principal:p.principal,command:"start",operation});if(auth.status!=="authorized")return d.errorMapper.error(auth.status==="unauthenticated"?"unauthenticated":"unauthorized");const fingerprint=createSafeWorkflowApiRequestFingerprint("start",request,p.principal),ownership:WorkflowReferenceOwnership={tenantRef:p.principal.tenantRef,region:p.principal.region,operation,subjectRef:p.principal.subjectRef,deletionState:"active",legalHold:false};return idem("start",request.idempotencyKey,fingerprint,async()=>{const runtime=await d.runtimeProvider.getRuntime(),workflowInput={...copy(request.workflowInput),adapterInput:{...copy(request.workflowInput.adapterInput),capability:operation==="generate-vocal"?REFERENCE_VOCAL_CAPABILITY:operation==="generate-music"?REFERENCE_MUSIC_CAPABILITY:REFERENCE_MV_CAPABILITY},contractVersion:"1.0",operation,providerId:"reference-provider",providerApiVersion:"reference-api-v1",context:{contextVersion:"1.0",operationRef:p.context.correlationRef,baselineTime:p.context.baselineTime,attempt:p.context.attempt,scenario:d.scenarios?.[operation]??"success",idempotencyKeyRef:`api-derived-${fingerprint}`}} as ReferenceWorkflowInput;const result=operation==="generate-vocal"?await runReferenceVocalWorkflow(workflowInput as any,{asyncRuntime:runtime}):operation==="generate-music"?await runReferenceMusicWorkflow(workflowInput as any,{asyncRuntime:runtime}):await runReferenceMVWorkflow(workflowInput as any,{asyncRuntime:runtime});return map(result,operation,ownership,fingerprint,true)})},
  async pollUpload(raw){const p=preflight(raw);if("status"in p)return p;const request=p.request as any,a=authorizeReference(p.principal,"poll-upload",request.pendingReference,p.context.baselineTime);if(!("resolved"in a))return a.error;const resolved=a.resolved!;const fingerprint=createSafeWorkflowApiRequestFingerprint("poll-upload",request,p.principal,{operation:resolved.ownership.operation,attempt:p.context.attempt});return idem("poll-upload",request.idempotencyKey,fingerprint,async()=>map(await (await d.runtimeProvider.getRuntime()).entryPoints.pollUpload({entryVersion:"1.0",pendingReference:resolved.internal,context:entryContext(p.context,fingerprint),authorization:a.authorization} as any),resolved.ownership.operation,resolved.ownership,resolved.identity))},
  async pollGeneration(raw){const p=preflight(raw);if("status"in p)return p;const request=p.request as any,a=authorizeReference(p.principal,"poll-generation",request.generationReference,p.context.baselineTime);if(!("resolved"in a))return a.error;const resolved=a.resolved!;const fingerprint=createSafeWorkflowApiRequestFingerprint("poll-generation",request,p.principal,{operation:resolved.ownership.operation,attempt:p.context.attempt});return idem("poll-generation",request.idempotencyKey,fingerprint,async()=>map(await (await d.runtimeProvider.getRuntime()).entryPoints.pollGeneration({entryVersion:"1.0",jobReference:resolved.internal,context:entryContext(p.context,fingerprint),authorization:a.authorization} as any),resolved.ownership.operation,resolved.ownership,resolved.identity))},
  async queryResult(raw){const p=preflight(raw);if("status"in p)return p;const request=p.request as any,a=authorizeReference(p.principal,"result",request.reference,p.context.baselineTime);if(!("resolved"in a))return a.error;const resolved=a.resolved!;const fingerprint=createSafeWorkflowApiRequestFingerprint("result",request,p.principal,{operation:resolved.ownership.operation,attempt:p.context.attempt});return idem("result",request.idempotencyKey,fingerprint,async()=>{if(request.reference.kind==="workflow-result")return resolved.terminal?{status:"success",http:{statusCode:200,headers:SAFE_WORKFLOW_API_HEADERS},body:copy(resolved.terminal)}:d.errorMapper.error("reference-unavailable");if(!resolved.internal)return d.errorMapper.error("reference-unavailable");const found=await (await d.runtimeProvider.getRuntime()).entryPoints.getResult({queryVersion:"1.0",reference:resolved.internal,context:entryContext(p.context,fingerprint),authorization:a.authorization} as any);return found.status==="found"?map(found.result,resolved.ownership.operation,resolved.ownership,resolved.identity):d.errorMapper.error("reference-unavailable")})},
  async cancel(raw){
   const p=preflight(raw);if("status"in p)return p;
   const request=p.request as any,a=authorizeReference(p.principal,"cancel",request.reference,p.context.baselineTime);if(!("resolved"in a))return a.error;
   const resolved=a.resolved!,fingerprint=createSafeWorkflowApiRequestFingerprint("cancel",request,p.principal,{operation:resolved.ownership.operation,attempt:p.context.attempt});
   return idem("cancel",request.idempotencyKey,fingerprint,async()=>{
    if(request.reference.kind==="workflow-result")return resolved.terminal?{status:"success",http:{statusCode:200,headers:SAFE_WORKFLOW_API_HEADERS},body:copy(resolved.terminal)}:d.errorMapper.error("reference-unavailable");
    if(!resolved.internal)return d.errorMapper.error("reference-unavailable");
    const result=await (await d.runtimeProvider.getRuntime()).entryPoints.cancel({entryVersion:"1.0",reference:resolved.internal,context:entryContext(p.context,fingerprint,true),authorization:a.authorization} as any);
    return map(result,resolved.ownership.operation,resolved.ownership,resolved.identity);
   });
  }
 }}
export const projectWorkflowApiLogMetadata=(input:{command:WorkflowApiCommand;operation?:WorkflowApiOperation;result:WorkflowApiServiceResult;sizeClass:"small"|"medium"|"large"|"too-large"})=>Object.freeze({command:input.command,...(input.operation?{operation:input.operation}:{}),statusClass:input.result.status,httpClass:`${Math.floor(input.result.http.statusCode/100)}xx`,retryable:input.result.status==="error"?input.result.body.retryable:false,safeCode:input.result.status==="error"?input.result.body.code:undefined,requestSizeClass:input.sizeClass});
