import type { IngestionJournalCompareAndSetResultV2, IngestionJournalCreateResultV2, IngestionJournalReadResultV2, IngestionJournalV2, OutputIngestionJournalIdentityV2, OutputIngestionJournalRecordV2, OutputIngestionRecoveryRequiredV2 } from "./types";
import { deepCopy } from "./outputIngestionUtils";
import { referenceReplayEvidenceV2, type ReferencePersistenceScenarioV2 } from "./referencePersistenceAssetStoreV2";

export class ReferencePersistenceJournalV2 implements IngestionJournalV2{
 readonly #records=new Map<string,OutputIngestionJournalRecordV2>();constructor(private readonly scenario:ReferencePersistenceScenarioV2="normal"){}
 async createIfAbsent(record:OutputIngestionJournalRecordV2):Promise<IngestionJournalCreateResultV2>{if(this.scenario==="corrupted")return{status:"corrupted"};if(this.scenario==="unavailable")return{status:"unavailable",retryable:true};const key=record.identity.ingestionIdentityRef,old=this.#records.get(key);if(old){if(old.identity.semanticFingerprint!==record.identity.semanticFingerprint)return{status:"semantic-conflict"};if(!old.mutationIdentity)return{status:"corrupted"};return{status:"replayed",record:deepCopy(old),replayEvidence:referenceReplayEvidenceV2(old.mutationIdentity,"journal")}}this.#records.set(key,deepCopy(record));return{status:"created",record:deepCopy(record)}}
 async readAuthoritative(identity:OutputIngestionJournalIdentityV2):Promise<IngestionJournalReadResultV2>{if(this.scenario==="corrupted")return{status:"corrupted"};if(this.scenario==="unavailable")return{status:"unavailable",retryable:true};const record=this.#records.get(identity.ingestionIdentityRef);if(!record)return{status:"missing"};if(record.identity.semanticFingerprint!==identity.semanticFingerprint)return{status:"corrupted"};return{status:"found",record:deepCopy(record)}}
 async compareAndSet(input:Parameters<IngestionJournalV2["compareAndSet"]>[0]):Promise<IngestionJournalCompareAndSetResultV2>{if(this.scenario==="corrupted")return{status:"corrupted"};if(this.scenario==="unavailable")return{status:"unavailable",retryable:true};const current=this.#records.get(input.identity.ingestionIdentityRef);if(!current)return{status:"corrupted"};if(current.identity.semanticFingerprint!==input.identity.semanticFingerprint||input.nextRecord.identity.semanticFingerprint!==input.identity.semanticFingerprint)return{status:"semantic-conflict"};if(current.terminal)return{status:"terminal-preserved"};if(current.revision!==input.expectedRevision)return{status:"stale-revision"};if(!input.expectedPriorStages.includes(current.stage))return{status:"wrong-prior-stage"};if(input.nextRecord.revision!==current.revision+1||input.nextRecord.identity.ingestionIdentityRef!==current.identity.ingestionIdentityRef)return{status:"corrupted"};this.#records.set(input.identity.ingestionIdentityRef,deepCopy(input.nextRecord));return{status:"updated",record:deepCopy(input.nextRecord)}}
}

export function projectReferenceRecoveryRequiredV2(stage:OutputIngestionRecoveryRequiredV2["stage"],outcome:{status:string}):OutputIngestionRecoveryRequiredV2|undefined{return outcome.status==="outcome-unknown"?{status:"recovery-required",recoveryVersion:"2.0",stage,reason:"outcome-unknown",retryable:false}:outcome.status==="unavailable"?{status:"recovery-required",recoveryVersion:"2.0",stage,reason:"authoritative-lookup-unavailable",retryable:false}:undefined;}
