import type { OutputIngestionAuthoritativeLookupResultV2, OutputIngestionMutationIdentityV2, OutputIngestionProvenanceReceiptV2, ProvenanceStoreV2, ProvenanceWriteInputV2, ProvenanceWriteResultV2 } from "./types";
import { deepCopy } from "./outputIngestionUtils";
import { referenceReplayEvidenceV2, type ReferencePersistenceScenarioV2 } from "./referencePersistenceAssetStoreV2";

export class ReferencePersistenceProvenanceV2 implements ProvenanceStoreV2{
 readonly #receipts=new Map<string,OutputIngestionProvenanceReceiptV2>();constructor(private readonly scenario:ReferencePersistenceScenarioV2="normal"){}
 async write(input:ProvenanceWriteInputV2):Promise<ProvenanceWriteResultV2>{if(this.scenario==="corrupted")return{status:"corrupted",retryable:false};if(this.scenario==="unavailable")return{status:"unavailable",retryable:true};const old=this.#receipts.get(input.mutationIdentity.identityRef);if(old){if(old.mutationIdentity.semanticFingerprint!==input.mutationIdentity.semanticFingerprint)return{status:"semantic-conflict",retryable:false};return{status:"replayed",receipt:deepCopy(old),replayEvidence:referenceReplayEvidenceV2(old.mutationIdentity,"provenance")};}const receipt={receiptVersion:"2.0",mutationIdentity:deepCopy(input.mutationIdentity),evidenceRef:`[reference-v2-provenance-${input.mutationIdentity.identityRef}]`} as unknown as OutputIngestionProvenanceReceiptV2;this.#receipts.set(input.mutationIdentity.identityRef,deepCopy(receipt));if(this.scenario==="outcome-unknown-committed")return{status:"outcome-unknown",retryable:false,recoveryRequired:true};return{status:"written",receipt:deepCopy(receipt)}}
 async lookupAuthoritative(identity:OutputIngestionMutationIdentityV2):Promise<OutputIngestionAuthoritativeLookupResultV2<OutputIngestionProvenanceReceiptV2>>{if(this.scenario==="corrupted")return{status:"corrupted"};if(this.scenario==="unavailable")return{status:"unavailable",retryable:true};const receipt=this.#receipts.get(identity.identityRef);if(!receipt)return{status:"not-committed"};if(receipt.mutationIdentity.semanticFingerprint!==identity.semanticFingerprint)return{status:"semantic-conflict"};return{status:"committed",receipt:deepCopy(receipt),replayEvidence:referenceReplayEvidenceV2(identity,"provenance")}}
}
