import type { CleanupScheduleInputV2, CleanupScheduleResultV2, CleanupSchedulerV2, OutputIngestionAuthoritativeLookupResultV2, OutputIngestionCleanupReceiptV2, OutputIngestionMutationIdentityV2 } from "./types";
import { deepCopy } from "./outputIngestionUtils";
import { referenceReplayEvidenceV2, type ReferencePersistenceScenarioV2 } from "./referencePersistenceAssetStoreV2";

export class ReferencePersistenceCleanupV2 implements CleanupSchedulerV2{
 readonly #receipts=new Map<string,OutputIngestionCleanupReceiptV2>();constructor(private readonly scenario:ReferencePersistenceScenarioV2="normal"){}
 async schedule(input:CleanupScheduleInputV2):Promise<CleanupScheduleResultV2>{if(this.scenario==="corrupted")return{status:"corrupted",retryable:false};if(this.scenario==="unavailable")return{status:"unavailable",retryable:true};const old=this.#receipts.get(input.mutationIdentity.identityRef);if(old){if(old.mutationIdentity.semanticFingerprint!==input.mutationIdentity.semanticFingerprint)return{status:"semantic-conflict",retryable:false};return{status:"replayed",receipt:deepCopy(old),replayEvidence:referenceReplayEvidenceV2(old.mutationIdentity,"cleanup")};}const receipt={receiptVersion:"2.0",mutationIdentity:deepCopy(input.mutationIdentity),requestRef:`[reference-v2-cleanup-${input.mutationIdentity.identityRef}]`} as unknown as OutputIngestionCleanupReceiptV2;this.#receipts.set(input.mutationIdentity.identityRef,deepCopy(receipt));if(this.scenario==="outcome-unknown-committed")return{status:"outcome-unknown",retryable:false,recoveryRequired:true};return{status:"scheduled",receipt:deepCopy(receipt)}}
 async lookupAuthoritative(identity:OutputIngestionMutationIdentityV2):Promise<OutputIngestionAuthoritativeLookupResultV2<OutputIngestionCleanupReceiptV2>>{if(this.scenario==="corrupted")return{status:"corrupted"};if(this.scenario==="unavailable")return{status:"unavailable",retryable:true};const receipt=this.#receipts.get(identity.identityRef);if(!receipt)return{status:"not-committed"};if(receipt.mutationIdentity.semanticFingerprint!==identity.semanticFingerprint)return{status:"semantic-conflict"};return{status:"committed",receipt:deepCopy(receipt),replayEvidence:referenceReplayEvidenceV2(identity,"cleanup")}}
}
