import type { Sensitive, AssetAvailabilityStatus, AssetRetentionClass, AssetSensitivityClass, AssetRecord } from "@/lib/assets/types";
import type { AssetKind } from "@/lib/mvContracts";
import type { NormalizedGenerationResult } from "@/lib/providers/types";
import type { ProviderOperation } from "@/lib/providerClients/types";

export type GeneratedOutputRole = "primary" | "alternate" | "preview" | "stem";
export type ExpectedDuration = { targetSeconds: number; toleranceSeconds: number };
export type ExpectedDimensions = { width?: number; height?: number; minimumWidth?: number; minimumHeight?: number; maximumWidth?: number; maximumHeight?: number; aspectRatio?: string; aspectTolerance?: number };
export type ExpectedOutputRole = { role: GeneratedOutputRole; requirement: "required" | "optional" };
export type ExpectedOutputContract = { contractVersion: "1.0"; kind: AssetKind; requiredRoles: readonly GeneratedOutputRole[]; optionalRoles: readonly GeneratedOutputRole[]; allowedMimeTypes: readonly string[]; allowedCodecs?: readonly string[]; allowedContainers?: readonly string[]; maximumOutputCount: number; maximumSizeBytes: number; expectedDuration?: ExpectedDuration; expectedDimensions?: ExpectedDimensions; requireChecksum: boolean; requireDurationMetadata: boolean; requireDimensions: boolean };
export type OutputIngestionPolicy = { policyVersion: "1.0"; externalFetchAllowed: boolean; allowedProviderIds: readonly string[]; maximumDownloadBytes: number; requireHttps: boolean; redirectPolicy: "none" | "same-allowlisted-host"; retentionClass: AssetRetentionClass; sensitivityClass: AssetSensitivityClass; scanRequired: boolean; metadataStrippingRequired: boolean; sourceRegion?: string; destinationRegion?: string; deletionPending: boolean };
export type OutputIngestionContext = { contextVersion: "1.0"; operationRef: string; baselineTime: string; attempt: number; cancellation?: { stage: "none" | "before-fetch" | "during-fetch" | "before-store" | "before-registry" } };
export type OutputIngestionIdempotencyContext = { ingestionKeyRef: string };
export type OutputIngestionInput = { contractVersion: "1.0"; providerId: string; providerApiVersion: string; operation: ProviderOperation; generationResult: NormalizedGenerationResult; expectedOutput: ExpectedOutputContract; policy: OutputIngestionPolicy; context: OutputIngestionContext; idempotency?: OutputIngestionIdempotencyContext };
export type OutputIngestionPlanItem = { slotIndex: number; role: GeneratedOutputRole; requirement: "required" | "optional"; expectedKind: AssetKind; allowedMimeTypes: readonly string[]; allowedCodecs: readonly string[]; allowedContainers: readonly string[]; maximumSizeBytes: number; expectedDuration?: ExpectedDuration; expectedDimensions?: ExpectedDimensions; requireChecksum: boolean; requireDurationMetadata: boolean; requireDimensions: boolean };
export type OutputIngestionPlan = { planVersion: "1.0"; executorVersion: "reference-v1"; providerId: string; providerApiVersion: string; operation: ProviderOperation; items: readonly OutputIngestionPlanItem[]; policy: Omit<OutputIngestionPolicy,"allowedProviderIds">; context: OutputIngestionContext; idempotency?: OutputIngestionIdempotencyContext; warnings: readonly string[] };
export type ProviderOutputReferenceItem = { slotIndex: number; role: GeneratedOutputRole; providerOutputReference: string };
export type ProviderOutputReferenceBundle = Sensitive<{ bundleVersion: "1.0"; providerId: string; providerApiVersion: string; operation: ProviderOperation; items: readonly ProviderOutputReferenceItem[] }>;
export type OutputIngestionPlanStatus = "planned" | "invalid";
export type OutputIngestionPlanResult = { status: "planned"; plan: OutputIngestionPlan; references: ProviderOutputReferenceBundle; issues: [] } | { status: "invalid"; issues: OutputIngestionIssue[] };
export type ProviderOutputAccess = Sensitive<{ mode: "provider-reference"; reference: string }>;
export type OutputContentHandle = Sensitive<{ handleVersion: "1.0"; contentRef: string }>;
export type ProviderOutputMetadata = { mimeType?: string; fetchContentType?: string; sizeBytes?: number; contentLength?: number; providerChecksum?: string; durationSeconds?: number; width?: number; height?: number; codec?: string; container?: string; contentEncoding?: "identity"; sourceRegion?: string };
export type ProviderOutputFetchInput = { access: ProviderOutputAccess; maximumBytes: number; requireHttps: boolean; redirectPolicy: OutputIngestionPolicy["redirectPolicy"] };
export type ProviderOutputFetchResult = { status: "fetched"; content: OutputContentHandle; metadata: ProviderOutputMetadata } | { status: "failed"; error: NormalizedOutputIngestionError };
export type ContentInspectionResult = { status: "inspected"; actualSizeBytes: number; computedChecksum: string; detectedMimeType: string; corrupted: boolean; partial: boolean; metadata: ProviderOutputMetadata } | { status: "failed"; error: NormalizedOutputIngestionError };
export type ContentScanResult = { status: "passed" | "pending" | "quarantined" | "blocked" | "failed" };
export type ContentSanitizationResult = { status: "sanitized" | "unchanged"; content: OutputContentHandle } | { status: "failed" };
export type AssetStoreWriteResult = { status: "written"; locatorRef: string; storedBytes: number; checksum: string } | { status: "failed"; error: NormalizedOutputIngestionError };
export type AssetRegistryCreateResult = { status: "created"; record: AssetRecord } | { status: "failed"; error: NormalizedOutputIngestionError };
export type AssetProvenanceRecord = { provenanceVersion: "1.0"; sourceType: "provider-generation"; providerId: string; providerApiVersion: string; operation: ProviderOperation; outputRole: GeneratedOutputRole; restrictedProviderOutputReference?: Sensitive<string>; importedChecksum: string };
export type ImportedAssetReference = { assetId: string; kind: AssetKind; role: GeneratedOutputRole; mimeType: string; sizeBytes: number; checksum: string; availability: AssetAvailabilityStatus };
export type OutputIngestionStatus = "completed" | "partial" | "failed";
export type OutputIngestionReasonCode = "unsupported-contract-version"|"input-shape-invalid"|"generation-result-invalid"|"provider-mismatch"|"provider-api-version-mismatch"|"operation-mismatch"|"output-reference-invalid"|"duplicate-output-reference"|"required-output-missing"|"optional-output-failed"|"output-count-exceeded"|"output-role-invalid"|"output-fetch-failed"|"output-fetch-timeout"|"output-too-large"|"output-empty"|"mime-type-mismatch"|"codec-unsupported"|"checksum-mismatch"|"metadata-missing"|"duration-mismatch"|"dimensions-mismatch"|"aspect-ratio-mismatch"|"content-scan-pending"|"content-quarantined"|"content-blocked"|"storage-write-failed"|"registry-create-failed"|"provenance-write-failed"|"duplicate-content-reused"|"ingestion-cancelled"|"cleanup-required"|"idempotency-conflict";
export type OutputIngestionIssueClassification = "validation"|"policy"|"fetch"|"integrity"|"metadata"|"safety"|"storage"|"execution";
export type OutputIngestionIssue = { reasonCode: OutputIngestionReasonCode; classification: OutputIngestionIssueClassification; slotIndex?: number; role?: GeneratedOutputRole; kind?: AssetKind; retryable: boolean };
export type OutputIngestionAudit = { status: OutputIngestionStatus; expectedCount: number; receivedCount: number; fetchedCount: number; validatedCount: number; importedCount: number; reusedCount: number; failedCount: number; roles: readonly GeneratedOutputRole[]; mimeClasses: readonly ("audio"|"video"|"image"|"unknown")[]; reasonCodes: readonly OutputIngestionReasonCode[] };
export type OutputIngestionResult = { status:"completed"; requiredOutputsComplete:true; assets:ImportedAssetReference[]; audit:OutputIngestionAudit } | { status:"partial"; requiredOutputsComplete:boolean; assets:ImportedAssetReference[]; issues:OutputIngestionIssue[]; audit:OutputIngestionAudit } | { status:"failed"; requiredOutputsComplete:false; issues:OutputIngestionIssue[]; audit:OutputIngestionAudit };
export type OutputIngestionErrorCategory = "reference-invalid"|"reference-expired"|"fetch-failed"|"fetch-timeout"|"payload-too-large"|"mime-invalid"|"metadata-invalid"|"checksum-mismatch"|"content-corrupted"|"scan-failed"|"content-blocked"|"storage-failed"|"registry-failed"|"cancelled"|"unknown";
export type OutputIngestionRetryAdvice = { retryable: boolean; safeCode?: string };
export type NormalizedOutputIngestionError = OutputIngestionRetryAdvice & { category: OutputIngestionErrorCategory };
export type ProviderOutputFetcher={fetch(input:ProviderOutputFetchInput):Promise<ProviderOutputFetchResult>};
export type ContentInspector={inspect(content:OutputContentHandle):Promise<ContentInspectionResult>};
export type ContentScanner={scan(content:OutputContentHandle):Promise<ContentScanResult>};
export type MediaSanitizer={sanitize(content:OutputContentHandle):Promise<ContentSanitizationResult>};
export type AssetStoreWriter={write(input:{content:OutputContentHandle;checksum:string;sizeBytes:number;mimeType:string;policy:OutputIngestionPlan["policy"]}):Promise<AssetStoreWriteResult>};
export type ImportedAssetRegistry={create(input:{slotIndex:number;kind:AssetKind;mimeType:string;sizeBytes:number;checksum:string;metadata:ProviderOutputMetadata;availability:AssetAvailabilityStatus;locatorRef:string;policy:OutputIngestionPlan["policy"]}):Promise<AssetRegistryCreateResult>};
export type ProvenanceStore={write(record:AssetProvenanceRecord):Promise<{status:"written"|"failed"}>};
export type DuplicateAssetLookup={find(input:{checksum:string;sizeBytes:number;mimeType:string;policy:OutputIngestionPlan["policy"]}):Promise<AssetRecord|undefined>};
export type IngestionJournal={get(keyRef:string):Promise<{fingerprint:string;result:OutputIngestionResult}|undefined>;put(keyRef:string,value:{fingerprint:string;result:OutputIngestionResult}):Promise<void>};
export type CleanupScheduler={schedule(reason:OutputIngestionReasonCode,content?:OutputContentHandle):Promise<{status:"scheduled"|"failed"}>};
