import { CLIP_PLATFORM_PROFILE_VERSION, type ClipPlatformProfileV1, type ClipPlatformTargetV1 } from "./types";

const profile = (value: Omit<ClipPlatformProfileV1, "version">): ClipPlatformProfileV1 => Object.freeze({ ...value, version: CLIP_PLATFORM_PROFILE_VERSION, durationPolicy: Object.freeze(value.durationPolicy), qualityWeights: Object.freeze(value.qualityWeights), portfolioWeights: Object.freeze(value.portfolioWeights), hookPolicy: Object.freeze(value.hookPolicy), editingPolicy: Object.freeze(value.editingPolicy), reasonCodes: Object.freeze([...value.reasonCodes]) });
const genericEditing = { hookWindowSeconds: 10, maximumHookShiftSeconds: 5, removableGapSeconds: 0.6, preservedPauseSeconds: 0.4, maximumRemovedRatio: 0.2, minimumFinalDurationSeconds: 15 } as const;
export const CLIP_PLATFORM_PROFILES_V1: Readonly<Record<ClipPlatformTargetV1, ClipPlatformProfileV1>> = Object.freeze({
  "generic-short": profile({ target: "generic-short", durationPolicy: { minimumSeconds: 15, preferredSeconds: 30, maximumSeconds: 60 }, qualityWeights: { hookStrength: 0.18, storyCompleteness: 0.216, standaloneValue: 0.162, payoffStrength: 0.144, informationDensity: 0.108, boundaryQuality: 0.09, sourceContextRelevance: 0.1 }, portfolioWeights: { quality: 0.75, diversity: 0.25, sourceContext: 0 }, hookPolicy: { hookWindowSeconds: 10, maxStartShiftSeconds: 5, allowWeakLeadTrim: true, contextProtectionLevel: "strict" }, editingPolicy: genericEditing, reasonCodes: ["generic-compatible"] }),
  "youtube-shorts": profile({ target: "youtube-shorts", durationPolicy: { minimumSeconds: 15, preferredSeconds: 36, maximumSeconds: 60 }, qualityWeights: { hookStrength: 0.17, storyCompleteness: 0.236, standaloneValue: 0.174, payoffStrength: 0.15, informationDensity: 0.09, boundaryQuality: 0.08, sourceContextRelevance: 0.1 }, portfolioWeights: { quality: 0.78, diversity: 0.18, sourceContext: 0.04 }, hookPolicy: { hookWindowSeconds: 10, maxStartShiftSeconds: 5, allowWeakLeadTrim: true, contextProtectionLevel: "strict" }, editingPolicy: { ...genericEditing, removableGapSeconds: 0.65, preservedPauseSeconds: 0.45 }, reasonCodes: ["shorts-story-priority", "duration-profile-applied", "hook-profile-applied"] }),
  tiktok: profile({ target: "tiktok", durationPolicy: { minimumSeconds: 15, preferredSeconds: 25, maximumSeconds: 55 }, qualityWeights: { hookStrength: 0.22, storyCompleteness: 0.19, standaloneValue: 0.15, payoffStrength: 0.13, informationDensity: 0.14, boundaryQuality: 0.07, sourceContextRelevance: 0.1 }, portfolioWeights: { quality: 0.76, diversity: 0.2, sourceContext: 0.04 }, hookPolicy: { hookWindowSeconds: 8, maxStartShiftSeconds: 4, allowWeakLeadTrim: true, contextProtectionLevel: "strict" }, editingPolicy: { ...genericEditing, hookWindowSeconds: 8, maximumHookShiftSeconds: 4, removableGapSeconds: 0.55, preservedPauseSeconds: 0.35 }, reasonCodes: ["tiktok-hook-priority", "duration-profile-applied", "hook-profile-applied"] }),
  "instagram-reels": profile({ target: "instagram-reels", durationPolicy: { minimumSeconds: 15, preferredSeconds: 30, maximumSeconds: 60 }, qualityWeights: { hookStrength: 0.19, storyCompleteness: 0.21, standaloneValue: 0.16, payoffStrength: 0.16, informationDensity: 0.11, boundaryQuality: 0.07, sourceContextRelevance: 0.1 }, portfolioWeights: { quality: 0.76, diversity: 0.2, sourceContext: 0.04 }, hookPolicy: { hookWindowSeconds: 10, maxStartShiftSeconds: 5, allowWeakLeadTrim: true, contextProtectionLevel: "strict" }, editingPolicy: genericEditing, reasonCodes: ["reels-balanced-priority", "duration-profile-applied", "hook-profile-applied"] }),
});
export const resolveClipPlatformProfileV1 = (target: ClipPlatformTargetV1 = "generic-short") => CLIP_PLATFORM_PROFILES_V1[target];
