import type {
  MultiCutReplayPostgresqlStatementCatalog,
  MultiCutReplayPostgresqlStatementId,
} from "./types";

export const MULTI_CUT_REPLAY_POSTGRESQL_STATEMENT_IDS = Object.freeze([
  "resolve-new-reservation",
  "resolve-existing-replay",
  "lookup-authoritative-replay",
  "renew-processing-reservation",
  "complete-processing-replay",
  "fail-processing-replay",
  "release-processing-replay",
  "takeover-stale-processing-replay",
] as const satisfies readonly MultiCutReplayPostgresqlStatementId[]);

export const MULTI_CUT_REPLAY_POSTGRESQL_STATEMENT_CATALOG =
  Object.freeze({
    "resolve-new-reservation": Object.freeze({
      statementId: "resolve-new-reservation",
      capabilityOwner: "resolution",
      operationKind: "resolve-new",
      accessMode: "write",
      transactionRequirement: "required",
      mutationClassification: "reservation-create",
      commitUnknownStrategy: "authoritative-lookup",
      authoritativeFollowUpRequirement: "conditional",
      reconciliationRequirement: "none",
    }),
    "resolve-existing-replay": Object.freeze({
      statementId: "resolve-existing-replay",
      capabilityOwner: "resolution",
      operationKind: "resolve-existing",
      accessMode: "write",
      transactionRequirement: "required",
      mutationClassification: "reservation-create",
      commitUnknownStrategy: "authoritative-lookup",
      authoritativeFollowUpRequirement: "conditional",
      reconciliationRequirement: "none",
    }),
    "lookup-authoritative-replay": Object.freeze({
      statementId: "lookup-authoritative-replay",
      capabilityOwner: "recovery",
      operationKind: "lookup",
      accessMode: "read",
      transactionRequirement: "read-consistent",
      mutationClassification: "none",
      commitUnknownStrategy: "not-applicable",
      authoritativeFollowUpRequirement: "none",
      reconciliationRequirement: "none",
    }),
    "renew-processing-reservation": Object.freeze({
      statementId: "renew-processing-reservation",
      capabilityOwner: "lifecycle",
      operationKind: "renew",
      accessMode: "write",
      transactionRequirement: "required",
      mutationClassification: "reservation-refresh",
      commitUnknownStrategy: "reservation-reconciliation",
      authoritativeFollowUpRequirement: "conditional",
      reconciliationRequirement: "reservation-mutation",
    }),
    "complete-processing-replay": Object.freeze({
      statementId: "complete-processing-replay",
      capabilityOwner: "lifecycle",
      operationKind: "complete",
      accessMode: "write",
      transactionRequirement: "workflow-completion-transaction",
      mutationClassification: "terminal-transition",
      commitUnknownStrategy: "workflow-completion-recovery",
      authoritativeFollowUpRequirement: "conditional",
      reconciliationRequirement: "none",
    }),
    "fail-processing-replay": Object.freeze({
      statementId: "fail-processing-replay",
      capabilityOwner: "lifecycle",
      operationKind: "fail",
      accessMode: "write",
      transactionRequirement: "required",
      mutationClassification: "terminal-transition",
      commitUnknownStrategy: "authoritative-lookup",
      authoritativeFollowUpRequirement: "conditional",
      reconciliationRequirement: "none",
    }),
    "release-processing-replay": Object.freeze({
      statementId: "release-processing-replay",
      capabilityOwner: "lifecycle",
      operationKind: "release",
      accessMode: "write",
      transactionRequirement: "required",
      mutationClassification: "terminal-transition",
      commitUnknownStrategy: "authoritative-lookup",
      authoritativeFollowUpRequirement: "conditional",
      reconciliationRequirement: "none",
    }),
    "takeover-stale-processing-replay": Object.freeze({
      statementId: "takeover-stale-processing-replay",
      capabilityOwner: "recovery",
      operationKind: "takeover",
      accessMode: "write",
      transactionRequirement: "required",
      mutationClassification: "ownership-takeover",
      commitUnknownStrategy: "reservation-reconciliation",
      authoritativeFollowUpRequirement: "conditional",
      reconciliationRequirement: "reservation-mutation",
    }),
  } satisfies MultiCutReplayPostgresqlStatementCatalog);
