import type { WorkflowApiCommand,WorkflowApiErrorDTO,WorkflowApiIdempotencyKey,WorkflowApiPrincipal,WorkflowApiRequest,WorkflowApiRequestContext,WorkflowApiResultDTO,WorkflowReferenceDTO } from "./types";
export type SafeValidationResult<T>={status:"valid";value:T}|{status:"invalid";code:"request-invalid"|"request-version-unsupported"|"operation-unsupported"};
const forbidden=new Set(["__proto__","prototype","constructor"]),scheme=/^[a-z][a-z0-9+.-]*:/i,control=/[\u0000-\u001f\u007f]/;
export const isPlainObject=(v:unknown):v is Record<string,unknown>=>{if(!v||typeof v!=="object"||Array.isArray(v))return false;const p=Object.getPrototypeOf(v);return p===Object.prototype||p===null};
const keysExact=(v:Record<string,unknown>,allowed:readonly string[])=>Object.keys(v).every(k=>allowed.includes(k)&&!forbidden.has(k));
export const hasUnsafeStructure=(value:unknown,depth=0):boolean=>{if(depth>16)return true;if(Array.isArray(value))return value.length>500||value.some(v=>hasUnsafeStructure(v,depth+1));if(isPlainObject(value))return Object.keys(value).some(k=>forbidden.has(k))||Object.values(value).some(v=>hasUnsafeStructure(v,depth+1));return typeof value==="string"&&(value.startsWith("data:")||/;base64,/i.test(value))};
export const validOpaque=(v:unknown,max=128)=>typeof v==="string"&&v.length>0&&v.length<=max&&!scheme.test(v)&&!control.test(v)&&!/[\r\n]/.test(v);
export const validIdempotencyKey=(v:unknown):v is WorkflowApiIdempotencyKey=>typeof v==="string"&&v.length>=1&&v.length<=128&&/^[A-Za-z0-9._~-]+$/.test(v)&&!scheme.test(v);
const leap=(y:number)=>y%4===0&&(y%100!==0||y%400===0),days=(y:number,m:number)=>[31,leap(y)?29:28,31,30,31,30,31,31,30,31,30,31][m-1]??0;
export const validUtcMillis=(v:unknown)=>{if(typeof v!=="string")return false;const m=/^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})\.000Z$/.exec(v);if(!m)return false;const [,ys,ms,ds,hs,mins,ss]=m,y=+ys,mo=+ms,d=+ds;return y>=1&&mo>=1&&mo<=12&&d>=1&&d<=days(y,mo)&&+hs<=23&&+mins<=59&&+ss<=59};
export function validatePrincipal(raw:unknown):SafeValidationResult<WorkflowApiPrincipal>{if(!isPlainObject(raw)||!keysExact(raw,["principalVersion","actorType","subjectRef","tenantRef","region","permissions"])||raw.principalVersion!=="1.0"||!(raw.actorType==="user"||raw.actorType==="service")||!validOpaque(raw.subjectRef)||!validOpaque(raw.tenantRef)||!validOpaque(raw.region,64)||!Array.isArray(raw.permissions)||raw.permissions.length>16)return{status:"invalid",code:"request-invalid"};const allowed=new Set(["workflow:start","workflow:poll-upload","workflow:poll-generation","workflow:result","workflow:cancel"]),p=raw.permissions;if(p.some(x=>typeof x!=="string"||!allowed.has(x))||new Set(p).size!==p.length)return{status:"invalid",code:"request-invalid"};return{status:"valid",value:raw as WorkflowApiPrincipal}}
export function validateContext(raw:unknown):SafeValidationResult<WorkflowApiRequestContext>{if(!isPlainObject(raw)||!keysExact(raw,["contextVersion","baselineTime","requestRef","correlationRef","attempt"])||raw.contextVersion!=="1.0"||!validUtcMillis(raw.baselineTime)||!validOpaque(raw.requestRef)||!validOpaque(raw.correlationRef)||!Number.isSafeInteger(raw.attempt)||(raw.attempt as number)<1)return{status:"invalid",code:"request-invalid"};return{status:"valid",value:raw as WorkflowApiRequestContext}}
export function validateReference(raw:unknown,kind?:WorkflowReferenceDTO["kind"]):SafeValidationResult<WorkflowReferenceDTO>{if(!isPlainObject(raw)||!keysExact(raw,["referenceVersion","kind","reference"])||raw.referenceVersion!=="1.0"||!(["upload-pending","generation-job","workflow-result"] as unknown[]).includes(raw.kind)||kind&&raw.kind!==kind||!validOpaque(raw.reference))return{status:"invalid",code:"request-invalid"};return{status:"valid",value:raw as WorkflowReferenceDTO}}
const validOperation=(v:unknown)=>v==="generate-vocal"||v==="generate-music"||v==="generate-mv";
export function validateRequest(raw:unknown):SafeValidationResult<WorkflowApiRequest>{if(!isPlainObject(raw)||hasUnsafeStructure(raw))return{status:"invalid",code:"request-invalid"};if(raw.requestVersion!=="1.0")return{status:"invalid",code:"request-version-unsupported"};if("operation"in raw){if(!validOperation(raw.operation))return{status:"invalid",code:"operation-unsupported"};if(!keysExact(raw,["requestVersion","operation","workflowInput","idempotencyKey"])||!isPlainObject(raw.workflowInput)||raw.workflowInput.operation!==raw.operation||raw.workflowInput.contractVersion!=="1.0"||raw.operation==="generate-music"&&isPlainObject(raw.workflowInput.adapterInput)&&isPlainObject(raw.workflowInput.adapterInput.assets)&&"guideVocalAsset" in raw.workflowInput.adapterInput.assets||!validIdempotencyKey(raw.idempotencyKey))return{status:"invalid",code:"request-invalid"};return{status:"valid",value:raw as WorkflowApiRequest}}if(typeof raw.command!=="string"||!(["poll-upload","poll-generation","result","cancel"] as string[]).includes(raw.command)||!validIdempotencyKey(raw.idempotencyKey))return{status:"invalid",code:"request-invalid"};const refKey=raw.command==="poll-upload"?"pendingReference":raw.command==="poll-generation"?"generationReference":"reference",allowed=["requestVersion","command",refKey,"idempotencyKey"];if(!keysExact(raw,allowed)||validateReference(raw[refKey],raw.command==="poll-upload"?"upload-pending":raw.command==="poll-generation"?"generation-job":undefined).status!=="valid")return{status:"invalid",code:"request-invalid"};return{status:"valid",value:raw as WorkflowApiRequest}}
export const classifyRequestSize=(raw:unknown,command:WorkflowApiCommand,operation?:string):"small"|"medium"|"large"|"too-large"=>{let n=Infinity;try{n=new TextEncoder().encode(JSON.stringify(raw)).length}catch{}const max=command==="start"?(operation==="generate-mv"?524288:131072):8192;return n>max?"too-large":n<=8192?"small":n<=131072?"medium":"large"};
export function validateResultDto(raw:unknown):SafeValidationResult<WorkflowApiResultDTO>{if(!isPlainObject(raw)||raw.responseVersion!=="1.0"||!validOperation(raw.operation)||typeof raw.status!=="string")return{status:"invalid",code:"request-invalid"};const common=["responseVersion","status","operation"],byStatus:Record<string,string[]>={completed:[...common,"assets","resultReference"],degraded:[...common,"assets","resultReference"],partial:[...common,"assets","resultReference"],"pending-upload":[...common,"reference","retryAdvice","progress"],"pending-generation":[...common,"reference","retryAdvice","progress"],failed:[...common,"error","resultReference"],cancelled:[...common,"resultReference"]};const allowed=byStatus[raw.status];if(!allowed||!keysExact(raw,allowed))return{status:"invalid",code:"request-invalid"};if(["completed","degraded","partial"].includes(raw.status)){if(!Array.isArray(raw.assets))return{status:"invalid",code:"request-invalid"};const assetIds:string[]=[];for(const asset of raw.assets){if(!isPlainObject(asset)||!keysExact(asset,["assetVersion","assetId","kind","role","mimeType"])||asset.assetVersion!=="1.0"||typeof asset.assetId!=="string"||!validOpaque(asset.assetId)||!validOpaque(asset.kind,64)||!validOpaque(asset.role,64)||!validOpaque(asset.mimeType,128))return{status:"invalid",code:"request-invalid"};assetIds.push(asset.assetId)}if(new Set(assetIds).size!==raw.assets.length)return{status:"invalid",code:"request-invalid"}}if(["completed","degraded","partial","failed","cancelled"].includes(raw.status)&&validateReference(raw.resultReference,"workflow-result").status!=="valid")return{status:"invalid",code:"request-invalid"};if(raw.status==="pending-upload"&&validateReference(raw.reference,"upload-pending").status!=="valid"||raw.status==="pending-generation"&&validateReference(raw.reference,"generation-job").status!=="valid")return{status:"invalid",code:"request-invalid"};return{status:"valid",value:raw as WorkflowApiResultDTO}}
export function validateErrorDto(raw:unknown):SafeValidationResult<WorkflowApiErrorDTO>{if(!isPlainObject(raw)||!keysExact(raw,["errorVersion","code","message","retryable","retryAfterClass"])||raw.errorVersion!=="1.0"||typeof raw.code!=="string"||typeof raw.message!=="string"||typeof raw.retryable!=="boolean")return{status:"invalid",code:"request-invalid"};return{status:"valid",value:raw as WorkflowApiErrorDTO}}
export const copy=<T>(v:T):T=>JSON.parse(JSON.stringify(v));
