import type { AssetRequirement, AssetUsage, ResolvedAsset, Sensitive } from "@/lib/assets/types";
import type { ProviderOperation } from "@/lib/providerClients/types";
import type { ProviderNativeAssetHandle, ProviderUploadSession } from "@/lib/providerUploads/types";

export type ProviderUploadPendingReference = Sensitive<{ referenceVersion: "1.0"; pendingRef: string; kind: "provider-upload" }>;
export type PendingUploadStoreKey = Sensitive<{ keyVersion: "1.0"; internalKey: string }>;
export type PendingUploadReferenceRecord = Sensitive<{ recordVersion: "1.0"; referenceDigest: string; storeKeyRef: PendingUploadStoreKey; status: "active" | "expired" | "revoked" | "deleted"; expiresAt: string }>;
export type PendingUploadSourceAsset = Omit<ResolvedAsset,"access"|"usage"|"requirement">;
export type PendingUploadItemState = Sensitive<{ itemVersion: "1.0"; itemIndex: number; usage: AssetUsage; requirement: AssetRequirement; session: ProviderUploadSession; itemStatus: "accepted" | "processing" | "completed" | "failed" | "cancelled" | "expired" | "blocked"; sourceAsset: PendingUploadSourceAsset; completedAsset?: ResolvedAsset }>;
export type PendingUploadState = Sensitive<{ stateVersion: "1.0"; planFingerprint: string; providerId: string; providerApiVersion: string; operation: ProviderOperation; pendingItems: readonly PendingUploadItemState[]; completedAssets: readonly ResolvedAsset[]; attempt: number; revision: number; stateStatus: "pending" | "ready" | "failed" | "cancelled" | "expired" | "blocked"; stateExpiresAt: string }>;
export type PendingUploadStateRevision = { revision: number };
export type PendingUploadPollContext = { contextVersion: "1.0"; baselineTime: string; attempt: number; correlationRef: string; idempotencyKeyRef?: string; cancellationRequested: boolean };
export type PendingUploadPollInput = { contractVersion: "1.0"; pendingReference: ProviderUploadPendingReference; context: PendingUploadPollContext };
export type PendingUploadRetryAdvice = { retryable: boolean; retryAfterSeconds?: number; safeCode: string };
export type PendingUploadPollAudit = { status: "pending" | "completed" | "failed" | "cancelled" | "expired" | "blocked"; providerId: string; operation: ProviderOperation; attempt: number; reasonCodes: readonly PendingUploadResumeReasonCode[] };
export type ProviderUploadPollAttemptResult =
  | { status: "pending"; progress?: number; retryAdvice: PendingUploadRetryAdvice; audit: PendingUploadPollAudit }
  | { status: "completed"; nativeAsset: Sensitive<ProviderNativeAssetHandle>; retryAdvice: PendingUploadRetryAdvice; audit: PendingUploadPollAudit }
  | { status: "failed"; error: NormalizedPendingUploadResumeError; retryAdvice: PendingUploadRetryAdvice; audit: PendingUploadPollAudit }
  | { status: "cancelled" | "expired" | "blocked"; audit: PendingUploadPollAudit };
export type PendingUploadResumeDecisionStatus = "remain-pending" | "ready-to-resume" | "degraded-ready" | "failed" | "cancelled" | "expired" | "blocked" | "conflict";
export type PendingUploadResumeReasonCode = "unsupported-contract-version" | "input-shape-invalid" | "pending-reference-invalid" | "pending-reference-not-found" | "pending-reference-expired" | "pending-reference-revoked" | "pending-state-invalid" | "pending-state-version-mismatch" | "pending-state-conflict" | "pending-state-expired" | "provider-mismatch" | "provider-api-version-mismatch" | "operation-mismatch" | "poll-not-supported" | "upload-still-pending" | "upload-completed" | "upload-failed" | "upload-cancelled" | "upload-session-expired" | "native-handle-invalid" | "native-handle-expired" | "required-upload-failed" | "optional-upload-omitted" | "resume-ready" | "resume-degraded" | "resume-conflict" | "store-read-failed" | "store-write-failed" | "cleanup-required" | "reconciliation-required" | "policy-blocked" | "region-mismatch";
export type PendingUploadResumeErrorCategory = "invalid-request" | "not-found" | "expired" | "revoked" | "authentication" | "authorization" | "rate-limit" | "timeout" | "network" | "provider-unavailable" | "job-not-found" | "processing-failed" | "state-conflict" | "policy-blocked" | "cancelled" | "unknown";
export type NormalizedPendingUploadResumeError = { category: PendingUploadResumeErrorCategory; retryable: boolean; safeCode?: string };
export type PendingUploadResumeIssue = { reasonCode: PendingUploadResumeReasonCode; classification: "invalid" | "missing" | "expired" | "conflict" | "failed" | "cancelled" | "blocked" | "internal"; retryable: boolean; itemIndex?: number };
export type PendingUploadResumeAudit = { auditVersion: "1.0"; status: PendingUploadResumeDecisionStatus | "pending" | "ready" | "degraded"; providerId: string; operation: ProviderOperation; attempt: number; pendingItemCount: number; completedItemCount: number; failedItemCount: number; omittedItemCount: number; reasonCodes: readonly PendingUploadResumeReasonCode[] };
export type PendingUploadResumeDecisionInput = { state: PendingUploadState; itemIndex?: number; pollResult?: ProviderUploadPollAttemptResult; baselineTime: string; materializerCapability: { acceptedAccessModes: readonly string[]; nativeHandleMinimumLifetimeSeconds: number; optionalOmissionAllowed: boolean }; binding: { providerId: string; providerApiVersion: string; operation: ProviderOperation }; expectedRevision?: number };
export type PendingUploadResumeDecision = { decisionVersion: "1.0"; status: PendingUploadResumeDecisionStatus; retryAdvice?: PendingUploadRetryAdvice; issues: readonly PendingUploadResumeIssue[]; audit: PendingUploadResumeAudit };
export type PendingUploadStateTransition = Sensitive<{ nextState: PendingUploadState; assets?: Sensitive<ResolvedAsset[]> }>;
export type PendingUploadResumeResult = { status: "ready" | "degraded"; assets: Sensitive<ResolvedAsset[]>; audit: PendingUploadResumeAudit } | { status: "pending"; pendingReference: ProviderUploadPendingReference; retryAdvice: PendingUploadRetryAdvice; audit: PendingUploadResumeAudit } | { status: "failed" | "cancelled" | "expired" | "blocked" | "conflict"; issues: readonly PendingUploadResumeIssue[]; audit: PendingUploadResumeAudit };
export type CreatePendingUploadInput = { state: PendingUploadState; referenceExpiresAt: string };
export type PendingUploadStoreResult = { status: "created"; reference: ProviderUploadPendingReference } | { status: "found"; state: PendingUploadState; revision: number } | { status: "updated"; state: PendingUploadState; revision: number } | { status: "missing" | "expired" | "revoked" | "deleted" | "conflict" | "failed" };
export type PendingUploadStore = { create(input: CreatePendingUploadInput): Promise<PendingUploadStoreResult>; readByReference(reference: ProviderUploadPendingReference, baselineTime: string): Promise<PendingUploadStoreResult>; compareAndSet(reference: ProviderUploadPendingReference, expectedRevision: number, state: PendingUploadState): Promise<PendingUploadStoreResult>; markExpired(reference: ProviderUploadPendingReference, expectedRevision: number): Promise<PendingUploadStoreResult>; revoke(reference: ProviderUploadPendingReference): Promise<PendingUploadStoreResult>; delete(reference: ProviderUploadPendingReference): Promise<PendingUploadStoreResult> };
export type PendingUploadReferenceResolverResult = { status: "resolved"; storeKey: PendingUploadStoreKey } | { status: "invalid" | "missing" | "expired" | "revoked" | "deleted" };
export type PendingUploadReferenceResolver = { resolvePendingReference(reference: unknown, baselineTime: string): PendingUploadReferenceResolverResult };
export type ProviderUploadPollClientInput = { session: ProviderUploadSession; sourceAsset: PendingUploadSourceAsset; providerId: string; providerApiVersion: string; operation: ProviderOperation; baselineTime: string; attempt: number };
export type ProviderUploadPollClient = { poll(input: ProviderUploadPollClientInput): Promise<ProviderUploadPollAttemptResult> };
export type PendingUploadResumeExecutor = { execute(input: PendingUploadPollInput): Promise<PendingUploadResumeResult> };
export type PendingUploadDescriptor = { descriptorVersion: "1.0"; resolverId: string; storeId: string; pollClientId: string; resumeExecutorId: string; supportedOperations: readonly ProviderOperation[]; contractVersion: "1.0"; availability: "available" | "disabled" };
