import assert from "node:assert/strict";
import test from "node:test";
import type { AssetStoreWriteInputV2, OutputContentHandle, OutputIngestionJournalIdentityV2, OutputIngestionJournalRecordV2, OutputIngestionMutationClassV2, OutputIngestionMutationIdentityV2 } from "../../lib/outputIngestion/types";
import { ReferencePersistenceAssetStoreV2 } from "../../lib/outputIngestion/referencePersistenceAssetStoreV2";
import { ReferencePersistenceRegistryV2 } from "../../lib/outputIngestion/referencePersistenceRegistryV2";
import { ReferencePersistenceJournalV2, projectReferenceRecoveryRequiredV2 } from "../../lib/outputIngestion/referencePersistenceJournalV2";
import { ReferencePersistenceProvenanceV2 } from "../../lib/outputIngestion/referencePersistenceProvenanceV2";
import { ReferencePersistenceCleanupV2 } from "../../lib/outputIngestion/referencePersistenceCleanupV2";

const identity=(mutationClass:OutputIngestionMutationClassV2,identityRef="identity",semanticFingerprint="fingerprint")=>({identityVersion:"2.0",mutationClass,identityRef,semanticFingerprint} as OutputIngestionMutationIdentityV2);
const journalIdentity=(fingerprint="journal-fingerprint")=>({identityVersion:"2.0",ingestionIdentityRef:"journal-identity",semanticFingerprint:fingerprint} as OutputIngestionJournalIdentityV2);
const policy={policyVersion:"1.0",externalFetchAllowed:true,maximumDownloadBytes:1000,requireHttps:true,redirectPolicy:"none",retentionClass:"project",sensitivityClass:"standard",scanRequired:true,metadataStrippingRequired:true,deletionPending:false} as const;
const storeInput=(mutationIdentity=identity("asset-store-write")):AssetStoreWriteInputV2=>({capabilityVersion:"2.0",mutationIdentity,content:{handleVersion:"1.0",contentRef:"content"} as OutputContentHandle,checksum:"1".repeat(64),sizeBytes:100,mimeType:"audio/wav",policy});
const journalRecord=(stage:OutputIngestionJournalRecordV2["stage"]="planned",revision=1,terminal=false,fingerprint="journal-fingerprint")=>({recordVersion:"2.0",identity:journalIdentity(fingerprint),slotIndex:0,role:"primary",stage,attempt:1,revision,terminal,mutationIdentity:identity("asset-store-write","journal-mutation",fingerprint)} as OutputIngestionJournalRecordV2);

test("asset store writes, replays, conflicts and isolates copies",async()=>{const store=new ReferencePersistenceAssetStoreV2(),input=storeInput();const written=await store.write(input);assert.equal(written.status,"written");const replay=await store.write(input);assert.equal(replay.status,"replayed");if(replay.status==="replayed"){assert.equal(replay.replayEvidence.semanticFingerprint,"fingerprint");replay.receipt.locatorRef="changed"}const lookup=await store.lookupAuthoritative(input.mutationIdentity);assert.equal(lookup.status,"committed");if(lookup.status==="committed")assert.notEqual(lookup.receipt.locatorRef,"changed");assert.equal((await store.write(storeInput(identity("asset-store-write","identity","different")))).status,"semantic-conflict")});

test("unknown committed outcome requires recovery and authoritative lookup",async()=>{const store=new ReferencePersistenceAssetStoreV2("outcome-unknown-committed"),input=storeInput();const result=await store.write(input);assert.deepEqual(result,{status:"outcome-unknown",retryable:false,recoveryRequired:true});assert.deepEqual(projectReferenceRecoveryRequiredV2("store",result),{status:"recovery-required",recoveryVersion:"2.0",stage:"store",reason:"outcome-unknown",retryable:false});assert.equal((await store.lookupAuthoritative(input.mutationIdentity)).status,"committed");assert.equal((await store.write(input)).status,"replayed")});

test("registry, provenance and cleanup persist and replay authoritative evidence",async()=>{const store=new ReferencePersistenceAssetStoreV2(),stored=await store.write(storeInput());assert.equal(stored.status,"written");if(stored.status!=="written")return;const registry=new ReferencePersistenceRegistryV2(),registryIdentity=identity("asset-registry-create","registry"),createInput={capabilityVersion:"2.0" as const,mutationIdentity:registryIdentity,slotIndex:0,kind:"audio" as const,mimeType:"audio/wav",sizeBytes:100,checksum:"1".repeat(64),metadata:{durationSeconds:10,codec:"pcm"},availability:"available" as const,storageReceipt:stored.receipt,policy};const created=await registry.create(createInput);assert.equal(created.status,"created");assert.equal((await registry.create(createInput)).status,"replayed");assert.equal((await registry.lookupAuthoritative(registryIdentity)).status,"committed");if(created.status!=="created")return;const provenance=new ReferencePersistenceProvenanceV2(),provenanceIdentity=identity("provenance-write","provenance");const provenanceInput={capabilityVersion:"2.0" as const,mutationIdentity:provenanceIdentity,record:{provenanceVersion:"1.0" as const,sourceType:"provider-generation" as const,providerId:"provider",providerApiVersion:"v1",operation:"generate-music" as const,outputRole:"primary" as const,importedChecksum:"1".repeat(64)},registryReceipt:created.receipt};assert.equal((await provenance.write(provenanceInput)).status,"written");assert.equal((await provenance.write(provenanceInput)).status,"replayed");assert.equal((await provenance.lookupAuthoritative(provenanceIdentity)).status,"committed");const cleanup=new ReferencePersistenceCleanupV2(),cleanupIdentity=identity("cleanup-schedule","cleanup"),cleanupInput={capabilityVersion:"2.0" as const,mutationIdentity:cleanupIdentity,reason:"cleanup-required" as const,storageReceipt:stored.receipt,registryReceipt:created.receipt};assert.equal((await cleanup.schedule(cleanupInput)).status,"scheduled");assert.equal((await cleanup.schedule(cleanupInput)).status,"replayed");assert.equal((await cleanup.lookupAuthoritative(cleanupIdentity)).status,"committed")});

test("journal provides create, replay, CAS guards and terminal preservation",async()=>{const journal=new ReferencePersistenceJournalV2(),created=await journal.createIfAbsent(journalRecord());assert.equal(created.status,"created");assert.equal((await journal.createIfAbsent(journalRecord())).status,"replayed");assert.equal((await journal.createIfAbsent(journalRecord("planned",1,false,"different"))).status,"semantic-conflict");const updated=await journal.compareAndSet({identity:journalIdentity(),expectedRevision:1,expectedPriorStages:["planned"],nextRecord:journalRecord("content-validated",2)});assert.equal(updated.status,"updated");assert.equal((await journal.compareAndSet({identity:journalIdentity(),expectedRevision:1,expectedPriorStages:["content-validated"],nextRecord:journalRecord("stored",3)})).status,"stale-revision");const terminal=await journal.compareAndSet({identity:journalIdentity(),expectedRevision:2,expectedPriorStages:["content-validated"],nextRecord:journalRecord("completed",3,true)});assert.equal(terminal.status,"updated");assert.equal((await journal.compareAndSet({identity:journalIdentity(),expectedRevision:3,expectedPriorStages:["completed"],nextRecord:journalRecord("failed",4,true)})).status,"terminal-preserved");const read=await journal.readAuthoritative(journalIdentity());assert.equal(read.status,"found");if(read.status==="found"){(read.record as {stage:string}).stage="changed"}assert.equal((await journal.readAuthoritative(journalIdentity())).status,"found")});

test("corruption and unavailable simulations are safe and deterministic",async()=>{const corrupted=new ReferencePersistenceAssetStoreV2("corrupted"),unavailable=new ReferencePersistenceJournalV2("unavailable");assert.deepEqual(await corrupted.write(storeInput()),{status:"corrupted",retryable:false});assert.deepEqual(await corrupted.lookupAuthoritative(identity("asset-store-write")),{status:"corrupted"});const read=await unavailable.readAuthoritative(journalIdentity());assert.deepEqual(read,{status:"unavailable",retryable:true});assert.deepEqual(projectReferenceRecoveryRequiredV2("registry",read),{status:"recovery-required",recoveryVersion:"2.0",stage:"registry",reason:"authoritative-lookup-unavailable",retryable:false})});
