import assert from "node:assert/strict";
import test from "node:test";
import { buildOutputIngestionPlan } from "../../lib/outputIngestion/outputIngestionPlan";
import { ReferenceContentInspector } from "../../lib/outputIngestion/referenceContentInspector";
import { ReferenceOutputFetcher } from "../../lib/outputIngestion/referenceOutputFetcher";
import { ReferenceRegistry } from "../../lib/outputIngestion/referenceRegistry";
import { ReferenceSanitizer, ReferenceScanner } from "../../lib/outputIngestion/referenceScanner";
import { ReferencePersistenceAssetStoreV2 } from "../../lib/outputIngestion/referencePersistenceAssetStoreV2";
import { ReferencePersistenceRegistryV2 } from "../../lib/outputIngestion/referencePersistenceRegistryV2";
import { ReferencePersistenceJournalV2 } from "../../lib/outputIngestion/referencePersistenceJournalV2";
import { ReferencePersistenceProvenanceV2 } from "../../lib/outputIngestion/referencePersistenceProvenanceV2";
import { ReferencePersistenceCleanupV2 } from "../../lib/outputIngestion/referencePersistenceCleanupV2";
import { ReferenceOutputIngestionExecutor, type ReferenceOutputIngestionDependencies } from "../../lib/outputIngestion/referenceOutputIngestion";
import type { AssetStoreWriterV2, CleanupSchedulerV2, IngestionJournalV2, OutputIngestionInput, ProvenanceStoreV2, ProviderOutputFetcher } from "../../lib/outputIngestion/types";

function input(optional=false):OutputIngestionInput{return{contractVersion:"1.0",providerId:"reference-provider",providerApiVersion:"v1",operation:"generate-music",generationResult:{resultSchemaVersion:"1.0",status:"completed",providerId:"reference-provider",adapterId:"reference",adapterVersion:"1.0",outputs:[{assetId:"ref-vocal",kind:"audio",role:"primary"},...(optional?[{assetId:"ref-music",kind:"audio" as const,role:"stem" as const}]:[])],warnings:[]},expectedOutput:{contractVersion:"1.0",kind:"audio",requiredRoles:["primary"],optionalRoles:["stem"],allowedMimeTypes:["audio/wav","audio/mpeg"],allowedCodecs:["pcm","mp3"],allowedContainers:["wav","mp3"],maximumOutputCount:2,maximumSizeBytes:200_000,requireChecksum:true,requireDurationMetadata:true,requireDimensions:false},policy:{policyVersion:"1.0",externalFetchAllowed:true,allowedProviderIds:["reference-provider"],maximumDownloadBytes:200_000,requireHttps:true,redirectPolicy:"none",retentionClass:"project",sensitivityClass:"standard",scanRequired:true,metadataStrippingRequired:true,deletionPending:false},context:{contextVersion:"1.0",operationRef:"operation",baselineTime:"2026-07-22T00:00:00.000Z",attempt:1,cancellation:{stage:"none"}},idempotency:{ingestionKeyRef:"ingestion-key"}}}
function planned(value:OutputIngestionInput){const result=buildOutputIngestionPlan(value);assert.equal(result.status,"planned");if(result.status!=="planned")throw new Error("safe fixture failure");return result;}
function composition(overrides:Partial<ReferenceOutputIngestionDependencies>={}){const dependencies:ReferenceOutputIngestionDependencies={fetcher:new ReferenceOutputFetcher(),inspector:new ReferenceContentInspector(),scanner:new ReferenceScanner(),sanitizer:new ReferenceSanitizer(),duplicateLookup:new ReferenceRegistry(),store:new ReferencePersistenceAssetStoreV2(),registry:new ReferencePersistenceRegistryV2(),journal:new ReferencePersistenceJournalV2(),provenance:new ReferencePersistenceProvenanceV2(),cleanup:new ReferencePersistenceCleanupV2(),...overrides};return new ReferenceOutputIngestionExecutor(dependencies)}

test("completes required and optional outputs in deterministic order",async()=>{const value=planned(input(true)),result=await composition().execute(value.plan,value.references);assert.equal(result.status,"completed");if(result.status!=="completed")return;assert.deepEqual(result.assets.map(asset=>asset.role),["primary","stem"]);assert.deepEqual(result.audit.reasonCodes,[]);assert.equal(result.requiredOutputsComplete,true);assert.throws(()=>{(value.plan.context as {operationRef:string}).operationRef="changed"})});

test("optional failure is partial and required failure is failed",async()=>{const base=new ReferenceOutputFetcher(),failing:ProviderOutputFetcher={async fetch(value){const reference=(value.access as {reference:string}).reference;return reference==="ref-music"?{status:"failed",error:{category:"fetch-timeout",retryable:true}}:base.fetch(value)}};const optional=planned(input(true)),partial=await composition({fetcher:failing}).execute(optional.plan,optional.references);assert.equal(partial.status,"partial");if(partial.status==="partial"){assert.equal(partial.requiredOutputsComplete,true);assert.deepEqual(partial.audit.reasonCodes,["output-fetch-timeout"])}const requiredInput=input();requiredInput.generationResult.outputs[0].assetId="ref-timeout";const required=planned(requiredInput),failed=await composition().execute(required.plan,required.references);assert.equal(failed.status,"failed")});

test("store and registry unknown committed outcomes recover authoritatively",async()=>{for(const overrides of [{store:new ReferencePersistenceAssetStoreV2("outcome-unknown-committed")},{registry:new ReferencePersistenceRegistryV2("outcome-unknown-committed")}]){const value=planned(input()),result=await composition(overrides).execute(value.plan,value.references);assert.equal(result.status,"completed")}});

test("unresolved unknown stops with recovery-required and no retry loop",async()=>{let writes=0,lookups=0;const base=new ReferencePersistenceAssetStoreV2("outcome-unknown-committed"),store:AssetStoreWriterV2={async write(value){writes++;return base.write(value)},async lookupAuthoritative(){lookups++;return{status:"unavailable",retryable:true}}};const value=planned(input()),result=await composition({store}).execute(value.plan,value.references);assert.deepEqual(result,{status:"recovery-required",recoveryVersion:"2.0",stage:"store",reason:"authoritative-lookup-unavailable",retryable:false});assert.equal(writes,1);assert.equal(lookups,1)});

test("provenance unknown uses one authoritative lookup and continues",async()=>{let writes=0,lookups=0;const base=new ReferencePersistenceProvenanceV2("outcome-unknown-committed"),provenance:ProvenanceStoreV2={async write(value){writes++;return base.write(value)},async lookupAuthoritative(value){lookups++;return base.lookupAuthoritative(value)}};const value=planned(input()),result=await composition({provenance}).execute(value.plan,value.references);assert.equal(result.status,"completed");assert.equal(writes,1);assert.equal(lookups,1)});

test("cleanup unknown with unavailable lookup projects recovery-required",async()=>{let schedules=0,lookups=0;const base=new ReferencePersistenceCleanupV2("outcome-unknown-committed"),cleanup:CleanupSchedulerV2={async schedule(value){schedules++;return base.schedule(value)},async lookupAuthoritative(){lookups++;return{status:"unavailable",retryable:true}}};const raw=input();raw.context.cancellation={stage:"before-registry"};const value=planned(raw),result=await composition({cleanup}).execute(value.plan,value.references);assert.deepEqual(result,{status:"recovery-required",recoveryVersion:"2.0",stage:"cleanup",reason:"authoritative-lookup-unavailable",retryable:false});assert.equal(schedules,1);assert.equal(lookups,1)});

test("journal replay returns terminal result without repeating capabilities",async()=>{let fetches=0;const base=new ReferenceOutputFetcher(),fetcher:ProviderOutputFetcher={async fetch(value){fetches++;return base.fetch(value)}},journal=new ReferencePersistenceJournalV2(),value=planned(input()),executor=composition({fetcher,journal});const first=await executor.execute(value.plan,value.references),afterFirst=fetches,replay=await executor.execute(value.plan,value.references);assert.deepEqual(replay,first);assert.equal(fetches,afterFirst)});

test("journal CAS conflict classes stop safely",async()=>{for(const conflict of ["stale-revision","wrong-prior-stage","terminal-preserved"] as const){const base=new ReferencePersistenceJournalV2();let calls=0;const journal:IngestionJournalV2={createIfAbsent:value=>base.createIfAbsent(value),readAuthoritative:value=>base.readAuthoritative(value),async compareAndSet(value){calls++;if(calls===1)return{status:conflict};return base.compareAndSet(value)}};const value=planned(input()),result=await composition({journal}).execute(value.plan,value.references);assert.equal(result.status,"failed");assert.doesNotMatch(JSON.stringify(result),/ingestion-key|ref-vocal|reference-v2/)}});

test("semantic conflict, corruption and unavailable are safe failures",async()=>{for(const store of [new ReferencePersistenceAssetStoreV2("corrupted"),new ReferencePersistenceAssetStoreV2("unavailable")]){const value=planned(input()),result=await composition({store}).execute(value.plan,value.references);assert.equal(result.status,"failed");assert.doesNotMatch(JSON.stringify(result),/locator|receipt|credential|stack|ref-vocal/)}});

test("cancellation stages stop subsequent persistence effects",async()=>{for(const stage of ["before-fetch","before-store","before-registry"] as const){let writes=0;const base=new ReferencePersistenceAssetStoreV2(),store:AssetStoreWriterV2={async write(value){writes++;return base.write(value)},lookupAuthoritative:value=>base.lookupAuthoritative(value)};const raw=input();raw.context.cancellation={stage};const value=planned(raw),result=await composition({store}).execute(value.plan,value.references);assert.equal(result.status,"failed");if(stage==="before-fetch"||stage==="before-store")assert.equal(writes,0);else assert.equal(writes,1)}});
