import assert from "node:assert/strict";
import test from "node:test";
import { withPostgreSqlTestEnvironment } from "../../lib/postgresqlTestEnvironment";
import { PostgreSQLConnectionPoolAdapter } from "../../lib/server/productionWorkflowRuntime/postgresqlDriver";
import { createDurableWorkflowTransactionSessionV3CompleteLifecycle, type DurableWorkflowDatabaseCapability, type DurableWorkflowTransactionContext } from "../../lib/server/productionWorkflowRuntime/durableTransaction";
import { createWorkflowCompletionTransitionRequest } from "../../lib/server/workflowCompletionState";
import { createWorkflowCompletionAtomicMutationOwnerV1, type WorkflowCompletionAtomicOwnerDependenciesV1, type WorkflowCompletionAtomicOwnerInputV1 } from "../../lib/server/workflowCompletionAtomicMutationOwner";

const stages = ["final-result", "workflow-completion-state", "result-reference", "replay-completion", "outbox"] as const;
const column = { "final-result": "final_result", "workflow-completion-state": "workflow_state", "result-reference": "result_reference", "replay-completion": "replay_completion", outbox: "workflow_outbox" } as const;
const identity = (namespace: string, protectedValue: string) => Object.freeze({ identityVersion: "1.0" as const, namespace, protectedValue });
const replayIdentity = (name: string) => Object.freeze({ identityVersion: "2.0" as const, protectedScope: Object.freeze({ scopeVersion: "1.0" as const, replayNamespace: "multi-cut", tenant: Object.freeze({ identityVersion: "1.0" as const, protectedTenantIdentity: `tenant:${name}` }), operationIdentity: `operation:${name}` }), resolvedIdentity: Object.freeze({ identityVersion: "1.0" as const, keyIdentity: `key:${name}`, requestFingerprintIdentity: `fingerprint:${name}` }) });

function ownerInput(name: string): WorkflowCompletionAtomicOwnerInputV1 {
  const workflow = identity("workflow-completion", name); const attempt = identity("logical-attempt", `attempt:${name}`); const resultReference = Object.freeze({ referenceVersion: "1.0" as const, resultReferenceIdentity: `result:${name}` }); const replay = replayIdentity(name); const operation = identity("operation", `operation:${name}`); const outbox = identity("outbox", `outbox:${name}`); const finalResult = identity("final-result", `final:${name}`); const completedAt = "2026-08-09T00:00:00.000Z";
  const consistency = Object.freeze({ workflowIdentity: workflow, protectedScopeIdentity: `scope:${name}`, logicalAttemptIdentity: attempt, completionTimestamp: completedAt, resultReference, replayIdentity: replay, operationIdentity: operation, outboxIdentity: outbox, commitIntentIdentity: finalResult, completionRevisionEvidence: "1" });
  return Object.freeze({ inputVersion: "1.0", consistency, componentConsistency: Object.freeze({ "final-result": consistency, "workflow-completion-state": consistency, "result-reference": consistency, "replay-completion": consistency, outbox: consistency }), stageInputs: Object.freeze({ "final-result": name, "workflow-completion-state": name, "result-reference": name, "replay-completion": name, outbox: name }), commitIntent: Object.freeze({ intentVersion: "1.0", workflowIdentity: workflow, replayIdentity: replay, completionOperationIdentity: operation, resultReference, resultReferenceVersion: "1.0", expectedPreCommitRevision: "0", expectedPostCommitRevision: "1", expectedOwnershipEvidence: Object.freeze({ evidenceVersion: "1.0", reservation: Object.freeze({ reservationVersion: "1.0", reservationIdentity: `reservation:${name}` }), expectedRevision: Object.freeze({ revisionVersion: "1.0", expectedRevision: "0" }), fencing: Object.freeze({ fencingVersion: "1.0", fencingToken: "1" }), lease: Object.freeze({ leaseVersion: "1.0", leaseIdentity: `lease:${name}` }), leaseExpiresAt: "2026-08-09T00:01:00.000Z", reservationAttempt: 1 }), terminalMetadata: Object.freeze({ metadataVersion: "1.0", completedAt, completionClassification: "workflow-completed" }), outboxEventIdentity: outbox, workflowFinalResultIdentity: finalResult, workflowFinalResultFingerprint: identity("fingerprint", `final:${name}`), logicalAttemptIdentity: attempt }) });
}

test("Atomic Owner commits all five components together and rolls every partial failure back", async () => {
  await withPostgreSqlTestEnvironment(async (environment) => {
    assert.equal(environment.flyway.migrate.succeeded, true); assert.equal(environment.flyway.validate.succeeded, true);
    await environment.pool.query("CREATE TABLE workflow.workflow_completion_atomicity_fixture (fixture_id text PRIMARY KEY, final_result boolean NOT NULL DEFAULT false, workflow_state boolean NOT NULL DEFAULT false, result_reference boolean NOT NULL DEFAULT false, replay_completion boolean NOT NULL DEFAULT false, workflow_outbox boolean NOT NULL DEFAULT false)");
    const names = ["success", "final-failure", "state-failure", "reference-failure", "replay-failure", "outbox-failure", "stale", "terminal"];
    for (const name of names) { await environment.pool.query("INSERT INTO workflow.workflow_completion_atomicity_fixture (fixture_id) VALUES ($1)", [name]); await environment.pool.query("INSERT INTO workflow.workflow_completion_states (workflow_identity_version,workflow_identity_namespace,workflow_identity_value,state,revision) VALUES ('1.0','workflow-completion',$1,'eligible-for-completion',0)", [name]); }
    await environment.pool.query("UPDATE workflow.workflow_completion_states SET state='completed',revision=1,logical_attempt_identity_version='1.0',logical_attempt_identity_namespace='logical-attempt',logical_attempt_identity_value='attempt:terminal',completion_timestamp='2026-08-09T00:00:00.000Z',result_reference_version='1.0',result_reference_identity='result:terminal' WHERE workflow_identity_value='terminal'");
    await environment.pool.query("UPDATE workflow.workflow_completion_states SET state='completed',revision=1,logical_attempt_identity_version='1.0',logical_attempt_identity_namespace='logical-attempt',logical_attempt_identity_value='attempt:other',completion_timestamp='2026-08-09T00:00:00.000Z',result_reference_version='1.0',result_reference_identity='result:other' WHERE workflow_identity_value='stale'");
    const pool = new PostgreSQLConnectionPoolAdapter({ ...environment.connection, maxConnections: 4, connectionTimeoutMs: 5_000, idleTimeoutMs: 5_000, queryTimeoutMs: 5_000, applicationName: "atomic-owner-integration", tls: { mode: "disabled" } }); assert.equal(await pool.start(), "ready");
    const counts = () => ({ final: 0, state: 0, reference: 0, replay: 0, outbox: 0, commit: 0, rollback: 0, release: 0, discard: 0 });
    const run = async (name: string, failAt?: (typeof stages)[number]) => {
      const invocation = counts(); const checkedOut = await pool.checkout(); if ("status" in checkedOut) throw new Error("checkout-failed"); const tx = await checkedOut.begin(); if ("status" in tx) throw new Error("begin-failed");
      const database: DurableWorkflowDatabaseCapability = Object.freeze({ capabilityVersion: "1.0", execute: async () => Object.freeze({ status: "success", rows: Object.freeze([]), rowCount: 0 }) }); const context: DurableWorkflowTransactionContext = Object.freeze({ contextVersion: "2.0", scope: "opaque-production-durable-transaction-scope", startedAt: "2026-08-09T00:00:00.000Z", deadlineMonotonicMilliseconds: 100, externalIoAllowed: false, database, state: () => "active", registerAfterCommit: () => "registered" });
      const base = createDurableWorkflowTransactionSessionV3CompleteLifecycle(Object.freeze({ constructionVersion: "3.0", transactionConnection: tx, transactionContextV2: context, transactionOwnerEvidence: Object.freeze({ evidenceVersion: "1.0", transactionOwner: "workflow-owner", transactionState: "active" }) }));
      const session = Object.freeze({ ...base, commitV2: async () => { invocation.commit += 1; return base.commitV2(); }, rollbackV2: async () => { invocation.rollback += 1; return base.rollbackV2(); }, release: () => { invocation.release += 1; return base.release(); }, discard: () => { invocation.discard += 1; return base.discard(); } });
      const update = async (stage: (typeof stages)[number]) => { invocation[stage === "final-result" ? "final" : stage === "workflow-completion-state" ? "state" : stage === "result-reference" ? "reference" : stage === "replay-completion" ? "replay" : "outbox"] += 1; if (failAt === stage) return Object.freeze({ resultVersion: "1.0" as const, status: "not-committed" as const, classification: "deterministic-injected-failure", lookupRequired: true, queryConnectionDisposition: "safe-to-reuse" as const }); const result = await session.contextV3.sameSessionQuery.executeQuery(Object.freeze({ statementId: `atomic-owner.${stage}`, text: `UPDATE workflow.workflow_completion_atomicity_fixture SET ${column[stage]}=true WHERE fixture_id=$1 RETURNING fixture_id`, values: Object.freeze([Object.freeze({ kind: "string" as const, value: name })]), expectedResult: "many" })); if (result.status !== "success") return Object.freeze({ resultVersion: "1.0" as const, status: "execution-failure" as const, classification: "query", issue: "query-failure", safeReason: "atomic-owner-query-failed", retryable: false, queryConnectionDisposition: "unknown" as const }); return Object.freeze({ resultVersion: "1.0" as const, status: "success" as const, classification: "one-row" }); };
      const built = createWorkflowCompletionTransitionRequest({ workflowIdentity: identity("workflow-completion", name), logicalAttemptIdentity: identity("logical-attempt", `attempt:${name}`), expectedRevision: "0", completionTimestamp: "2026-08-09T00:00:00.000Z", resultReference: Object.freeze({ referenceVersion: "1.0", resultReferenceIdentity: `result:${name}` }) }); if (built.status !== "valid") throw new Error("invalid-state-request");
      const dependencies: WorkflowCompletionAtomicOwnerDependenciesV1 = Object.freeze({ dependencyVersion: "1.0", acquireSession: async () => session, executeFinalResult: () => update("final-result"), executeWorkflowState: async () => { invocation.state += 1; if (failAt === "workflow-completion-state") return Object.freeze({ resultVersion: "1.0", status: "not-committed", classification: "deterministic-injected-failure", lookupRequired: true, queryConnectionDisposition: "safe-to-reuse" }); const state = await session.workflowCompletionState.transition(built.request); if (state.status !== "transitioned") return Object.freeze({ resultVersion: "1.0", status: "not-committed", classification: state.status, lookupRequired: true, queryConnectionDisposition: "safe-to-reuse" }); const marker = await update("workflow-completion-state"); invocation.state -= 1; return marker; }, executeResultReference: () => update("result-reference"), executeReplayCompletion: () => update("replay-completion"), executeOutbox: async () => { const result = await update("outbox"); if (result.status === "success") { const before = await environment.pool.query("SELECT final_result,workflow_state,result_reference,replay_completion,workflow_outbox FROM workflow.workflow_completion_atomicity_fixture WHERE fixture_id=$1", [name]); assert.deepEqual(before.rows[0], { final_result: false, workflow_state: false, result_reference: false, replay_completion: false, workflow_outbox: false }); } return result; } });
      const result = await createWorkflowCompletionAtomicMutationOwnerV1(dependencies).execute(ownerInput(name)); return { result, invocation };
    };
    const success = await run("success"); assert.equal(success.result.status, "committed", JSON.stringify(success.result)); assert.deepEqual(success.invocation, { final: 1, state: 1, reference: 1, replay: 1, outbox: 1, commit: 1, rollback: 0, release: 1, discard: 0 });
    const committed = await environment.pool.query("SELECT final_result,workflow_state,result_reference,replay_completion,workflow_outbox FROM workflow.workflow_completion_atomicity_fixture WHERE fixture_id='success'"); assert.deepEqual(committed.rows[0], { final_result: true, workflow_state: true, result_reference: true, replay_completion: true, workflow_outbox: true });
    for (const [name, stage] of [["final-failure", "final-result"], ["state-failure", "workflow-completion-state"], ["reference-failure", "result-reference"], ["replay-failure", "replay-completion"], ["outbox-failure", "outbox"]] as const) { const failed = await run(name, stage); assert.equal(failed.result.status, "not-committed"); assert.equal(failed.invocation.commit, 0); assert.equal(failed.invocation.rollback, 1); const snapshot = await environment.pool.query("SELECT final_result,workflow_state,result_reference,replay_completion,workflow_outbox FROM workflow.workflow_completion_atomicity_fixture WHERE fixture_id=$1", [name]); assert.deepEqual(snapshot.rows[0], { final_result: false, workflow_state: false, result_reference: false, replay_completion: false, workflow_outbox: false }); const state = await environment.pool.query("SELECT state,revision::text revision FROM workflow.workflow_completion_states WHERE workflow_identity_value=$1", [name]); assert.deepEqual(state.rows[0], { state: "eligible-for-completion", revision: "0" }); }
    const stale = await run("stale"); assert.equal(stale.result.status, "not-committed"); assert.equal(stale.invocation.commit, 0); const terminal = await run("terminal"); assert.equal(terminal.result.status, "not-committed"); assert.equal(terminal.invocation.commit, 0);
    assert.equal((await environment.pool.query("SELECT count(*)::int count FROM workflow.workflow_completion_atomicity_fixture WHERE final_result OR workflow_state OR result_reference OR replay_completion OR workflow_outbox")).rows[0]?.count, 1);
    assert.equal(await pool.close(), "closed"); await environment.pool.query("DROP TABLE workflow.workflow_completion_atomicity_fixture");
  });
});
