import type { AssetResolutionExecutionResult, AssetUsage, ResolvedAsset, ResolvedAssetAccess } from "@/lib/assets/types";
import type { AssetFieldMapping, MaterializedAssetValue, ProviderMaterializationProfile, RequestMaterializationAudit, RequestMaterializationInput, RequestMaterializationIssue, RequestMaterializationReasonCode } from "./types";
type ResolvedAssetIndex = ReadonlyMap<string, ReadonlyMap<AssetUsage, ResolvedAsset>>;

export const deepCopy = <T>(value: T): T => JSON.parse(JSON.stringify(value)) as T;
export const deepFreeze = <T>(value: T): T => { if(value&&typeof value==="object"){Object.freeze(value);Object.values(value as Record<string,unknown>).forEach(deepFreeze);}return value; };
export const isObject = (value:unknown):value is Record<string,unknown>=>typeof value==="object"&&value!==null&&!Array.isArray(value);
export function isSafeDataTree(value:unknown):boolean{const seen=new Set<object>();const visit=(candidate:unknown):boolean=>{if(candidate===null||typeof candidate==="string"||typeof candidate==="boolean"||candidate===undefined)return true;if(typeof candidate==="number")return Number.isFinite(candidate);if(typeof candidate!=="object")return false;if(seen.has(candidate))return false;seen.add(candidate);try{const prototype=Object.getPrototypeOf(candidate);if(prototype!==Object.prototype&&prototype!==Array.prototype&&prototype!==null)return false;for(const key of Reflect.ownKeys(candidate)){if(typeof key!=="string"||key==="__proto__"||key==="prototype"||key==="constructor")return false;const descriptor=Object.getOwnPropertyDescriptor(candidate,key);if(!descriptor||descriptor.get||descriptor.set||!("value" in descriptor)||!visit(descriptor.value))return false;}return true;}catch{return false;}finally{seen.delete(candidate);}};return visit(value);}
export const isPositiveInteger=(value:unknown):value is number=>typeof value==="number"&&Number.isFinite(value)&&Number.isInteger(value)&&value>0;
export const isSafeAssetId=(value:unknown):value is string=>typeof value==="string"&&value.length>0&&value.length<=256&&!/^https?:\/\//i.test(value)&&!/[\r\n]/.test(value);
export const unique=<T>(values:readonly T[]):T[]=>values.filter((v,i)=>values.indexOf(v)===i);
export const issue=(reasonCode:RequestMaterializationReasonCode,classification:RequestMaterializationIssue["classification"],mappingIndex?:number,usage?:AssetUsage,kind?:RequestMaterializationIssue["kind"]):RequestMaterializationIssue=>({reasonCode,classification,...(mappingIndex===undefined?{}:{mappingIndex}),...(usage?{usage}:{}),...(kind?{kind}:{})});

export function parseIsoEpochMilliseconds(value:unknown):number|undefined{if(typeof value!=="string")return undefined;const m=/^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})\.(\d{3})Z$/.exec(value);if(!m)return undefined;const y=+m[1],mo=+m[2],d=+m[3],h=+m[4],mi=+m[5],s=+m[6],ms=+m[7];const leap=y%4===0&&(y%100!==0||y%400===0),dim=[31,leap?29:28,31,30,31,30,31,31,30,31,30,31];if(mo<1||mo>12||d<1||d>dim[mo-1]||h>23||mi>59||s>59)return undefined;const ay=y-(mo<=2?1:0),era=Math.floor(ay/400),yoe=ay-era*400,mp=mo+(mo>2?-3:9),doy=Math.floor((153*mp+2)/5)+d-1,doe=yoe*365+Math.floor(yoe/4)-Math.floor(yoe/100)+doy,days=era*146097+doe-719468;return (days*86400+h*3600+mi*60+s)*1000+ms;}

export function validateProfile(profile:unknown):profile is ProviderMaterializationProfile{if(!isObject(profile)||profile.profileVersion!=="1.0"||profile.materializerVersion!=="reference-v1"||typeof profile.providerId!=="string"||!profile.providerId||typeof profile.providerApiVersion!=="string"||!profile.providerApiVersion||typeof profile.operation!=="string"||!isPositiveInteger(profile.minimumAssetLifetimeSeconds)||!Array.isArray(profile.mappings))return false;const ids=new Set<string>();for(const raw of profile.mappings){if(!isObject(raw)||typeof raw.mappingId!=="string"||!raw.mappingId||ids.has(raw.mappingId)||typeof raw.sourceSlot!=="string"||!raw.sourceSlot||(raw.requirement!=="required"&&raw.requirement!=="optional")||(raw.cardinality!=="single"&&raw.cardinality!=="multiple")||!Array.isArray(raw.allowedAccessModes)||raw.allowedAccessModes.length===0||!Array.isArray(raw.allowedKinds)||raw.allowedKinds.length===0||(raw.maximumCount!==undefined&&!isPositiveInteger(raw.maximumCount))||(raw.requirement==="required"&&raw.omissionBehavior!==undefined))return false;ids.add(raw.mappingId);}return true;}

export function buildResolvedAssetIndex(result:AssetResolutionExecutionResult):{index?:ResolvedAssetIndex;duplicate?:ResolvedAsset;invalid?:ResolvedAsset}{if(result.status!=="resolved"&&result.status!=="degraded")return{};const outer=new Map<string,Map<AssetUsage,ResolvedAsset>>();for(const asset of result.assets){if(!asset||!asset.assetRef||!isSafeAssetId(asset.assetRef.assetId)||!isValidResolvedAccess(asset.access))return{invalid:asset};let inner=outer.get(asset.assetRef.assetId);if(!inner){inner=new Map();outer.set(asset.assetRef.assetId,inner);}if(inner.has(asset.usage))return{duplicate:asset};inner.set(asset.usage,asset);}return{index:outer};}
export const findByUsage=(index:ResolvedAssetIndex,assetId:string,usage:AssetUsage):ResolvedAsset|undefined=>index.get(assetId)?.get(usage);
export function findUniqueByAllowedUsage(index:ResolvedAssetIndex,assetId:string,usages:readonly AssetUsage[]):{asset?:ResolvedAsset;ambiguous:boolean}{const inner=index.get(assetId);if(!inner)return{ambiguous:false};const matches=usages.map(u=>inner.get(u)).filter((v):v is ResolvedAsset=>Boolean(v));return{asset:matches.length===1?matches[0]:undefined,ambiguous:matches.length>1};}

export function convertAccess(access:ResolvedAssetAccess):MaterializedAssetValue{if(access.mode==="signed-url")return{mode:"signed-url",url:access.url,expiresAt:access.expiresAt};if(access.mode==="provider-upload")return{mode:"provider-upload",uploadSourceToken:access.uploadSourceToken,expiresAt:access.expiresAt};if(access.mode==="provider-native-asset")return{mode:"provider-native-asset",providerAssetHandle:access.handle,...(access.expiresAt?{expiresAt:access.expiresAt}:{})};return{mode:"internal-stream",streamToken:access.streamToken,expiresAt:access.expiresAt};}
export function isValidResolvedAccess(value:unknown):value is ResolvedAssetAccess{if(!isObject(value))return false;if(value.mode==="signed-url")return typeof value.url==="string"&&value.url.length>0&&typeof value.expiresAt==="string";if(value.mode==="provider-upload")return typeof value.uploadSourceToken==="string"&&value.uploadSourceToken.length>0&&typeof value.expiresAt==="string";if(value.mode==="provider-native-asset")return typeof value.handle==="string"&&value.handle.length>0&&(value.expiresAt===undefined||typeof value.expiresAt==="string");if(value.mode==="internal-stream")return typeof value.streamToken==="string"&&value.streamToken.length>0&&typeof value.expiresAt==="string";return false;}
export function validateResolvedAsset(asset:ResolvedAsset,mapping:AssetFieldMapping,baselineMs:number,minimumSeconds:number,mappingIndex:number):{value?:MaterializedAssetValue;expiry?:string;issue?:RequestMaterializationIssue}{const usages=Array.isArray(mapping.usage)?mapping.usage:[mapping.usage];if(!usages.includes(asset.usage))return{issue:issue("asset-usage-mismatch","mapping",mappingIndex,asset.usage,asset.assetRef.kind)};if(asset.requirement!==mapping.requirement)return{issue:issue("requirement-mismatch","mapping",mappingIndex,asset.usage,asset.assetRef.kind)};if(!mapping.allowedKinds.includes(asset.assetRef.kind))return{issue:issue("asset-kind-mismatch","mapping",mappingIndex,asset.usage,asset.assetRef.kind)};if(!mapping.allowedAccessModes.includes(asset.access.mode))return{issue:issue("access-mode-unsupported","mapping",mappingIndex,asset.usage,asset.assetRef.kind)};const expiry="expiresAt" in asset.access?asset.access.expiresAt:undefined;if(asset.access.mode==="provider-native-asset"&&!expiry&&mapping.allowMissingExpiryForNative)return{value:convertAccess(asset.access)};if(!expiry)return{issue:issue("asset-access-expired","expiry",mappingIndex,asset.usage,asset.assetRef.kind)};const expiryMs=parseIsoEpochMilliseconds(expiry);if(expiryMs===undefined)return{issue:issue("asset-access-expired","expiry",mappingIndex,asset.usage,asset.assetRef.kind)};const remaining=expiryMs-baselineMs;if(remaining<=0)return{issue:issue("asset-access-expired","expiry",mappingIndex,asset.usage,asset.assetRef.kind)};if(remaining<Math.max(minimumSeconds,120)*1000)return{issue:issue("asset-access-lifetime-insufficient","expiry",mappingIndex,asset.usage,asset.assetRef.kind)};return{value:convertAccess(asset.access),expiry};}

export function audit(profileVersion:"1.0",status:"materialized"|"failed",required:number,optional:number,materialized:number,omitted:number,modes:readonly ResolvedAssetAccess["mode"][],reasons:readonly RequestMaterializationReasonCode[]):RequestMaterializationAudit{return{status,requiredReferenceCount:required,optionalReferenceCount:optional,materializedCount:materialized,omittedCount:omitted,accessModes:unique(modes),reasonCodes:unique(reasons),profileVersion};}

export function validateCommonInput(input:unknown,operation:string):{input?:RequestMaterializationInput<unknown>;baselineMs?:number;index?:ResolvedAssetIndex;issue?:RequestMaterializationIssue}{if(!isObject(input))return{issue:issue("input-shape-invalid","validation")};if(input.contractVersion!=="1.0")return{issue:issue("unsupported-contract-version","validation")};if(typeof input.providerId!=="string"||input.providerId!=="reference-provider")return{issue:issue("provider-mismatch","validation")};if(input.providerApiVersion!=="reference-api-v1")return{issue:issue("provider-api-version-mismatch","validation")};if(input.operation!==operation)return{issue:issue("operation-mismatch","validation")};if(!isObject(input.adapterRequest)||!isSafeDataTree(input.adapterRequest))return{issue:issue("adapter-request-invalid","validation")};if(!isObject(input.resolvedAssets))return{issue:issue("resolution-result-invalid","resolution")};const result=input.resolvedAssets as AssetResolutionExecutionResult;if(result.status!=="resolved"&&result.status!=="degraded")return{issue:issue("resolution-not-complete","resolution")};if(!Array.isArray(result.assets))return{issue:issue("resolution-result-invalid","resolution")};if(!validateProfile(input.profile))return{issue:issue(isObject(input.profile)&&input.profile.profileVersion!=="1.0"?"unsupported-profile-version":"profile-invalid","validation")};const profile=input.profile as ProviderMaterializationProfile;if(profile.providerId!==input.providerId||profile.providerApiVersion!==input.providerApiVersion||profile.operation!==input.operation)return{issue:issue("profile-invalid","validation")};if(!isObject(input.context)||input.context.contextVersion!=="1.0")return{issue:issue("context-invalid","validation")};const baselineMs=parseIsoEpochMilliseconds(input.context.baselineTime);if(baselineMs===undefined)return{issue:issue("context-invalid","validation")};const indexed=buildResolvedAssetIndex(result);if(indexed.duplicate)return{issue:issue("duplicate-resolved-asset","resolution",undefined,indexed.duplicate.usage,indexed.duplicate.assetRef.kind)};if(!indexed.index)return{issue:issue("resolution-result-invalid","resolution")};return{input:input as unknown as RequestMaterializationInput<unknown>,baselineMs,index:indexed.index};}
