import type { ResolvedAssetAccess } from "@/lib/assets/types";
import type {
  MaterializedProviderRequest,
  ReferenceMusicRequest,
} from "@/lib/providerRequests/types";
import { audit, deepCopy, deepFreeze, findByUsage, isObject, isSafeAssetId, parseIsoEpochMilliseconds, validateCommonInput, validateResolvedAsset } from "./materializerUtils";
import { REFERENCE_MATERIALIZER_PROVIDER_API_VERSION, REFERENCE_MATERIALIZER_PROVIDER_ID, referenceMusicMaterializationProfile } from "./referenceProfiles";
import type { ReferenceMusicMaterializedBody, ReferenceMusicSlot, RequestMaterializationInput, RequestMaterializationReasonCode, RequestMaterializationResult, RequestMaterializer } from "./types";

export const referenceMusicMaterializer:RequestMaterializer<ReferenceMusicRequest,ReferenceMusicMaterializedBody,ReferenceMusicSlot>=deepFreeze({
  materializerId:"reference-music-materializer-v1",materializerVersion:"reference-v1",providerId:REFERENCE_MATERIALIZER_PROVIDER_ID,providerApiVersion:REFERENCE_MATERIALIZER_PROVIDER_API_VERSION,operation:"generate-music",
  materialize(raw:RequestMaterializationInput<ReferenceMusicRequest,ReferenceMusicSlot>):RequestMaterializationResult<ReferenceMusicMaterializedBody>{
    const c=validateCommonInput(raw,"generate-music");if(c.issue)return{status:"failed",issues:[c.issue],audit:audit("1.0","failed",0,0,0,0,[],[c.issue.reasonCode])};const input=c.input!,request=input.adapterRequest as ReferenceMusicRequest;
    if(request.requestSchemaVersion!=="1.0"||typeof request.durationSeconds!=="number"||!Number.isFinite(request.durationSeconds)||request.durationSeconds<=0||(request.outputFormat!=="wav"&&request.outputFormat!=="mp3")||request.outputMode!=="mix"||!(["none","instrumental","use-lyrics"] as const).includes(request.lyricsMode)||!isObject(request.tempo)||!isObject(request.performance)||!Array.isArray(request.timeline)||(request.referenceAudioAssetId!==undefined&&!isSafeAssetId(request.referenceAudioAssetId)))return{status:"failed",issues:[{reasonCode:"adapter-request-invalid",classification:"validation"}],audit:audit("1.0","failed",0,0,0,0,[],["adapter-request-invalid"])};if(JSON.stringify(input.profile)!==JSON.stringify(referenceMusicMaterializationProfile))return{status:"failed",issues:[{reasonCode:"profile-invalid",classification:"validation"}],audit:audit("1.0","failed",0,0,0,0,[],["profile-invalid"])};
    let optional=0,materialized=0,omitted=0;const reasons:RequestMaterializationReasonCode[]=[],modes:ResolvedAssetAccess["mode"][]=[],expiries:string[]=[];let referenceAudio;
    if(request.referenceAudioAssetId){optional=1;const mappingIndex=input.profile.mappings.findIndex(m=>m.sourceSlot==="reference-audio"),mapping=input.profile.mappings[mappingIndex];if(!mapping)return{status:"failed",issues:[{reasonCode:"profile-invalid",classification:"validation"}],audit:audit("1.0","failed",0,1,0,0,[],["profile-invalid"])};const asset=findByUsage(c.index!,request.referenceAudioAssetId,"audio-conditioning");if(!asset){omitted=1;reasons.push("optional-asset-omitted");}else{const checked=validateResolvedAsset(asset,mapping,c.baselineMs!,input.profile.minimumAssetLifetimeSeconds,mappingIndex);if(checked.issue)return{status:"failed",issues:[checked.issue],audit:audit("1.0","failed",0,1,0,0,[],[checked.issue.reasonCode])};referenceAudio=checked.value;materialized=1;modes.push(asset.access.mode);if(checked.expiry)expiries.push(checked.expiry);}}
    const {referenceAudioAssetId:_,...rest}=deepCopy(request);const body:ReferenceMusicMaterializedBody={...rest,...(referenceAudio?{referenceAudio}:{})};const earliest=expiries.sort((a,b)=>parseIsoEpochMilliseconds(a)!-parseIsoEpochMilliseconds(b)!)[0];const materializedRequest={requestVersion:"1.0",providerId:input.providerId,providerApiVersion:input.providerApiVersion,operation:"generate-music",body,assetAccessCount:materialized,...(earliest?{earliestAssetExpiry:earliest}:{}),materialization:{status:"complete",unresolvedAssetCount:0}} as MaterializedProviderRequest<ReferenceMusicMaterializedBody>;
    return{status:"materialized",request:materializedRequest,audit:audit("1.0","materialized",0,optional,materialized,omitted,modes,reasons)};
  }
});
