import type { ResolvedAssetAccess } from "@/lib/assets/types";
import type {
  MaterializedProviderRequest,
  ReferenceMVRequest,
} from "@/lib/providerRequests/types";
import { audit, deepCopy, deepFreeze, findByUsage, findUniqueByAllowedUsage, isObject, isSafeAssetId, parseIsoEpochMilliseconds, validateCommonInput, validateResolvedAsset } from "./materializerUtils";
import { REFERENCE_MATERIALIZER_PROVIDER_API_VERSION, REFERENCE_MATERIALIZER_PROVIDER_ID, referenceMVMaterializationProfile } from "./referenceProfiles";
import type { MaterializedAssetValue, ReferenceMVMaterializedBody, ReferenceMVMaterializedSceneInstruction, ReferenceMVSlot, RequestMaterializationInput, RequestMaterializationIssueClassification, RequestMaterializationReasonCode, RequestMaterializationResult, RequestMaterializer } from "./types";

const fail=(reason:RequestMaterializationReasonCode,classification:RequestMaterializationIssueClassification="mapping",required=0,optional=0,materialized=0,modes:ResolvedAssetAccess["mode"][]=[],mappingIndex?:number):RequestMaterializationResult<ReferenceMVMaterializedBody>=>({status:"failed",issues:[{reasonCode:reason,classification,...(mappingIndex===undefined?{}:{mappingIndex})}],audit:audit("1.0","failed",required,optional,materialized,0,modes,[reason])});
export const referenceMVMaterializer:RequestMaterializer<ReferenceMVRequest,ReferenceMVMaterializedBody,ReferenceMVSlot>=deepFreeze({
  materializerId:"reference-mv-materializer-v1",materializerVersion:"reference-v1",providerId:REFERENCE_MATERIALIZER_PROVIDER_ID,providerApiVersion:REFERENCE_MATERIALIZER_PROVIDER_API_VERSION,operation:"generate-mv",
  materialize(raw:RequestMaterializationInput<ReferenceMVRequest,ReferenceMVSlot>):RequestMaterializationResult<ReferenceMVMaterializedBody>{
    const c=validateCommonInput(raw,"generate-mv");if(c.issue)return{status:"failed",issues:[c.issue],audit:audit("1.0","failed",0,0,0,0,[],[c.issue.reasonCode])};const input=c.input!,request=input.adapterRequest as ReferenceMVRequest;
    if(request.requestSchemaVersion!=="1.0"||typeof request.durationSeconds!=="number"||!Number.isFinite(request.durationSeconds)||request.durationSeconds<=0||typeof request.aspectRatio!=="string"||(request.resolution!=="720p"&&request.resolution!=="1080p")||(request.frameRate!==24&&request.frameRate!==30)||request.outputFormat!=="mp4"||!isSafeAssetId(request.audioAssetId)||!isObject(request.globalDirection)||!isObject(request.peak)||!isObject(request.afterglow)||!Array.isArray(request.scenes)||request.scenes.some(scene=>!isObject(scene)||!isSafeAssetId(scene.sceneId)||typeof scene.startSeconds!=="number"||typeof scene.endSeconds!=="number"||!Array.isArray(scene.assetIds)||scene.assetIds.some(id=>!isSafeAssetId(id))||new Set(scene.assetIds).size!==scene.assetIds.length))return fail("adapter-request-invalid","validation");
    if(JSON.stringify(input.profile)!==JSON.stringify(referenceMVMaterializationProfile))return fail("profile-invalid","validation");
    const ai=input.profile.mappings.findIndex(m=>m.sourceSlot==="audio"),si=input.profile.mappings.findIndex(m=>m.sourceSlot==="scene-assets"),am=input.profile.mappings[ai],sm=input.profile.mappings[si];if(!am||!sm)return fail("profile-invalid","validation");
    const audio=findByUsage(c.index!,request.audioAssetId,"audio-conditioning");if(!audio)return fail("required-asset-missing","mapping",1);const checkedAudio=validateResolvedAsset(audio,am,c.baselineMs!,input.profile.minimumAssetLifetimeSeconds,ai);if(checkedAudio.issue)return{status:"failed",issues:[checkedAudio.issue],audit:audit("1.0","failed",1,0,0,0,[],[checkedAudio.issue.reasonCode])};
    const usages=Array.isArray(sm.usage)?sm.usage:[sm.usage],optional=request.scenes.reduce((sum,s)=>sum+s.assetIds.length,0);if(sm.maximumCount!==undefined&&optional>sm.maximumCount)return fail("source-field-cardinality-invalid","mapping",1,optional,1,[audio.access.mode],si);
    const modes:ResolvedAssetAccess["mode"][]=[audio.access.mode],expiries:string[]=[];if(checkedAudio.expiry)expiries.push(checkedAudio.expiry);let materialized=1;const scenes:ReferenceMVMaterializedSceneInstruction[]=[];
    for(const scene of request.scenes){const assets:MaterializedAssetValue[]=[];for(const id of scene.assetIds){const found=findUniqueByAllowedUsage(c.index!,id,usages);if(found.ambiguous)return fail("asset-usage-mismatch","mapping",1,optional,materialized,modes,si);if(!found.asset)return fail("unresolved-asset-reference","mapping",1,optional,materialized,modes,si);const checked=validateResolvedAsset(found.asset,sm,c.baselineMs!,input.profile.minimumAssetLifetimeSeconds,si);if(checked.issue)return{status:"failed",issues:[checked.issue],audit:audit("1.0","failed",1,optional,materialized,0,modes,[checked.issue.reasonCode])};assets.push(checked.value!);materialized++;modes.push(found.asset.access.mode);if(checked.expiry)expiries.push(checked.expiry);}const {assetIds:_,...rest}=deepCopy(scene);scenes.push({...rest,assets});}
    const {audioAssetId:_,scenes:__,...rest}=deepCopy(request);const body:ReferenceMVMaterializedBody={...rest,audio:checkedAudio.value!,scenes};const earliest=expiries.sort((a,b)=>parseIsoEpochMilliseconds(a)!-parseIsoEpochMilliseconds(b)!)[0];const out={requestVersion:"1.0",providerId:input.providerId,providerApiVersion:input.providerApiVersion,operation:"generate-mv",body,assetAccessCount:materialized,...(earliest?{earliestAssetExpiry:earliest}:{}),materialization:{status:"complete",unresolvedAssetCount:0}} as MaterializedProviderRequest<ReferenceMVMaterializedBody>;
    return{status:"materialized",request:out,audit:audit("1.0","materialized",1,optional,materialized,0,modes,[])};
  }
});
