import type { ReconciliationStatement, ReconciliationStatementCatalog, ReconciliationStatementRegistrar } from "./types";

const definitions: readonly Omit<ReconciliationStatement, "parameterCount" | "cardinality" | "accessMode" | "statementClass">[] = [
  { statementId: "reconciliation.request.insert", sql: `INSERT INTO workflow.workflow_reconciliation_requests (reconciliation_id,identity_digest_algorithm,identity_digest_version,identity_digest,identity_digest_domain,tenant_digest,tenant_digest_domain,tenant_digest_algorithm,tenant_digest_version,workflow_digest,workflow_digest_domain,workflow_digest_algorithm,workflow_digest_version,reconciliation_class,operation,home_region,state,policy_version,temporal_policy_class,max_observation_count,max_attempt_count,policy_deadline_at,writer_epoch,retention_class,next_eligible_at,semantic_fingerprint_domain,semantic_fingerprint_algorithm,semantic_fingerprint_algorithm_version,semantic_fingerprint_digest) VALUES ($1,'hmac-sha256',$2,$3,'reconciliation-request',$4,'tenant','hmac-sha256',$5,$6,'workflow','hmac-sha256',$7,$8,$9,$10,$11,1,$12,$13,$14,$15,$16,$17,CASE WHEN $18::timestamptz IS NOT NULL THEN transaction_timestamp() END,'reconciliation-request-semantic','hmac-sha256',$19,$20) ON CONFLICT DO NOTHING RETURNING *` },
  { statementId: "reconciliation.request.read", sql: `SELECT * FROM workflow.workflow_reconciliation_requests WHERE identity_digest_domain='reconciliation-request' AND identity_digest_algorithm='hmac-sha256' AND identity_digest_version=$1 AND identity_digest=$2` },
  { statementId: "reconciliation.request.cas", sql: `UPDATE workflow.workflow_reconciliation_requests SET state=$4,revision=revision+1,updated_at=transaction_timestamp(),terminal_at=CASE WHEN $4 IN ('resolved','still-unknown','corrupted','manual-repair-required','cancelled') THEN transaction_timestamp() ELSE NULL END,next_eligible_at=CASE WHEN $4 IN ('resolved','still-unknown','corrupted','manual-repair-required','cancelled') THEN NULL ELSE next_eligible_at END,resolution_class=$5,escalation_class=$6,claim_owner_digest=CASE WHEN $4 IN ('claimed','observing') THEN claim_owner_digest ELSE NULL END,claim_owner_digest_domain=CASE WHEN $4 IN ('claimed','observing') THEN claim_owner_digest_domain ELSE NULL END,claim_owner_digest_algorithm=CASE WHEN $4 IN ('claimed','observing') THEN claim_owner_digest_algorithm ELSE NULL END,claim_owner_digest_version=CASE WHEN $4 IN ('claimed','observing') THEN claim_owner_digest_version ELSE NULL END,lease_expires_at=CASE WHEN $4 IN ('claimed','observing') THEN lease_expires_at ELSE NULL END WHERE identity_digest_version=$1 AND identity_digest=$2 AND revision=$3 AND writer_epoch=$7 AND fencing_revision=$8 AND state NOT IN ('resolved','still-unknown','corrupted','manual-repair-required','cancelled','deleted') RETURNING *` },
  { statementId: "reconciliation.request.cas.v2", sql: `UPDATE workflow.workflow_reconciliation_requests SET state=$4,revision=revision+1,updated_at=transaction_timestamp(),terminal_at=CASE WHEN $4 IN ('resolved','still-unknown','corrupted','manual-repair-required','cancelled') THEN transaction_timestamp() ELSE NULL END,next_eligible_at=CASE WHEN $4 IN ('resolved','still-unknown','corrupted','manual-repair-required','cancelled') THEN NULL ELSE next_eligible_at END,resolution_class=$5,escalation_class=$6,claim_owner_digest=CASE WHEN $4 IN ('claimed','observing') THEN claim_owner_digest ELSE NULL END,claim_owner_digest_domain=CASE WHEN $4 IN ('claimed','observing') THEN claim_owner_digest_domain ELSE NULL END,claim_owner_digest_algorithm=CASE WHEN $4 IN ('claimed','observing') THEN claim_owner_digest_algorithm ELSE NULL END,claim_owner_digest_version=CASE WHEN $4 IN ('claimed','observing') THEN claim_owner_digest_version ELSE NULL END,lease_expires_at=CASE WHEN $4 IN ('claimed','observing') THEN lease_expires_at ELSE NULL END WHERE identity_digest_version=$1 AND identity_digest=$2 AND revision=$3 AND writer_epoch=$7 AND fencing_revision=$8 AND claim_owner_digest=$9 AND state=ANY($10::text[]) AND state NOT IN ('resolved','still-unknown','corrupted','manual-repair-required','cancelled','deleted') AND deletion_state='active' RETURNING *` },
  { statementId: "reconciliation.request.claim", sql: `WITH candidates AS (SELECT reconciliation_id FROM workflow.workflow_reconciliation_requests WHERE ((state IN ('pending-observation','retry-wait') AND next_eligible_at<=transaction_timestamp()) OR (state IN ('claimed','observing') AND lease_expires_at<=transaction_timestamp())) AND writer_epoch=$1 ORDER BY COALESCE(next_eligible_at,lease_expires_at),reconciliation_id FOR UPDATE SKIP LOCKED LIMIT $2) UPDATE workflow.workflow_reconciliation_requests r SET state='claimed',claim_owner_digest=$3,claim_owner_digest_domain='claim-owner',claim_owner_digest_algorithm='hmac-sha256',claim_owner_digest_version=$4,lease_expires_at=$5,fencing_revision=r.fencing_revision+1,revision=r.revision+1,updated_at=transaction_timestamp() FROM candidates c WHERE r.reconciliation_id=c.reconciliation_id RETURNING r.*` },
  { statementId: "reconciliation.request.renew", sql: `UPDATE workflow.workflow_reconciliation_requests SET lease_expires_at=$7,revision=revision+1,updated_at=transaction_timestamp() WHERE identity_digest_version=$1 AND identity_digest=$2 AND state IN ('claimed','observing') AND writer_epoch=$3 AND fencing_revision=$4 AND claim_owner_digest=$5 AND lease_expires_at>transaction_timestamp() AND $6::boolean RETURNING *` },
  { statementId: "reconciliation.request.release", sql: `UPDATE workflow.workflow_reconciliation_requests SET state='retry-wait',claim_owner_digest=NULL,claim_owner_digest_domain=NULL,claim_owner_digest_algorithm=NULL,claim_owner_digest_version=NULL,lease_expires_at=NULL,next_eligible_at=transaction_timestamp(),revision=revision+1,updated_at=transaction_timestamp() WHERE identity_digest_version=$1 AND identity_digest=$2 AND state IN ('claimed','observing') AND writer_epoch=$3 AND fencing_revision=$4 AND claim_owner_digest=$5 AND lease_expires_at>transaction_timestamp() RETURNING *` },
  { statementId: "reconciliation.observation.insert", sql: `INSERT INTO workflow.workflow_reconciliation_observations (observation_id,reconciliation_id,identity_digest_algorithm,identity_digest_version,identity_digest,identity_digest_domain,tenant_digest,tenant_digest_domain,tenant_digest_algorithm,tenant_digest_version,observation_sequence,source_class,source_result_class,safe_evidence_class,attempt,observed_at,safe_payload,payload_version,semantic_fingerprint_domain,semantic_fingerprint_algorithm,semantic_fingerprint_algorithm_version,semantic_fingerprint_digest) VALUES ($1,$2,'hmac-sha256',$3,$4,'observation',$5,'tenant','hmac-sha256',$6,$7,$8,$9,$10,$11,$12,$13::jsonb,1,'observation-semantic','hmac-sha256',$14,$15) ON CONFLICT DO NOTHING RETURNING *` },
  { statementId: "reconciliation.observation.read", sql: `SELECT * FROM workflow.workflow_reconciliation_observations WHERE identity_digest_version=$1 AND identity_digest=$2` },
  { statementId: "reconciliation.observation.list", sql: `SELECT * FROM workflow.workflow_reconciliation_observations WHERE reconciliation_id=$1 ORDER BY observation_sequence` },
  { statementId: "reconciliation.observation.latest", sql: `SELECT * FROM workflow.workflow_reconciliation_observations WHERE reconciliation_id=$1 AND source_class=$2 ORDER BY observation_sequence DESC LIMIT 1` },
  { statementId: "reconciliation.resolution.insert", sql: `INSERT INTO workflow.workflow_reconciliation_resolutions (resolution_id,reconciliation_id,identity_digest_algorithm,identity_digest_version,identity_digest,identity_digest_domain,tenant_digest,tenant_digest_domain,tenant_digest_algorithm,tenant_digest_version,resolution_sequence,resolution_class,safe_reason_code,safe_summary,summary_version,committed_revision,resolved_at,semantic_fingerprint_domain,semantic_fingerprint_algorithm,semantic_fingerprint_algorithm_version,semantic_fingerprint_digest) VALUES ($1,$2,'hmac-sha256',$3,$4,'resolution',$5,'tenant','hmac-sha256',$6,$7,$8,$9,$10::jsonb,1,$11,$12,'resolution-semantic','hmac-sha256',$13,$14) ON CONFLICT DO NOTHING RETURNING *` },
  { statementId: "reconciliation.resolution.insert.v2", sql: `INSERT INTO workflow.workflow_reconciliation_resolutions (resolution_id,reconciliation_id,identity_digest_algorithm,identity_digest_version,identity_digest,identity_digest_domain,tenant_digest,tenant_digest_domain,tenant_digest_algorithm,tenant_digest_version,resolution_sequence,resolution_class,safe_reason_code,safe_summary,summary_version,committed_revision,resolved_at,semantic_fingerprint_domain,semantic_fingerprint_algorithm,semantic_fingerprint_algorithm_version,semantic_fingerprint_digest) SELECT $1,r.reconciliation_id,'hmac-sha256',$3,$4,'resolution',$5,'tenant','hmac-sha256',$6,$7,$8,$9,$10::jsonb,1,$11,$12,'resolution-semantic','hmac-sha256',$13,$14 FROM workflow.workflow_reconciliation_requests r WHERE r.reconciliation_id=$2 AND r.identity_digest_version=$15 AND r.identity_digest=$16 AND r.revision=$17 AND r.state=ANY($18::text[]) AND r.writer_epoch=$19 AND r.claim_owner_digest=$20 AND r.fencing_revision=$21 AND r.deletion_state='active' AND r.state NOT IN ('resolved','still-unknown','corrupted','manual-repair-required','cancelled','deleted') ON CONFLICT DO NOTHING RETURNING *` },
  { statementId: "reconciliation.resolution.read", sql: `SELECT * FROM workflow.workflow_reconciliation_resolutions WHERE identity_digest_version=$1 AND identity_digest=$2` },
  { statementId: "reconciliation.resolution.list", sql: `SELECT * FROM workflow.workflow_reconciliation_resolutions WHERE reconciliation_id=$1 ORDER BY resolution_sequence` },
  { statementId: "reconciliation.resolution.latest", sql: `SELECT * FROM workflow.workflow_reconciliation_resolutions WHERE reconciliation_id=$1 ORDER BY resolution_sequence DESC LIMIT 1` },
  { statementId: "reconciliation.repair.insert", sql: `INSERT INTO workflow.workflow_reconciliation_manual_repairs (repair_request_id,reconciliation_id,identity_digest_algorithm,identity_digest_version,identity_digest,identity_digest_domain,tenant_digest,tenant_digest_domain,tenant_digest_algorithm,tenant_digest_version,state,requested_action_class,requester_subject_digest,requester_subject_digest_domain,requester_subject_digest_algorithm,requester_subject_digest_version,approver_subject_digest,approver_subject_digest_domain,approver_subject_digest_algorithm,approver_subject_digest_version,authorization_decision_reference_digest,authorization_decision_reference_digest_domain,authorization_decision_reference_digest_algorithm,authorization_decision_reference_digest_version,approval_decision_reference_digest,approval_decision_reference_digest_domain,approval_decision_reference_digest_algorithm,approval_decision_reference_digest_version,safe_reason_code,safe_metadata,metadata_version,requested_at,retention_class,legal_hold_state,writer_epoch,semantic_fingerprint_domain,semantic_fingerprint_algorithm,semantic_fingerprint_algorithm_version,semantic_fingerprint_digest) VALUES ($1,$2,'hmac-sha256',$3,$4,'manual-repair',$5,'tenant','hmac-sha256',$6,'requested',$7,$8,'operator-subject','hmac-sha256',$9,$10,$11,$12,$13,$14,'authorization-decision','hmac-sha256',$15,$16,$17,$18,$19,$20,$21::jsonb,1,$22,$23,$24,$25,'manual-repair-semantic','hmac-sha256',$26,$27) ON CONFLICT DO NOTHING RETURNING *` },
  { statementId: "reconciliation.repair.read", sql: `SELECT * FROM workflow.workflow_reconciliation_manual_repairs WHERE identity_digest_version=$1 AND identity_digest=$2` },
  { statementId: "reconciliation.repair.cas", sql: `UPDATE workflow.workflow_reconciliation_manual_repairs SET state=$6,approved_at=CASE WHEN $6 IN ('authorized','rejected') THEN transaction_timestamp() ELSE approved_at END,started_at=CASE WHEN $6='executing' THEN transaction_timestamp() ELSE started_at END,completed_at=CASE WHEN $6 IN ('reconciled','deferred','terminal-safe-failure') THEN transaction_timestamp() ELSE completed_at END,cancelled_at=CASE WHEN $6='cancelled' THEN transaction_timestamp() ELSE NULL END,revision=revision+1,updated_at=transaction_timestamp() WHERE identity_digest_version=$1 AND identity_digest=$2 AND revision=$3 AND writer_epoch=$4 AND COALESCE(fencing_revision,0)=$5 AND state NOT IN ('rejected','reconciled','deferred','terminal-safe-failure','cancelled') RETURNING *` },
  { statementId: "reconciliation.repair.approve", sql: `UPDATE workflow.workflow_reconciliation_manual_repairs SET state='authorized',approver_subject_digest=$8,approver_subject_digest_domain='operator-subject',approver_subject_digest_algorithm='hmac-sha256',approver_subject_digest_version=$9,approval_decision_reference_digest=$10,approval_decision_reference_digest_domain='approval-decision',approval_decision_reference_digest_algorithm='hmac-sha256',approval_decision_reference_digest_version=$11,safe_reason_code=$13,approved_at=transaction_timestamp(),revision=revision+1,updated_at=transaction_timestamp() WHERE identity_digest_version=$1 AND identity_digest=$2 AND revision=$3 AND state=$4 AND state='requested' AND writer_epoch=$5 AND COALESCE(fencing_revision,0)=$6 AND requester_subject_digest=$7 AND requester_subject_digest<>$8 AND requested_action_class IN ('transition-business-state','revoke-reference','reissue-outbox','cancel-repair') AND $12::integer>0 AND semantic_fingerprint_algorithm_version=$14 AND semantic_fingerprint_digest=$15 AND deletion_state='active' RETURNING *` },
  { statementId: "reconciliation.outbox.insert", sql: `INSERT INTO workflow.workflow_reconciliation_outbox_events (event_id,reconciliation_id,identity_digest_algorithm,identity_digest_version,identity_digest,identity_digest_domain,tenant_digest,tenant_digest_domain,tenant_digest_algorithm,tenant_digest_version,event_type,payload_version,safe_payload,delivery_state,next_eligible_at,retention_class,semantic_fingerprint_domain,semantic_fingerprint_algorithm,semantic_fingerprint_algorithm_version,semantic_fingerprint_digest) VALUES ($1,$2,'hmac-sha256',$3,$4,'reconciliation-outbox',$5,'tenant','hmac-sha256',$6,$7,1,$8::jsonb,'pending',CASE WHEN $9::timestamptz IS NOT NULL THEN transaction_timestamp() END,$10,'reconciliation-outbox-semantic','hmac-sha256',$11,$12) ON CONFLICT DO NOTHING RETURNING *` },
  { statementId: "reconciliation.outbox.read", sql: `SELECT * FROM workflow.workflow_reconciliation_outbox_events WHERE identity_digest_version=$1 AND identity_digest=$2` },
  { statementId: "reconciliation.outbox.claim", sql: `WITH candidates AS (SELECT event_id FROM workflow.workflow_reconciliation_outbox_events WHERE ((delivery_state='pending' AND next_eligible_at<=transaction_timestamp()) OR (delivery_state='claimed' AND lease_expires_at<=transaction_timestamp())) ORDER BY COALESCE(next_eligible_at,lease_expires_at),event_id FOR UPDATE SKIP LOCKED LIMIT $1) UPDATE workflow.workflow_reconciliation_outbox_events e SET delivery_state='claimed',claim_owner_digest=$2,claim_owner_digest_domain='claim-owner',claim_owner_digest_algorithm='hmac-sha256',claim_owner_digest_version=$3,lease_expires_at=$4,fencing_revision=e.fencing_revision+1,attempt=e.attempt+1,revision=e.revision+1,updated_at=transaction_timestamp(),safe_failure_class=NULL FROM candidates c WHERE e.event_id=c.event_id RETURNING e.*` },
  { statementId: "reconciliation.outbox.renew", sql: `UPDATE workflow.workflow_reconciliation_outbox_events SET lease_expires_at=$6,revision=revision+1,updated_at=transaction_timestamp() WHERE identity_digest_version=$1 AND identity_digest=$2 AND delivery_state='claimed' AND fencing_revision=$3 AND claim_owner_digest=$4 AND lease_expires_at>transaction_timestamp() AND $5::boolean RETURNING *` },
  { statementId: "reconciliation.outbox.release", sql: `UPDATE workflow.workflow_reconciliation_outbox_events SET delivery_state='pending',claim_owner_digest=NULL,claim_owner_digest_domain=NULL,claim_owner_digest_algorithm=NULL,claim_owner_digest_version=NULL,lease_expires_at=NULL,next_eligible_at=transaction_timestamp(),revision=revision+1,updated_at=transaction_timestamp() WHERE identity_digest_version=$1 AND identity_digest=$2 AND delivery_state='claimed' AND fencing_revision=$3 AND claim_owner_digest=$4 AND lease_expires_at>transaction_timestamp() RETURNING *` },
  { statementId: "reconciliation.outbox.transition", sql: `UPDATE workflow.workflow_reconciliation_outbox_events SET delivery_state=$5,delivered_at=CASE WHEN $5='delivered' THEN transaction_timestamp() ELSE NULL END,safe_failure_class=CASE WHEN $5='reconciliation-required' THEN $6 ELSE NULL END,claim_owner_digest=NULL,claim_owner_digest_domain=NULL,claim_owner_digest_algorithm=NULL,claim_owner_digest_version=NULL,lease_expires_at=NULL,revision=revision+1,updated_at=transaction_timestamp() WHERE identity_digest_version=$1 AND identity_digest=$2 AND revision=$3 AND fencing_revision=$4 AND delivery_state='claimed' RETURNING *` },
  { statementId: "reconciliation.outbox.transition.v2", sql: `UPDATE workflow.workflow_reconciliation_outbox_events SET delivery_state=$7,delivered_at=CASE WHEN $7='delivered' THEN transaction_timestamp() ELSE NULL END,safe_failure_class=CASE WHEN $7='reconciliation-required' THEN $8 ELSE NULL END,claim_owner_digest=NULL,claim_owner_digest_domain=NULL,claim_owner_digest_algorithm=NULL,claim_owner_digest_version=NULL,lease_expires_at=NULL,revision=revision+1,updated_at=transaction_timestamp() WHERE identity_digest_version=$1 AND identity_digest=$2 AND revision=$3 AND delivery_state=$4 AND delivery_state='claimed' AND claim_owner_digest=$5 AND fencing_revision=$6 AND deletion_state='active' RETURNING *` },
  { statementId: "reconciliation.outbox.renew.v2", sql: `UPDATE workflow.workflow_reconciliation_outbox_events SET lease_expires_at=$7,revision=revision+1,updated_at=transaction_timestamp() WHERE identity_digest_version=$1 AND identity_digest=$2 AND revision=$3 AND delivery_state=$4 AND delivery_state='claimed' AND claim_owner_digest=$5 AND fencing_revision=$6 AND lease_expires_at>transaction_timestamp() AND deletion_state='active' RETURNING *` },
  { statementId: "reconciliation.outbox.release.v2", sql: `UPDATE workflow.workflow_reconciliation_outbox_events SET delivery_state='pending',claim_owner_digest=NULL,claim_owner_digest_domain=NULL,claim_owner_digest_algorithm=NULL,claim_owner_digest_version=NULL,lease_expires_at=NULL,next_eligible_at=transaction_timestamp(),revision=revision+1,updated_at=transaction_timestamp() WHERE identity_digest_version=$1 AND identity_digest=$2 AND revision=$3 AND delivery_state=$4 AND delivery_state='claimed' AND claim_owner_digest=$5 AND fencing_revision=$6 AND deletion_state='active' RETURNING *` },
  { statementId: "reconciliation.outbox.takeover.v2", sql: `UPDATE workflow.workflow_reconciliation_outbox_events SET claim_owner_digest=$5,claim_owner_digest_domain='claim-owner',claim_owner_digest_algorithm='hmac-sha256',claim_owner_digest_version=$6,lease_expires_at=$7,fencing_revision=fencing_revision+1,attempt=attempt+1,revision=revision+1,updated_at=transaction_timestamp() WHERE identity_digest_version=$1 AND identity_digest=$2 AND revision=$3 AND delivery_state='claimed' AND fencing_revision=$4 AND lease_expires_at<transaction_timestamp() AND deletion_state='active' RETURNING *` },
  { statementId: "reconciliation.commit.lookup", sql: `SELECT (SELECT count(*) FROM workflow.workflow_reconciliation_requests WHERE identity_digest=$1 AND semantic_fingerprint_digest=$2) request_count,(SELECT count(*) FROM workflow.workflow_reconciliation_observations WHERE identity_digest=$3 AND semantic_fingerprint_digest=$4) observation_count,(SELECT count(*) FROM workflow.workflow_reconciliation_resolutions WHERE $5::bytea IS NULL OR identity_digest=$5 AND semantic_fingerprint_digest=$6) resolution_count,(SELECT count(*) FROM workflow.workflow_reconciliation_outbox_events WHERE $7::bytea IS NULL OR identity_digest=$7 AND semantic_fingerprint_digest=$8) outbox_count` },
];

const meta: Readonly<Record<string, readonly [number, "none" | "single" | "many", "read" | "write", ReconciliationStatement["statementClass"]]>> = Object.freeze({
  "reconciliation.request.insert":[20,"many","write","insert"],"reconciliation.request.read":[2,"single","read","select"],"reconciliation.request.cas":[8,"single","write","cas"],"reconciliation.request.cas.v2":[10,"single","write","cas"],"reconciliation.request.claim":[5,"many","write","claim"],"reconciliation.request.renew":[7,"single","write","transition"],"reconciliation.request.release":[5,"single","write","transition"],
  "reconciliation.observation.insert":[15,"many","write","insert"],"reconciliation.observation.read":[2,"single","read","select"],"reconciliation.observation.list":[1,"many","read","select"],"reconciliation.observation.latest":[2,"single","read","select"],
  "reconciliation.resolution.insert":[14,"many","write","insert"],"reconciliation.resolution.insert.v2":[21,"many","write","insert"],"reconciliation.resolution.read":[2,"single","read","select"],"reconciliation.resolution.list":[1,"many","read","select"],"reconciliation.resolution.latest":[1,"single","read","select"],
  "reconciliation.repair.insert":[27,"many","write","insert"],"reconciliation.repair.read":[2,"single","read","select"],"reconciliation.repair.cas":[6,"single","write","cas"],"reconciliation.repair.approve":[15,"single","write","cas"],
  "reconciliation.outbox.insert":[12,"many","write","insert"],"reconciliation.outbox.read":[2,"single","read","select"],"reconciliation.outbox.claim":[4,"many","write","claim"],"reconciliation.outbox.renew":[6,"single","write","transition"],"reconciliation.outbox.release":[4,"single","write","transition"],"reconciliation.outbox.transition":[6,"single","write","transition"],"reconciliation.outbox.transition.v2":[8,"single","write","transition"],"reconciliation.outbox.renew.v2":[7,"single","write","transition"],"reconciliation.outbox.release.v2":[6,"single","write","transition"],"reconciliation.outbox.takeover.v2":[7,"single","write","transition"],"reconciliation.commit.lookup":[8,"single","read","lookup"],
});

export const POSTGRESQL_RECONCILIATION_STATEMENT_CATALOG: ReconciliationStatementCatalog = Object.freeze({ catalogVersion:"1.0", statements:Object.freeze(definitions.map(definition => { const value=meta[definition.statementId]!; return Object.freeze({...definition,parameterCount:value[0],cardinality:value[1],accessMode:value[2],statementClass:value[3]}); })) });
export const registerPostgreSQLReconciliationStatements = (registrar: ReconciliationStatementRegistrar) => registrar.register(POSTGRESQL_RECONCILIATION_STATEMENT_CATALOG);
