import type { DurableWorkflowDatabaseRow, DurableWorkflowTransactionContext } from "../durableTransaction";
import { decodeOutbox } from "./postgresqlReconciliationStores";
import { execute, sameDigest, text, validFingerprint, validIdentity } from "./postgresqlReconciliationStoreUtils";
import type { ReconciliationOutboxGuardV2, ReconciliationOutboxLeaseInputV2, ReconciliationOutboxRecord, ReconciliationOutboxStoreV2, ReconciliationOutboxTakeoverInputV2, ReconciliationOutboxTransitionInputV2, ReconciliationOutboxTransitionResultV2 } from "./types";

const noSubmit = Object.freeze({providerSubmitPermitted:false} as const);
const conflict = (conflictClass:"stale-revision"|"stale-fence"|"wrong-prior-state"|"semantic-conflict"|"terminal-preserved"):ReconciliationOutboxTransitionResultV2=>Object.freeze({status:"conflict",conflictClass,...noSubmit});
const corrupted = ():ReconciliationOutboxTransitionResultV2=>Object.freeze({status:"corrupted",...noSubmit});
const unavailable = ():ReconciliationOutboxTransitionResultV2=>Object.freeze({status:"unavailable",retryable:true,...noSubmit});
const updated = (outcome:"renewed"|"released"|"taken-over"|"delivered"|"reconciliation-required"):ReconciliationOutboxTransitionResultV2=>Object.freeze({status:"updated",outcome,...noSubmit});
const safeFailureClass=/^[a-z][a-z0-9-]{0,63}$/;

async function authoritativeRow(context:DurableWorkflowTransactionContext,identity:ReconciliationOutboxGuardV2["identity"]):Promise<DurableWorkflowDatabaseRow|undefined|"unavailable">{const value=await execute(context.database,"reconciliation.outbox.read",[identity.algorithmVersion,identity.digest],"single");if(value.status==="failure")return"unavailable";return value.status==="success"&&value.rows.length===1?value.rows[0]:undefined;}
async function classify(context:DurableWorkflowTransactionContext,input:ReconciliationOutboxGuardV2):Promise<ReconciliationOutboxTransitionResultV2>{const row=await authoritativeRow(context,input.identity);if(row==="unavailable")return unavailable();if(!row)return conflict("semantic-conflict");const record:ReconciliationOutboxRecord|undefined=decodeOutbox(row);if(!record||text(row,"deletion_state")!=="active")return corrupted();if(!sameDigest(record.fingerprint.digest,input.expectedFingerprint.digest))return conflict("semantic-conflict");if(record.deliveryState==="delivered"||record.deliveryState==="reconciliation-required")return conflict("terminal-preserved");if(!record.claimOwner||!sameDigest(record.claimOwner.digest,input.expectedOwner.digest)||record.fencingRevision!==input.expectedFence)return conflict("stale-fence");if(record.revision!==input.expectedRevision)return conflict("stale-revision");if(record.deliveryState!==input.expectedSourceState)return conflict("wrong-prior-state");return corrupted();}
const validGuard=(input:ReconciliationOutboxGuardV2)=>validIdentity(input.identity,"reconciliation-outbox")&&validFingerprint(input.expectedFingerprint,"reconciliation-outbox-semantic")&&validIdentity(input.expectedOwner,"claim-owner")&&input.expectedSourceState==="claimed";
async function executeGuarded(context:DurableWorkflowTransactionContext,input:ReconciliationOutboxGuardV2,statementId:string,parameters:readonly (string|number|boolean|Uint8Array|null)[],outcome:"renewed"|"released"|"delivered"|"reconciliation-required"):Promise<ReconciliationOutboxTransitionResultV2>{if(!validGuard(input))return corrupted();const value=await execute(context.database,statementId,parameters,"single");if(value.status==="failure")return unavailable();if(value.status==="success"&&value.rows.length===1)return decodeOutbox(value.rows[0]!)?updated(outcome):corrupted();return classify(context,input);}

export const createPostgreSQLReconciliationOutboxStoreV2=():ReconciliationOutboxStoreV2=>Object.freeze({
  storeVersionV2:"2.0",
  transitionV2(context:DurableWorkflowTransactionContext,input:ReconciliationOutboxTransitionInputV2){if((input.targetState==="reconciliation-required"&&(!input.safeFailureClass||!safeFailureClass.test(input.safeFailureClass)))||(input.targetState==="delivered"&&input.safeFailureClass!==undefined))return Promise.resolve(corrupted());return executeGuarded(context,input,"reconciliation.outbox.transition.v2",[input.identity.algorithmVersion,input.identity.digest,input.expectedRevision,input.expectedSourceState,input.expectedOwner.digest,input.expectedFence,input.targetState,input.safeFailureClass??null],input.targetState);},
  renewLeaseV2(context:DurableWorkflowTransactionContext,input:ReconciliationOutboxLeaseInputV2){return executeGuarded(context,input,"reconciliation.outbox.renew.v2",[input.identity.algorithmVersion,input.identity.digest,input.expectedRevision,input.expectedSourceState,input.expectedOwner.digest,input.expectedFence,input.leaseExpiresAt],"renewed");},
  releaseLeaseV2(context:DurableWorkflowTransactionContext,input:ReconciliationOutboxGuardV2){return executeGuarded(context,input,"reconciliation.outbox.release.v2",[input.identity.algorithmVersion,input.identity.digest,input.expectedRevision,input.expectedSourceState,input.expectedOwner.digest,input.expectedFence],"released");},
  async takeoverExpiredLeaseV2(context:DurableWorkflowTransactionContext,input:ReconciliationOutboxTakeoverInputV2){if(!validIdentity(input.identity,"reconciliation-outbox")||!validIdentity(input.newOwner,"claim-owner")||input.expectedSourceState!=="claimed")return corrupted();const value=await execute(context.database,"reconciliation.outbox.takeover.v2",[input.identity.algorithmVersion,input.identity.digest,input.expectedRevision,input.expectedFence,input.newOwner.digest,input.newOwner.algorithmVersion,input.leaseExpiresAt],"single");if(value.status==="failure")return unavailable();if(value.status==="success"&&value.rows.length===1)return decodeOutbox(value.rows[0]!)?updated("taken-over"):corrupted();return conflict("stale-fence");},
});
