import type { DurableWorkflowDatabaseCapability, DurableWorkflowTransactionContext } from "../durableTransaction";

export type ReconciliationDigestDomain =
  | "reconciliation-request" | "tenant" | "workflow" | "provider-request" | "provider-job"
  | "claim-owner" | "observation" | "resolution" | "manual-repair" | "operator-subject"
  | "authorization-decision" | "approval-decision" | "reconciliation-outbox";
export type ReconciliationFingerprintDomain =
  | "reconciliation-request-semantic" | "observation-semantic" | "resolution-semantic"
  | "manual-repair-semantic" | "reconciliation-outbox-semantic";
export type ProtectedIdentity<D extends ReconciliationDigestDomain = ReconciliationDigestDomain> = Readonly<{
  domain: D; algorithm: "hmac-sha256"; algorithmVersion: number; digest: Uint8Array;
}>;
export type SemanticFingerprint<D extends ReconciliationFingerprintDomain = ReconciliationFingerprintDomain> = Readonly<{
  domain: D; algorithm: "hmac-sha256"; algorithmVersion: number; digest: Uint8Array;
}>;
export type ReconciliationUuidGenerator = Readonly<{ generatorVersion: "1.0"; generate(): string }>;
export type ReconciliationReadSession = Readonly<{ sessionVersion: "1.0"; database: DurableWorkflowDatabaseCapability }>;
export type SafeJson = Readonly<Record<string, string | number | boolean | null>>;
export type ReconciliationRequestState = "pending-observation" | "claimed" | "observing" | "retry-wait" | "resolved" | "still-unknown" | "corrupted" | "manual-repair-required" | "cancelled";
export type ReconciliationRequestNonTerminalState = Exclude<ReconciliationRequestState, "resolved" | "still-unknown" | "corrupted" | "manual-repair-required" | "cancelled">;
export type ReconciliationExpectedPriorStates = readonly [ReconciliationRequestNonTerminalState, ...ReconciliationRequestNonTerminalState[]];
export type ReconciliationTransitionAuthorityV2 = Readonly<{ writerEpoch: string; expectedFence: string; owner: ProtectedIdentity<"claim-owner"> }>;

export type ReconciliationRequestRecord = Readonly<{
  id: string; identity: ProtectedIdentity<"reconciliation-request">; tenant: ProtectedIdentity<"tenant">;
  workflow: ProtectedIdentity<"workflow">; providerRequest?: ProtectedIdentity<"provider-request">;
  providerJob?: ProtectedIdentity<"provider-job">; fingerprint: SemanticFingerprint<"reconciliation-request-semantic">;
  reconciliationClass: string; operation: "generate-vocal" | "generate-music" | "generate-mv"; region: string;
  state: ReconciliationRequestState; policyClass: string; maxObservations: number; maxAttempts: number;
  observationCount: number; attempt: number; writerEpoch: string; fencingRevision: string; revision: string;
  nextEligibleAt?: string; leaseExpiresAt?: string; claimOwner?: ProtectedIdentity<"claim-owner">;
  resolutionClass?: string; escalationClass?: string; terminalAt?: string;
}>;
export type ReconciliationRequestDraft = Omit<ReconciliationRequestRecord, "id" | "observationCount" | "attempt" | "fencingRevision" | "revision" | "claimOwner" | "leaseExpiresAt" | "resolutionClass" | "escalationClass" | "terminalAt"> & Readonly<{ policyDeadlineAt: string; retentionClass: string }>;
export type StoreRecordResult<T> = Readonly<{ status: "created" | "replayed" | "updated" | "found"; record: T }> | Readonly<{ status: "conflict" | "wrong-prior-state" | "not-found" | "stale-revision" | "stale-fence" | "stale-writer" | "terminal" | "legacy-unready" | "corrupted" | "unavailable" }>;
export type LeaseAuthority = Readonly<{ owner: ProtectedIdentity<"claim-owner">; expectedFence: string; writerEpoch: string; leaseExpiresAt: string }>;

export type ObservationRecord = Readonly<{ id: string; requestId: string; identity: ProtectedIdentity<"observation">; tenant: ProtectedIdentity<"tenant">; fingerprint: SemanticFingerprint<"observation-semantic">; sequence: string; source: string; result: string; evidence: string; attempt: number; observedAt: string; payload: SafeJson }>;
export type ObservationDraft = Omit<ObservationRecord, "id">;
export type ResolutionRecord = Readonly<{ id: string; requestId: string; identity: ProtectedIdentity<"resolution">; tenant: ProtectedIdentity<"tenant">; fingerprint: SemanticFingerprint<"resolution-semantic">; sequence: string; resolutionClass: string; reasonCode: string; summary: SafeJson; committedRevision: string; resolvedAt: string }>;
export type ResolutionDraft = Omit<ResolutionRecord, "id">;

export type ManualRepairState = "requested" | "authorized" | "rejected" | "executing" | "reconciled" | "deferred" | "terminal-safe-failure" | "cancelled";
export type ManualRepairRecord = Readonly<{ id: string; requestId: string; identity: ProtectedIdentity<"manual-repair">; tenant: ProtectedIdentity<"tenant">; fingerprint: SemanticFingerprint<"manual-repair-semantic">; requester: ProtectedIdentity<"operator-subject">; approver?: ProtectedIdentity<"operator-subject">; authorizationDecision: ProtectedIdentity<"authorization-decision">; approvalDecision?: ProtectedIdentity<"approval-decision">; state: ManualRepairState; action: string; reasonCode: string; metadata: SafeJson; revision: string; writerEpoch?: string; fencingRevision?: string; leaseExpiresAt?: string; claimOwner?: ProtectedIdentity<"claim-owner">; requestedAt: string; approvedAt?: string; startedAt?: string; completedAt?: string; cancelledAt?: string; legalHoldState: "none" | "held" }>;
export type ManualRepairDraft = Omit<ManualRepairRecord, "id" | "state" | "revision" | "fencingRevision" | "leaseExpiresAt" | "claimOwner" | "approvedAt" | "startedAt" | "completedAt" | "cancelledAt">;

export type ReconciliationOutboxRecord = Readonly<{ id: string; requestId: string; identity: ProtectedIdentity<"reconciliation-outbox">; tenant: ProtectedIdentity<"tenant">; fingerprint: SemanticFingerprint<"reconciliation-outbox-semantic">; eventType: string; payload: SafeJson; deliveryState: "pending" | "claimed" | "delivered" | "reconciliation-required"; attempt: number; revision: string; fencingRevision: string; nextEligibleAt: string; claimOwner?: ProtectedIdentity<"claim-owner">; leaseExpiresAt?: string; deliveredAt?: string }>;
export type ReconciliationOutboxDraft = Omit<ReconciliationOutboxRecord, "id" | "deliveryState" | "attempt" | "revision" | "fencingRevision" | "claimOwner" | "leaseExpiresAt" | "deliveredAt"> & Readonly<{ retentionClass: string }>;

export type StatementCardinality = "none" | "single" | "many";
export type ReconciliationStatement = Readonly<{ statementId: string; sql: string; parameterCount: number; cardinality: StatementCardinality; accessMode: "read" | "write"; statementClass: "insert" | "select" | "cas" | "claim" | "transition" | "lookup" }>;
export type ReconciliationStatementCatalog = Readonly<{ catalogVersion: "1.0"; statements: readonly ReconciliationStatement[] }>;
export type ReconciliationStatementRegistrar = Readonly<{ register(catalog: ReconciliationStatementCatalog): "registered" | "already-registered" | "rejected" }>;

export type ReconciliationRequestStore = Readonly<{ storeVersion: "1.0"; createIfAbsent(c: DurableWorkflowTransactionContext, d: ReconciliationRequestDraft): Promise<StoreRecordResult<ReconciliationRequestRecord>>; readInTransaction(c: DurableWorkflowTransactionContext, i: ProtectedIdentity<"reconciliation-request">): Promise<StoreRecordResult<ReconciliationRequestRecord>>; readAuthoritative(s: ReconciliationReadSession, i: ProtectedIdentity<"reconciliation-request">): Promise<StoreRecordResult<ReconciliationRequestRecord>>; compareAndSet(c: DurableWorkflowTransactionContext, i: ProtectedIdentity<"reconciliation-request">, expectedRevision: string, state: ReconciliationRequestState, authority: Readonly<{ writerEpoch: string; expectedFence: string }>): Promise<StoreRecordResult<ReconciliationRequestRecord>>; claimDue(c: DurableWorkflowTransactionContext, authority: LeaseAuthority, limit: number): Promise<readonly ReconciliationRequestRecord[]>; renewLease(c: DurableWorkflowTransactionContext, i: ProtectedIdentity<"reconciliation-request">, authority: LeaseAuthority): Promise<StoreRecordResult<ReconciliationRequestRecord>>; releaseLease(c: DurableWorkflowTransactionContext, i: ProtectedIdentity<"reconciliation-request">, authority: LeaseAuthority): Promise<StoreRecordResult<ReconciliationRequestRecord>>; takeoverExpiredLease(c: DurableWorkflowTransactionContext, authority: LeaseAuthority, limit: number): Promise<readonly ReconciliationRequestRecord[]>; transition(c: DurableWorkflowTransactionContext, i: ProtectedIdentity<"reconciliation-request">, expectedRevision: string, authority: Readonly<{ writerEpoch: string; expectedFence: string }>, state: ReconciliationRequestState, resolutionClass?: string, escalationClass?: string): Promise<StoreRecordResult<ReconciliationRequestRecord>> }>;
export type ReconciliationRequestTransitionInputV2 = Readonly<{ identity: ProtectedIdentity<"reconciliation-request">; expectedRevision: string; expectedPriorStates: ReconciliationExpectedPriorStates; authority: ReconciliationTransitionAuthorityV2; nextState: ReconciliationRequestState; resolutionClass?: string; escalationClass?: string }>;
export type ReconciliationRequestStoreV2 = ReconciliationRequestStore & Readonly<{ storeVersionV2: "2.0"; transitionV2(c: DurableWorkflowTransactionContext, input: ReconciliationRequestTransitionInputV2): Promise<StoreRecordResult<ReconciliationRequestRecord>> }>;
export type ObservationStore = Readonly<{ storeVersion: "1.0"; appendIfAbsent(c: DurableWorkflowTransactionContext, d: ObservationDraft): Promise<StoreRecordResult<ObservationRecord>>; listByRequest(c: DurableWorkflowTransactionContext, requestId: string): Promise<readonly ObservationRecord[]>; readLatestBySource(c: DurableWorkflowTransactionContext, requestId: string, source: string): Promise<StoreRecordResult<ObservationRecord>> }>;
export type ResolutionStore = Readonly<{ storeVersion: "1.0"; appendIfAbsent(c: DurableWorkflowTransactionContext, d: ResolutionDraft): Promise<StoreRecordResult<ResolutionRecord>>; listByRequest(c: DurableWorkflowTransactionContext, requestId: string): Promise<readonly ResolutionRecord[]>; latestResolution(c: DurableWorkflowTransactionContext, requestId: string): Promise<StoreRecordResult<ResolutionRecord>> }>;
export type ResolutionAtomicInputV2 = Readonly<{ draft: ResolutionDraft; requestIdentity: ProtectedIdentity<"reconciliation-request">; expectedRequestRevision: string; expectedPriorStates: ReconciliationExpectedPriorStates; authority: ReconciliationTransitionAuthorityV2 }>;
export type ReconciliationResolutionAppendResultV2 = Readonly<{status:"created"|"replayed"}> | Readonly<{status:"conflict";conflictClass:"stale-revision"|"stale-fence"|"writer-epoch-mismatch"|"wrong-prior-state"|"semantic-conflict"|"terminal-preserved"}> | Readonly<{status:"corrupted"}> | Readonly<{status:"unavailable";retryable:boolean}>;
export type ResolutionStoreV2 = ResolutionStore & Readonly<{ storeVersionV2: "2.0"; appendForAtomicTransitionV2(c: DurableWorkflowTransactionContext, input: ResolutionAtomicInputV2): Promise<StoreRecordResult<ResolutionRecord>>; appendStandaloneV2(c:DurableWorkflowTransactionContext,input:ResolutionAtomicInputV2):Promise<ReconciliationResolutionAppendResultV2> }>;
export type ManualRepairStore = Readonly<{ storeVersion: "1.0"; createRequest(c: DurableWorkflowTransactionContext, d: ManualRepairDraft): Promise<StoreRecordResult<ManualRepairRecord>>; read(c: DurableWorkflowTransactionContext, i: ProtectedIdentity<"manual-repair">): Promise<StoreRecordResult<ManualRepairRecord>>; compareAndSet(c: DurableWorkflowTransactionContext, i: ProtectedIdentity<"manual-repair">, expectedRevision: string, expectedWriterEpoch: string, expectedFence: string, state: ManualRepairState): Promise<StoreRecordResult<ManualRepairRecord>> }>;
export type ManualRepairApprovalInput = Readonly<{repairIdentity:ProtectedIdentity<"manual-repair">;expectedRevision:string;expectedPriorState:"requested";writerEpoch:string;fencingRevision:string;requester:ProtectedIdentity<"operator-subject">;approver:ProtectedIdentity<"operator-subject">;approvalDecision:ProtectedIdentity<"approval-decision">;authorizationPolicyVersion:number;safeReasonCode:string;semanticFingerprint:SemanticFingerprint<"manual-repair-semantic">}>;
export type ManualRepairApprovalStore = Readonly<{storeVersion:"1.0";recordApproval(c:DurableWorkflowTransactionContext,input:ManualRepairApprovalInput):Promise<StoreRecordResult<ManualRepairRecord>>}>;
export type ReconciliationOutboxStore = Readonly<{ storeVersion: "1.0"; appendIfAbsent(c: DurableWorkflowTransactionContext, d: ReconciliationOutboxDraft): Promise<StoreRecordResult<ReconciliationOutboxRecord>>; claimBatch(c: DurableWorkflowTransactionContext, authority: LeaseAuthority, limit: number): Promise<readonly ReconciliationOutboxRecord[]>; renewLease(c: DurableWorkflowTransactionContext, i: ProtectedIdentity<"reconciliation-outbox">, authority: LeaseAuthority): Promise<StoreRecordResult<ReconciliationOutboxRecord>>; releaseLease(c: DurableWorkflowTransactionContext, i: ProtectedIdentity<"reconciliation-outbox">, authority: LeaseAuthority): Promise<StoreRecordResult<ReconciliationOutboxRecord>>; takeoverExpiredLease(c: DurableWorkflowTransactionContext, authority: LeaseAuthority, limit: number): Promise<readonly ReconciliationOutboxRecord[]>; transition(c: DurableWorkflowTransactionContext, i: ProtectedIdentity<"reconciliation-outbox">, expectedRevision: string, expectedFence: string, state: "delivered" | "reconciliation-required", failureClass?: string): Promise<StoreRecordResult<ReconciliationOutboxRecord>> }>;
export type ReconciliationOutboxConflictClassV2 = "stale-revision" | "stale-fence" | "wrong-prior-state" | "semantic-conflict" | "terminal-preserved";
export type ReconciliationOutboxTransitionResultV2 = Readonly<{status:"updated";outcome:"renewed"|"released"|"taken-over"|"delivered"|"reconciliation-required";providerSubmitPermitted:false}> | Readonly<{status:"conflict";conflictClass:ReconciliationOutboxConflictClassV2;providerSubmitPermitted:false}> | Readonly<{status:"corrupted";providerSubmitPermitted:false}> | Readonly<{status:"unavailable";retryable:boolean;providerSubmitPermitted:false}>;
export type ReconciliationOutboxGuardV2 = Readonly<{identity:ProtectedIdentity<"reconciliation-outbox">;expectedFingerprint:SemanticFingerprint<"reconciliation-outbox-semantic">;expectedRevision:string;expectedSourceState:"claimed";expectedOwner:ProtectedIdentity<"claim-owner">;expectedFence:string}>;
export type ReconciliationOutboxTransitionInputV2 = ReconciliationOutboxGuardV2 & Readonly<{targetState:"delivered"|"reconciliation-required";safeFailureClass?:string}>;
export type ReconciliationOutboxLeaseInputV2 = ReconciliationOutboxGuardV2 & Readonly<{leaseExpiresAt:string}>;
export type ReconciliationOutboxTakeoverInputV2 = Readonly<{identity:ProtectedIdentity<"reconciliation-outbox">;expectedRevision:string;expectedSourceState:"claimed";expectedFence:string;newOwner:ProtectedIdentity<"claim-owner">;leaseExpiresAt:string}>;
export type ReconciliationOutboxStoreV2 = Readonly<{storeVersionV2:"2.0";transitionV2(c:DurableWorkflowTransactionContext,input:ReconciliationOutboxTransitionInputV2):Promise<ReconciliationOutboxTransitionResultV2>;renewLeaseV2(c:DurableWorkflowTransactionContext,input:ReconciliationOutboxLeaseInputV2):Promise<ReconciliationOutboxTransitionResultV2>;releaseLeaseV2(c:DurableWorkflowTransactionContext,input:ReconciliationOutboxGuardV2):Promise<ReconciliationOutboxTransitionResultV2>;takeoverExpiredLeaseV2(c:DurableWorkflowTransactionContext,input:ReconciliationOutboxTakeoverInputV2):Promise<ReconciliationOutboxTransitionResultV2>} >;
export type ReconciliationAtomicInput = Readonly<{ observation: ObservationDraft; requestIdentity: ProtectedIdentity<"reconciliation-request">; expectedRevision: string; authority: Readonly<{ writerEpoch: string; expectedFence: string }>; nextState: ReconciliationRequestState; resolution?: ResolutionDraft; outbox?: ReconciliationOutboxDraft }>;
export type ReconciliationAtomicInputV2 = Readonly<{ observation: ObservationDraft; requestIdentity: ProtectedIdentity<"reconciliation-request">; expectedRevision: string; expectedPriorStates: ReconciliationExpectedPriorStates; authority: ReconciliationTransitionAuthorityV2; nextState: ReconciliationRequestState; resolution?: ResolutionDraft; outbox?: ReconciliationOutboxDraft }>;
export type ReconciliationCommitLookupResult = Readonly<{ status: "committed" | "not-committed" | "corrupted" | "unavailable" }>;
