import type { ReferenceWorkflowAuthenticationAdapter,ReferenceWorkflowAuthenticationResult,ReferenceWorkflowAuthSessionStore } from "./types";
import { copyFixture,REFERENCE_COOKIE_NAME,validFixtureToken } from "./workflowAuthTestUtils";
export type ReferenceWorkflowCookieParseResult={status:"parsed";token:string}|{status:"missing"}|{status:"malformed"};
export function parseReferenceWorkflowSessionCookie(header:unknown):ReferenceWorkflowCookieParseResult{
  if(header===undefined)return{status:"missing"};if(typeof header!=="string"||header.length===0||new TextEncoder().encode(header).length>4096||/[\u0000-\u001f\u007f,]/.test(header))return{status:"malformed"};
  let found:string|undefined;for(const part of header.split(";")){const trimmed=part.trim(),index=trimmed.indexOf("=");if(index<=0||index!==trimmed.lastIndexOf("="))return{status:"malformed"};const name=trimmed.slice(0,index),value=trimmed.slice(index+1);if(!/^[!#$%&'*+.^_`|~0-9A-Za-z-]+$/.test(name)||!value||/["%\s]/.test(value))return{status:"malformed"};if(name===REFERENCE_COOKIE_NAME){if(found!==undefined||!validFixtureToken(value))return{status:"malformed"};found=value}}
  return found===undefined?{status:"missing"}:{status:"parsed",token:found};
}
export function createReferenceWorkflowAuthenticationAdapter(store:ReferenceWorkflowAuthSessionStore):ReferenceWorkflowAuthenticationAdapter{const authenticate=(input:{cookieHeader?:string;baselineTime:string}):ReferenceWorkflowAuthenticationResult=>{try{const parsed=parseReferenceWorkflowSessionCookie(input.cookieHeader);if(parsed.status==="missing")return{status:"unauthenticated",reason:"authentication-missing"};if(parsed.status==="malformed")return{status:"malformed",reason:"authentication-malformed"};const read=store.read(parsed.token,input.baselineTime);if(read.status==="found")return{status:"authenticated",reason:"authentication-succeeded",principal:copyFixture(read.principal),sessionIdentity:read.sessionIdentity};if(read.status==="expired")return{status:"expired",reason:"authentication-expired"};if(read.status==="revoked")return{status:"revoked",reason:"authentication-revoked"};return{status:"unauthenticated",reason:read.status==="invalid"?"authentication-malformed":"authentication-missing"}}catch{return{status:"unavailable",reason:"authentication-unavailable"}}};return Object.freeze({authenticate})};
export const formatReferenceWorkflowCookieHeader=(token:string)=>validFixtureToken(token)?`${REFERENCE_COOKIE_NAME}=${token}`:undefined;
export const REFERENCE_WORKFLOW_COOKIE_ATTRIBUTE_CONTRACT=Object.freeze({httpOnly:true,secure:true,sameSite:"Strict" as const,path:"/" as const,maxAgeSeconds:3600});
