import type { Sensitive } from "@/lib/assets/types";
import type { WorkflowApiCommand } from "@/lib/workflowApi/types";
import type { ReferenceWorkflowBrowserAuthFixture } from "@/lib/workflowAuthTest/types";
import type { ReferenceWorkflowAuthenticationAdapter,ReferenceWorkflowAuthenticationResult,ReferenceWorkflowAuthSessionStore,ReferenceWorkflowBrowserFixtureResult,ReferenceWorkflowCsrfStore,ReferenceWorkflowCsrfValidationResult,ReferenceWorkflowSecurityFactoryResult,WorkflowApiSecurityAdapter } from "./types";
import { formatReferenceWorkflowCookieHeader } from "./referenceWorkflowAuthAdapter";
const commands=new Set(["start","poll-upload","poll-generation","result","cancel"]);
export function createReferenceWorkflowSecurityAdapter(input:{environment:unknown;enabled:unknown;authentication:ReferenceWorkflowAuthenticationAdapter;sessionStore:ReferenceWorkflowAuthSessionStore;csrfStore:ReferenceWorkflowCsrfStore}):ReferenceWorkflowSecurityFactoryResult{
  if(input.environment==="production")return{status:"denied",reason:"reference-auth-production-denied"};if(!(input.environment==="test"||input.environment==="development")||input.enabled!==true)return{status:"denied",reason:"reference-auth-disabled"};
  const authenticate=(value:{cookieHeader?:string;baselineTime:string}):ReferenceWorkflowAuthenticationResult=>input.authentication.authenticate(value);const validateCsrf=(value:{sessionIdentity:string;csrfHeader?:string;command:WorkflowApiCommand;baselineTime:string}):ReferenceWorkflowCsrfValidationResult=>{if(!commands.has(value.command))return{status:"conflict",reason:"csrf-conflict"};const session=input.sessionStore.readByIdentity(value.sessionIdentity,value.baselineTime);if(session.status==="expired")return{status:"expired",reason:"csrf-expired"};if(session.status==="revoked")return{status:"revoked",reason:"csrf-revoked"};if(session.status!=="found")return{status:"conflict",reason:"csrf-conflict"};return input.csrfStore.validateForSession({sessionIdentity:value.sessionIdentity,csrfToken:value.csrfHeader,baselineTime:value.baselineTime})};const adapter:WorkflowApiSecurityAdapter=Object.freeze({authenticate,validateCsrf});return{status:"created",adapter,capability:{capabilityVersion:"1.0",enabled:true,mode:"reference-test-only",productionReady:false}};
}
export function createReferenceWorkflowBrowserAuthFixture(cookieToken:string,csrfToken:string):ReferenceWorkflowBrowserFixtureResult{const cookieHeader=formatReferenceWorkflowCookieHeader(cookieToken);if(!cookieHeader||typeof csrfToken!=="string"||csrfToken.length<16)return{status:"invalid"};return{status:"created",fixture:{fixtureVersion:"1.0",cookieHeader,csrfToken} as Sensitive<ReferenceWorkflowBrowserAuthFixture>}}
