import { PostgreSQLConnectionPoolAdapter } from "@/lib/server/productionWorkflowRuntime/postgresqlDriver";
import type { PostgreSQLConnection, PostgreSQLConnectionConfig, PostgreSQLQueryResult, PostgreSQLTransactionConnection } from "@/lib/server/productionWorkflowRuntime/postgresqlDriver";
import { classifyDurableWorkflowPostgresqlFailureV1, projectDurableWorkflowDatabaseSafeFailureV2 } from "@/lib/server/productionWorkflowRuntime/durableTransaction";
import type { DurableWorkflowDatabaseCommand, DurableWorkflowDatabaseExecutionResult, DurableWorkflowDatabaseRow, DurableWorkflowTransactionOptions, DurableWorkflowTransactionSession, DurableWorkflowTransactionSessionBeginResult, DurableWorkflowTransactionSessionCommitResult, DurableWorkflowTransactionSessionFactory, DurableWorkflowTransactionSessionRollbackResult } from "@/lib/server/productionWorkflowRuntime/durableTransaction";
import { resolvePostgreSQLSliceAStatementV1 } from "@/lib/server/productionWorkflowRuntime/postgresqlStores";
import type { PostgreSQLSliceAReadSession, PostgreSQLSliceAStatement, PostgreSQLSliceAStatementCatalog, PostgreSQLSliceAStatementCatalogRegistrar } from "@/lib/server/productionWorkflowRuntime/postgresqlStores";

function scalar(value:unknown):null|string|boolean|number|Uint8Array{
  if(value===null||typeof value==="string"||typeof value==="boolean"||typeof value==="number")return value;if(value instanceof Uint8Array)return Uint8Array.from(value);return JSON.stringify(value);
}
function bridgeResult(result:PostgreSQLQueryResult,statement:PostgreSQLSliceAStatement):DurableWorkflowDatabaseExecutionResult{
  if(result.status==="not-found"||result.status==="cardinality-conflict")return result;
  if(result.status==="failure")return projectDurableWorkflowDatabaseSafeFailureV2({source:result,failure:classifyDurableWorkflowPostgresqlFailureV1({classificationVersion:"1.0",issue:result.issue,phase:"query-execution",statement:{accessMode:statement.accessMode}}).failure});
  const rows:DurableWorkflowDatabaseRow[]=result.rows.map((row)=>Object.freeze(Object.fromEntries(Object.entries(row).map(([key,value])=>[key,scalar(value)]))));return{status:"success",rows:Object.freeze(rows),rowCount:result.rowCount};
}

export class SliceATestStatementBridge implements PostgreSQLSliceAStatementCatalogRegistrar{
  readonly productionReady=false;private readonly statements=new Map<string,PostgreSQLSliceAStatement>();private readonly pool:PostgreSQLConnectionPoolAdapter;
  constructor(config:PostgreSQLConnectionConfig){this.pool=new PostgreSQLConnectionPoolAdapter(config);}
  register(catalog:PostgreSQLSliceAStatementCatalog){for(const entry of catalog.statements){const current=this.statements.get(entry.statementId);if(current&&current.sql!==entry.sql)return"rejected";this.statements.set(entry.statementId,Object.freeze({...entry}));}return"registered";}
  async start(){return this.pool.start();}
  sessionFactory():DurableWorkflowTransactionSessionFactory{return Object.freeze({acquire:async()=>{const connection=await this.pool.checkout();if("status" in connection)return{status:"unavailable" as const};return{status:"acquired" as const,session:this.transactionSession(connection)};}});}
  private transactionSession(connection:PostgreSQLConnection):DurableWorkflowTransactionSession{
    let transaction:PostgreSQLTransactionConnection|undefined;
    const execute=async(command:DurableWorkflowDatabaseCommand)=>{if(!transaction)return{status:"failure",failure:"transaction-aborted",retryable:false} as const;const resolution=resolvePostgreSQLSliceAStatementV1({catalogVersion:"1.0",statements:Object.freeze([...this.statements.values()])},command);if(resolution.status!=="resolved")return{status:"failure",failure:"internal-failure",retryable:false} as const;return bridgeResult(await transaction.query(resolution.value.query),resolution.value.statement);};
    return Object.freeze({begin:async(options:DurableWorkflowTransactionOptions):Promise<DurableWorkflowTransactionSessionBeginResult>=>{const begun=await connection.begin();if("status" in begun)return{status:"failure",failure:"unavailable",connectionAction:"discard"};transaction=begun;const mode=`SET TRANSACTION ISOLATION LEVEL ${options.isolation==="serializable"?"SERIALIZABLE":"READ COMMITTED"} ${options.accessMode==="read-only"?"READ ONLY":"READ WRITE"}`;const configured=await transaction.query({statementId:"slice-a.test.transaction-options",text:mode,values:[],expectedResult:"none"});return configured.status==="success"?{status:"active"}:{status:"failure",failure:"transaction-aborted",connectionAction:"release"};},execute,commit:async():Promise<DurableWorkflowTransactionSessionCommitResult>=>{if(!transaction)return{status:"failure",failure:"internal-failure"};const result=await transaction.commit();if(result.status==="committed")return result;if(result.status==="unknown-outcome"||result.status==="connection-unavailable")return{status:"unknown-outcome"};return{status:"failure",failure:"transaction-aborted"};},rollback:async():Promise<DurableWorkflowTransactionSessionRollbackResult>=>{if(!transaction)return{status:"rollback-failed"};const result=await transaction.rollback();return result.status==="rolled-back"?result:result.status==="connection-lost"?result:{status:"rollback-failed"};},release:()=>{transaction?.release();},discard:()=>{connection.discard();}});
  }
  async acquireReadSession():Promise<Readonly<{session:PostgreSQLSliceAReadSession;state():"active"|"closed";release():"released"|"already-released"}>>{const connection=await this.pool.checkout();if("status" in connection)throw new Error("read-session-unavailable");let active=true;const database=Object.freeze({capabilityVersion:"1.0" as const,execute:async(command:DurableWorkflowDatabaseCommand)=>{if(!active)return{status:"failure",failure:"transaction-aborted",retryable:false} as const;const resolution=resolvePostgreSQLSliceAStatementV1({catalogVersion:"1.0",statements:Object.freeze([...this.statements.values()])},command);if(resolution.status!=="resolved")return{status:"failure",failure:"internal-failure",retryable:false} as const;return bridgeResult(await connection.query(resolution.value.query),resolution.value.statement);}});return Object.freeze({session:Object.freeze({sessionVersion:"1.0",database}),state:()=>active?"active":"closed",release:()=>{if(!active)return"already-released";active=false;connection.release();return"released";}});}
  close(){return this.pool.close();}
}
